### ISSUE TITLE
Brush Listing missing OutlineVariant

### ISSUE THREAD

**Issue by NVLudwig** [unoplatform/Uno.Themes#1000]
## On which page?
https://github.com/unoplatform/Uno.Themes/blob/master/src/library/Uno.Material/Styles/Application/v2/SharedColors.xaml

## What's wrong?
No mention of OutlineVariant

## Any feedback?
Add Outline Variant and it's siblings

Note: It's done in this related page https://github.com/unoplatform/Uno.Themes/blob/master/src/library/Uno.Material/Styles/Application/v2/SharedColorPalette.xaml

**Comment by agneszitte** [comment]
Work was done on this PR from @eriklimakc https://github.com/unoplatform/Uno.Themes/pull/1166
But @kazo0 I think that we should have docs in place that list colors/brushes and fonts used for Material

**Comment by Xiaoy312** [comment]
we have the fonts here: https://github.com/unoplatform/Uno.Themes/blob/master/doc/styles/TextBlock.md#lightweight-styling-typography
we do miss a table for colors
not sure about brush themselves, since they are just a cartesian product of color x opacity

**Comment by NVLudwig** [comment]
@Xiaoy312 is this what you need?
https://github.com/unoplatform/Uno.Themes/blob/master/src/library/Uno.Material/Styles/Application/v2/SharedColors.xaml
https://github.com/unoplatform/Uno.Themes/blob/master/src/library/Uno.Material/Styles/Application/v2/SharedColorPalette.xaml

**Comment by Xiaoy312** [comment]
im aware of their existance,
but i was adding to/replying agnes's comment regarding docs for color/brush

**Comment by agneszitte** [comment]
Yes, @NVLudwig what I am checking with @kazo0 and @Xiaoy312 is regarding the fact we don't have proper documentation for colors (and brushes if needed also) on our side for the libs.

@NVLudwig your main issue here is already fixed by @eriklimakc with this PR -> https://github.com/unoplatform/Uno.Themes/pull/1166. I am just making sure the documentation is properly done as well before we close the issue.

**Comment by agneszitte** [comment]
@Darsh0307 will help us add the missing documentation for this, will sync with you on Monday

**Comment by kazo0** [comment]
@Darsh0307 for this issue we need to create a new page in the documentation folder, called something like material-colors.md.

Similar to [material-controls-styles.md](https://github.com/unoplatform/Uno.Themes/blob/master/doc/material-controls-styles.md)

We should have a section for Colors where you can create a table based on the colors defined here: https://github.com/unoplatform/Uno.Themes/blob/d19569b466a8dc4e533d5fcedee113804592d75e/src/library/Uno.Material/Styles/Application/v2/SharedColorPalette.xaml#L11-L118

So a table something like 

## Colors
Color|Light|Dark
-|-|-
PrimaryColor|#5946D2|C7BFFF
etc.

## Brushes
Brush|Color
-|-
PrimaryBrush|PrimaryColor
PrimaryHoverBrush|PrimaryColor@HoverOpacity
etc.

**Comment by kazo0** [comment]
Also don't forget to then add a reference to that new page in the [toc.yml](https://github.com/unoplatform/Uno.Themes/blob/master/doc/toc.yml)

**Comment by Xiaoy312** [comment]
# Colors
Key|LightValue|DarkValue
-|-|-
PrimaryColor|#C7BFFF|#C7BFFF
OnPrimaryColor|#2A009F|#2A009F
PrimaryContainerColor|#4129BA|#4129BA
OnPrimaryContainerColor|#E4DFFF|#E4DFFF
PrimaryInverseColor|#2A009F|#2A009F
PrimaryVariantDarkColor|#4128BA|#4128BA
PrimaryVariantLightColor|#C8BFFF|#C8BFFF
SecondaryColor|#CDC2DC|#CDC2DC
OnSecondaryColor|#332D41|#332D41
SecondaryContainerColor|#433C52|#433C52
OnSecondaryContainerColor|#EDDFFF|#EDDFFF
SecondaryVariantDarkColor|#441F8A|#441F8A
SecondaryVariantLightColor|#EBE6F1|#EBE6F1
TertiaryColor|#9FCAFF|#9FCAFF
OnTertiaryColor|#003258|#003258
TertiaryContainerColor|#00497D|#00497D
OnTertiaryContainerColor|#D1E4FF|#D1E4FF
ErrorColor|#FFB4AB|#FFB4AB
OnErrorColor|#690005|#690005
ErrorContainerColor|#93000A|#93000A
OnErrorContainerColor|#FFDAD6|#FFDAD6
BackgroundColor|#1C1B1F|#1C1B1F
OnBackgroundColor|#E5E1E6|#E5E1E6
SurfaceColor|#302D37|#302D37
OnSurfaceColor|#E6E1E5|#E6E1E5
SurfaceVariantColor|#47464F|#47464F
OnSurfaceVariantColor|#C9C5D0|#C9C5D0
SurfaceInverseColor|#E6E1E5|#E6E1E5
OnSurfaceInverseColor|#1C1B1F|#1C1B1F
SurfaceTintColor|#C7BFFF|#C7BFFF
OutlineColor|#928F99|#928F99
OutlineVariantColor|#57545D|#57545D

# Opacities
Key|Value
-|-
HoverOpacity|0.08
FocusedOpacity|0.12
PressedOpacity|0.12
DraggedOpacity|0.16
SelectedOpacity|0.16
MediumOpacity|0.54
LowOpacity|0.32
DisabledOpacity|0.38
DisabledLowOpacity|0.12

# Brushes
Key|Color|Opacity
-|-|-
PrimaryBrush|PrimaryColor|1
PrimaryHoverBrush|PrimaryColor|HoverOpacity
PrimaryFocusedBrush|PrimaryColor|FocusedOpacity
PrimaryPressedBrush|PrimaryColor|PressedOpacity
PrimaryDraggedBrush|PrimaryColor|DraggedOpacity
PrimarySelectedBrush|PrimaryColor|SelectedOpacity
PrimaryMediumBrush|PrimaryColor|MediumOpacity
PrimaryLowBrush|PrimaryColor|LowOpacity
PrimaryDisabledBrush|PrimaryColor|DisabledOpacity
PrimaryDisabledLowBrush|PrimaryColor|DisabledLowOpacity
PrimaryInverseBrush|PrimaryInverseColor|1
PrimaryInverseHoverBrush|PrimaryInverseColor|HoverOpacity
PrimaryInverseFocusedBrush|PrimaryInverseColor|FocusedOpacity
PrimaryInversePressedBrush|PrimaryInverseColor|PressedOpacity
PrimaryInverseDraggedBrush|PrimaryInverseColor|DraggedOpacity
PrimaryInverseSelectedBrush|PrimaryInverseColor|SelectedOpacity
PrimaryInverseMediumBrush|PrimaryInverseColor|MediumOpacity
PrimaryInverseLowBrush|PrimaryInverseColor|LowOpacity
PrimaryInverseDisabledBrush|PrimaryInverseColor|DisabledOpacity
PrimaryInverseDisabledLowBrush|PrimaryInverseColor|DisabledLowOpacity
OnPrimaryBrush|OnPrimaryColor|1
OnPrimaryHoverBrush|OnPrimaryColor|HoverOpacity
OnPrimaryFocusedBrush|OnPrimaryColor|FocusedOpacity
OnPrimaryPressedBrush|OnPrimaryColor|PressedOpacity
OnPrimaryDraggedBrush|OnPrimaryColor|DraggedOpacity
OnPrimarySelectedBrush|OnPrimaryColor|SelectedOpacity
OnPrimaryMediumBrush|OnPrimaryColor|MediumOpacity
OnPrimaryLowBrush|OnPrimaryColor|LowOpacity
OnPrimaryDisabledBrush|OnPrimaryColor|DisabledOpacity
OnPrimaryDisabledLowBrush|OnPrimaryColor|DisabledLowOpacity
PrimaryContainerBrush|PrimaryContainerColor|1
PrimaryContainerHoverBrush|PrimaryContainerColor|HoverOpacity
PrimaryContainerFocusedBrush|PrimaryContainerColor|FocusedOpacity
PrimaryContainerPressedBrush|PrimaryContainerColor|PressedOpacity
PrimaryContainerDraggedBrush|PrimaryContainerColor|DraggedOpacity
PrimaryContainerSelectedBrush|PrimaryContainerColor|SelectedOpacity
PrimaryContainerMediumBrush|PrimaryContainerColor|MediumOpacity
PrimaryContainerLowBrush|PrimaryContainerColor|LowOpacity
PrimaryContainerDisabledBrush|PrimaryContainerColor|DisabledOpacity
PrimaryContainerDisabledLowBrush|PrimaryContainerColor|DisabledLowOpacity
OnPrimaryContainerBrush|OnPrimaryContainerColor|1
OnPrimaryContainerHoverBrush|OnPrimaryContainerColor|HoverOpacity
OnPrimaryContainerFocusedBrush|OnPrimaryContainerColor|FocusedOpacity
OnPrimaryContainerPressedBrush|OnPrimaryContainerColor|PressedOpacity
OnPrimaryContainerDraggedBrush|OnPrimaryContainerColor|DraggedOpacity
OnPrimaryContainerSelectedBrush|OnPrimaryContainerColor|SelectedOpacity
OnPrimaryContainerMediumBrush|OnPrimaryContainerColor|MediumOpacity
OnPrimaryContainerLowBrush|OnPrimaryContainerColor|LowOpacity
OnPrimaryContainerDisabledBrush|OnPrimaryContainerColor|DisabledOpacity
OnPrimaryContainerDisabledLowBrush|OnPrimaryContainerColor|DisabledLowOpacity
PrimaryVariantLightBrush|PrimaryVariantLightColor|1
PrimaryVariantLightHoverBrush|PrimaryVariantLightColor|HoverOpacity
PrimaryVariantLightFocusedBrush|PrimaryVariantLightColor|FocusedOpacity
PrimaryVariantLightPressedBrush|PrimaryVariantLightColor|PressedOpacity
PrimaryVariantLightDraggedBrush|PrimaryVariantLightColor|DraggedOpacity
PrimaryVariantLightSelectedBrush|PrimaryVariantLightColor|SelectedOpacity
PrimaryVariantLightMediumBrush|PrimaryVariantLightColor|MediumOpacity
PrimaryVariantLightLowBrush|PrimaryVariantLightColor|LowOpacity
PrimaryVariantLightDisabledBrush|PrimaryVariantLightColor|DisabledOpacity
PrimaryVariantLightDisabledLowBrush|PrimaryVariantLightColor|DisabledLowOpacity
PrimaryVariantDarkBrush|PrimaryVariantDarkColor|1
PrimaryVariantDarkHoverBrush|PrimaryVariantDarkColor|HoverOpacity
PrimaryVariantDarkFocusedBrush|PrimaryVariantDarkColor|FocusedOpacity
PrimaryVariantDarkPressedBrush|PrimaryVariantDarkColor|PressedOpacity
PrimaryVariantDarkDraggedBrush|PrimaryVariantDarkColor|DraggedOpacity
PrimaryVariantDarkSelectedBrush|PrimaryVariantDarkColor|SelectedOpacity
PrimaryVariantDarkMediumBrush|PrimaryVariantDarkColor|MediumOpacity
PrimaryVariantDarkLowBrush|PrimaryVariantDarkColor|LowOpacity
PrimaryVariantDarkDisabledBrush|PrimaryVariantDarkColor|DisabledOpacity
PrimaryVariantDarkDisabledLowBrush|PrimaryVariantDarkColor|DisabledLowOpacity
SecondaryBrush|SecondaryColor|1
SecondaryHoverBrush|SecondaryColor|HoverOpacity
SecondaryFocusedBrush|SecondaryColor|FocusedOpacity
SecondaryPressedBrush|SecondaryColor|PressedOpacity
SecondaryDraggedBrush|SecondaryColor|DraggedOpacity
SecondarySelectedBrush|SecondaryColor|SelectedOpacity
SecondaryMediumBrush|SecondaryColor|MediumOpacity
SecondaryLowBrush|SecondaryColor|LowOpacity
SecondaryDisabledBrush|SecondaryColor|DisabledOpacity
SecondaryDisabledLowBrush|SecondaryColor|DisabledLowOpacity
OnSecondaryBrush|OnSecondaryColor|1
OnSecondaryHoverBrush|OnSecondaryColor|HoverOpacity
OnSecondaryFocusedBrush|OnSecondaryColor|FocusedOpacity
OnSecondaryPressedBrush|OnSecondaryColor|PressedOpacity
OnSecondaryDraggedBrush|OnSecondaryColor|DraggedOpacity
OnSecondarySelectedBrush|OnSecondaryColor|SelectedOpacity
OnSecondaryMediumBrush|OnSecondaryColor|MediumOpacity
OnSecondaryLowBrush|OnSecondaryColor|LowOpacity
OnSecondaryDisabledBrush|OnSecondaryColor|DisabledOpacity
OnSecondaryDisabledLowBrush|OnSecondaryColor|DisabledLowOpacity
SecondaryContainerBrush|SecondaryContainerColor|1
SecondaryContainerHoverBrush|SecondaryContainerColor|HoverOpacity
SecondaryContainerFocusedBrush|SecondaryContainerColor|FocusedOpacity
SecondaryContainerPressedBrush|SecondaryContainerColor|PressedOpacity
SecondaryContainerDraggedBrush|SecondaryContainerColor|DraggedOpacity
SecondaryContainerSelectedBrush|SecondaryContainerColor|SelectedOpacity
SecondaryContainerMediumBrush|SecondaryContainerColor|MediumOpacity
SecondaryContainerLowBrush|SecondaryContainerColor|LowOpacity
SecondaryContainerDisabledBrush|SecondaryContainerColor|DisabledOpacity
SecondaryContainerDisabledLowBrush|SecondaryContainerColor|DisabledLowOpacity
OnSecondaryContainerBrush|OnSecondaryContainerColor|1
OnSecondaryContainerHoverBrush|OnSecondaryContainerColor|HoverOpacity
OnSecondaryContainerFocusedBrush|OnSecondaryContainerColor|FocusedOpacity
OnSecondaryContainerPressedBrush|OnSecondaryContainerColor|PressedOpacity
OnSecondaryContainerDraggedBrush|OnSecondaryContainerColor|DraggedOpacity
OnSecondaryContainerSelectedBrush|OnSecondaryContainerColor|SelectedOpacity
OnSecondaryContainerMediumBrush|OnSecondaryContainerColor|MediumOpacity
OnSecondaryContainerLowBrush|OnSecondaryContainerColor|LowOpacity
OnSecondaryContainerDisabledBrush|OnSecondaryContainerColor|DisabledOpacity
OnSecondaryContainerDisabledLowBrush|OnSecondaryContainerColor|DisabledLowOpacity
SecondaryVariantLightBrush|SecondaryVariantLightColor|1
SecondaryVariantLightHoverBrush|SecondaryVariantLightColor|HoverOpacity
SecondaryVariantLightFocusedBrush|SecondaryVariantLightColor|FocusedOpacity
SecondaryVariantLightPressedBrush|SecondaryVariantLightColor|PressedOpacity
SecondaryVariantLightDraggedBrush|SecondaryVariantLightColor|DraggedOpacity
SecondaryVariantLightSelectedBrush|SecondaryVariantLightColor|SelectedOpacity
SecondaryVariantLightMediumBrush|SecondaryVariantLightColor|MediumOpacity
SecondaryVariantLightLowBrush|SecondaryVariantLightColor|LowOpacity
SecondaryVariantLightDisabledBrush|SecondaryVariantLightColor|DisabledOpacity
SecondaryVariantLightDisabledLowBrush|SecondaryVariantLightColor|DisabledLowOpacity
SecondaryVariantDarkBrush|SecondaryVariantDarkColor|1
SecondaryVariantDarkHoverBrush|SecondaryVariantDarkColor|HoverOpacity
SecondaryVariantDarkFocusedBrush|SecondaryVariantDarkColor|FocusedOpacity
SecondaryVariantDarkPressedBrush|SecondaryVariantDarkColor|PressedOpacity
SecondaryVariantDarkDraggedBrush|SecondaryVariantDarkColor|DraggedOpacity
SecondaryVariantDarkSelectedBrush|SecondaryVariantDarkColor|SelectedOpacity
SecondaryVariantDarkMediumBrush|SecondaryVariantDarkColor|MediumOpacity
SecondaryVariantDarkLowBrush|SecondaryVariantDarkColor|LowOpacity
SecondaryVariantDarkDisabledBrush|SecondaryVariantDarkColor|DisabledOpacity
SecondaryVariantDarkDisabledLowBrush|SecondaryVariantDarkColor|DisabledLowOpacity
TertiaryBrush|TertiaryColor|1
TertiaryHoverBrush|TertiaryColor|HoverOpacity
TertiaryFocusedBrush|TertiaryColor|FocusedOpacity
TertiaryPressedBrush|TertiaryColor|PressedOpacity
TertiaryDraggedBrush|TertiaryColor|DraggedOpacity
TertiarySelectedBrush|TertiaryColor|SelectedOpacity
TertiaryMediumBrush|TertiaryColor|MediumOpacity
TertiaryLowBrush|TertiaryColor|LowOpacity
TertiaryDisabledBrush|TertiaryColor|DisabledOpacity
TertiaryDisabledLowBrush|TertiaryColor|DisabledLowOpacity
OnTertiaryBrush|OnTertiaryColor|1
OnTertiaryHoverBrush|OnTertiaryColor|HoverOpacity
OnTertiaryFocusedBrush|OnTertiaryColor|FocusedOpacity
OnTertiaryPressedBrush|OnTertiaryColor|PressedOpacity
OnTertiaryDraggedBrush|OnTertiaryColor|DraggedOpacity
OnTertiarySelectedBrush|OnTertiaryColor|SelectedOpacity
OnTertiaryMediumBrush|OnTertiaryColor|MediumOpacity
OnTertiaryLowBrush|OnTertiaryColor|LowOpacity
OnTertiaryDisabledBrush|OnTertiaryColor|DisabledOpacity
OnTertiaryDisabledLowBrush|OnTertiaryColor|DisabledLowOpacity
TertiaryContainerBrush|TertiaryContainerColor|1
TertiaryContainerHoverBrush|TertiaryContainerColor|HoverOpacity
TertiaryContainerFocusedBrush|TertiaryContainerColor|FocusedOpacity
TertiaryContainerPressedBrush|TertiaryContainerColor|PressedOpacity
TertiaryContainerDraggedBrush|TertiaryContainerColor|DraggedOpacity
TertiaryContainerSelectedBrush|TertiaryContainerColor|SelectedOpacity
TertiaryContainerMediumBrush|TertiaryContainerColor|MediumOpacity
TertiaryContainerLowBrush|TertiaryContainerColor|LowOpacity
TertiaryContainerDisabledBrush|TertiaryContainerColor|DisabledOpacity
TertiaryContainerDisabledLowBrush|TertiaryContainerColor|DisabledLowOpacity
OnTertiaryContainerBrush|OnTertiaryContainerColor|1
OnTertiaryContainerHoverBrush|OnTertiaryContainerColor|HoverOpacity
OnTertiaryContainerFocusedBrush|OnTertiaryContainerColor|FocusedOpacity
OnTertiaryContainerPressedBrush|OnTertiaryContainerColor|PressedOpacity
OnTertiaryContainerDraggedBrush|OnTertiaryContainerColor|DraggedOpacity
OnTertiaryContainerSelectedBrush|OnTertiaryContainerColor|SelectedOpacity
OnTertiaryContainerMediumBrush|OnTertiaryContainerColor|MediumOpacity
OnTertiaryContainerLowBrush|OnTertiaryContainerColor|LowOpacity
OnTertiaryContainerDisabledBrush|OnTertiaryContainerColor|DisabledOpacity
OnTertiaryContainerDisabledLowBrush|OnTertiaryContainerColor|DisabledLowOpacity
ErrorBrush|ErrorColor|1
ErrorHoverBrush|ErrorColor|HoverOpacity
ErrorFocusedBrush|ErrorColor|FocusedOpacity
ErrorPressedBrush|ErrorColor|PressedOpacity
ErrorDraggedBrush|ErrorColor|DraggedOpacity
ErrorSelectedBrush|ErrorColor|SelectedOpacity
ErrorMediumBrush|ErrorColor|MediumOpacity
ErrorLowBrush|ErrorColor|LowOpacity
ErrorDisabledBrush|ErrorColor|DisabledOpacity
ErrorDisabledLowBrush|ErrorColor|DisabledLowOpacity
OnErrorBrush|OnErrorColor|1
OnErrorHoverBrush|OnErrorColor|HoverOpacity
OnErrorFocusedBrush|OnErrorColor|FocusedOpacity
OnErrorPressedBrush|OnErrorColor|PressedOpacity
OnErrorDraggedBrush|OnErrorColor|DraggedOpacity
OnErrorSelectedBrush|OnErrorColor|SelectedOpacity
OnErrorMediumBrush|OnErrorColor|MediumOpacity
OnErrorLowBrush|OnErrorColor|LowOpacity
OnErrorDisabledBrush|OnErrorColor|DisabledOpacity
OnErrorDisabledLowBrush|OnErrorColor|DisabledLowOpacity
ErrorContainerBrush|ErrorContainerColor|1
ErrorContainerHoverBrush|ErrorContainerColor|HoverOpacity
ErrorContainerFocusedBrush|ErrorContainerColor|FocusedOpacity
ErrorContainerPressedBrush|ErrorContainerColor|PressedOpacity
ErrorContainerDraggedBrush|ErrorContainerColor|DraggedOpacity
ErrorContainerSelectedBrush|ErrorContainerColor|SelectedOpacity
ErrorContainerMediumBrush|ErrorContainerColor|MediumOpacity
ErrorContainerLowBrush|ErrorContainerColor|LowOpacity
ErrorContainerDisabledBrush|ErrorContainerColor|DisabledOpacity
ErrorContainerDisabledLowBrush|ErrorContainerColor|DisabledLowOpacity
OnErrorContainerBrush|OnErrorContainerColor|1
OnErrorContainerHoverBrush|OnErrorContainerColor|HoverOpacity
OnErrorContainerFocusedBrush|OnErrorContainerColor|FocusedOpacity
OnErrorContainerPressedBrush|OnErrorContainerColor|PressedOpacity
OnErrorContainerDraggedBrush|OnErrorContainerColor|DraggedOpacity
OnErrorContainerSelectedBrush|OnErrorContainerColor|SelectedOpacity
OnErrorContainerMediumBrush|OnErrorContainerColor|MediumOpacity
OnErrorContainerLowBrush|OnErrorContainerColor|LowOpacity
OnErrorContainerDisabledBrush|OnErrorContainerColor|DisabledOpacity
OnErrorContainerDisabledLowBrush|OnErrorContainerColor|DisabledLowOpacity
BackgroundBrush|BackgroundColor|1
BackgroundHoverBrush|BackgroundColor|HoverOpacity
BackgroundFocusedBrush|BackgroundColor|FocusedOpacity
BackgroundPressedBrush|BackgroundColor|PressedOpacity
BackgroundDraggedBrush|BackgroundColor|DraggedOpacity
BackgroundSelectedBrush|BackgroundColor|SelectedOpacity
BackgroundMediumBrush|BackgroundColor|MediumOpacity
BackgroundLowBrush|BackgroundColor|LowOpacity
BackgroundDisabledBrush|BackgroundColor|DisabledOpacity
BackgroundDisabledLowBrush|BackgroundColor|DisabledLowOpacity
OnBackgroundBrush|OnBackgroundColor|1
OnBackgroundHoverBrush|OnBackgroundColor|HoverOpacity
OnBackgroundFocusedBrush|OnBackgroundColor|FocusedOpacity
OnBackgroundPressedBrush|OnBackgroundColor|PressedOpacity
OnBackgroundDraggedBrush|OnBackgroundColor|DraggedOpacity
OnBackgroundSelectedBrush|OnBackgroundColor|SelectedOpacity
OnBackgroundMediumBrush|OnBackgroundColor|MediumOpacity
OnBackgroundLowBrush|OnBackgroundColor|LowOpacity
OnBackgroundDisabledBrush|OnBackgroundColor|DisabledOpacity
OnBackgroundDisabledLowBrush|OnBackgroundColor|DisabledLowOpacity
SurfaceBrush|SurfaceColor|1
SurfaceHoverBrush|SurfaceColor|HoverOpacity
SurfaceFocusedBrush|SurfaceColor|FocusedOpacity
SurfacePressedBrush|SurfaceColor|PressedOpacity
SurfaceDraggedBrush|SurfaceColor|DraggedOpacity
SurfaceSelectedBrush|SurfaceColor|SelectedOpacity
SurfaceMediumBrush|SurfaceColor|MediumOpacity
SurfaceLowBrush|SurfaceColor|LowOpacity
SurfaceDisabledBrush|SurfaceColor|DisabledOpacity
SurfaceDisabledLowBrush|SurfaceColor|DisabledLowOpacity
OnSurfaceBrush|OnSurfaceColor|1
OnSurfaceHoverBrush|OnSurfaceColor|HoverOpacity
OnSurfaceFocusedBrush|OnSurfaceColor|FocusedOpacity
OnSurfacePressedBrush|OnSurfaceColor|PressedOpacity
OnSurfaceDraggedBrush|OnSurfaceColor|DraggedOpacity
OnSurfaceSelectedBrush|OnSurfaceColor|SelectedOpacity
OnSurfaceMediumBrush|OnSurfaceColor|MediumOpacity
OnSurfaceLowBrush|OnSurfaceColor|DisabledOpacity
OnSurfaceDisabledBrush|OnSurfaceColor|DisabledOpacity
OnSurfaceDisabledLowBrush|OnSurfaceColor|DisabledLowOpacity
SurfaceVariantBrush|SurfaceVariantColor|1
SurfaceVariantHoverBrush|SurfaceVariantColor|HoverOpacity
SurfaceVariantFocusedBrush|SurfaceVariantColor|FocusedOpacity
SurfaceVariantPressedBrush|SurfaceVariantColor|PressedOpacity
SurfaceVariantDraggedBrush|SurfaceVariantColor|DraggedOpacity
SurfaceVariantSelectedBrush|SurfaceVariantColor|SelectedOpacity
SurfaceVariantMediumBrush|SurfaceVariantColor|MediumOpacity
SurfaceVariantLowBrush|SurfaceVariantColor|LowOpacity
SurfaceVariantDisabledBrush|SurfaceVariantColor|DisabledOpacity
SurfaceVariantDisabledLowBrush|SurfaceVariantColor|DisabledLowOpacity
OnSurfaceVariantBrush|OnSurfaceVariantColor|1
OnSurfaceVariantHoverBrush|OnSurfaceVariantColor|HoverOpacity
OnSurfaceVariantFocusedBrush|OnSurfaceVariantColor|FocusedOpacity
OnSurfaceVariantPressedBrush|OnSurfaceVariantColor|PressedOpacity
OnSurfaceVariantDraggedBrush|OnSurfaceVariantColor|DraggedOpacity
OnSurfaceVariantSelectedBrush|OnSurfaceVariantColor|SelectedOpacity
OnSurfaceVariantMediumBrush|OnSurfaceVariantColor|MediumOpacity
OnSurfaceVariantLowBrush|OnSurfaceVariantColor|LowOpacity
OnSurfaceVariantDisabledBrush|OnSurfaceVariantColor|DisabledOpacity
OnSurfaceVariantDisabledLowBrush|OnSurfaceVariantColor|DisabledLowOpacity
SurfaceInverseBrush|SurfaceInverseColor|1
SurfaceInverseHoverBrush|SurfaceInverseColor|HoverOpacity
SurfaceInverseFocusedBrush|SurfaceInverseColor|FocusedOpacity
SurfaceInversePressedBrush|SurfaceInverseColor|PressedOpacity
SurfaceInverseDraggedBrush|SurfaceInverseColor|DraggedOpacity
SurfaceInverseSelectedBrush|SurfaceInverseColor|SelectedOpacity
SurfaceInverseMediumBrush|SurfaceInverseColor|MediumOpacity
SurfaceInverseLowBrush|SurfaceInverseColor|LowOpacity
SurfaceInverseDisabledBrush|SurfaceInverseColor|DisabledOpacity
SurfaceInverseDisabledLowBrush|SurfaceInverseColor|DisabledLowOpacity
OnSurfaceInverseBrush|OnSurfaceInverseColor|1
OnSurfaceInverseHoverBrush|OnSurfaceInverseColor|HoverOpacity
OnSurfaceInverseFocusedBrush|OnSurfaceInverseColor|FocusedOpacity
OnSurfaceInversePressedBrush|OnSurfaceInverseColor|PressedOpacity
OnSurfaceInverseDraggedBrush|OnSurfaceInverseColor|DraggedOpacity
OnSurfaceInverseSelectedBrush|OnSurfaceInverseColor|SelectedOpacity
OnSurfaceInverseMediumBrush|OnSurfaceInverseColor|MediumOpacity
OnSurfaceInverseLowBrush|OnSurfaceInverseColor|LowOpacity
OnSurfaceInverseDisabledBrush|OnSurfaceInverseColor|DisabledOpacity
OnSurfaceInverseDisabledLowBrush|OnSurfaceInverseColor|DisabledLowOpacity
OutlineBrush|OutlineColor|1
OutlineHoverBrush|OutlineColor|HoverOpacity
OutlineFocusedBrush|OutlineColor|FocusedOpacity
OutlinePressedBrush|OutlineColor|PressedOpacity
OutlineDraggedBrush|OutlineColor|DraggedOpacity
OutlineSelectedBrush|OutlineColor|SelectedOpacity
OutlineMediumBrush|OutlineColor|MediumOpacity
OutlineLowBrush|OutlineColor|LowOpacity
OutlineDisabledBrush|OutlineColor|DisabledOpacity
OutlineDisabledLowBrush|OutlineColor|DisabledLowOpacity
OutlineVariantBrush|OutlineVariantColor|1
OutlineVariantHoverBrush|OutlineVariantColor|HoverOpacity
OutlineVariantFocusedBrush|OutlineVariantColor|FocusedOpacity
OutlineVariantPressedBrush|OutlineVariantColor|PressedOpacity
OutlineVariantDraggedBrush|OutlineVariantColor|DraggedOpacity
OutlineVariantSelectedBrush|OutlineVariantColor|SelectedOpacity
OutlineVariantMediumBrush|OutlineVariantColor|MediumOpacity
OutlineVariantLowBrush|OutlineVariantColor|LowOpacity
OutlineVariantDisabledBrush|OutlineVariantColor|DisabledOpacity
OutlineVariantDisabledLowBrush|OutlineVariantColor|DisabledLowOpacity
SurfaceTintBrush|SurfaceTintColor|1

**Comment by NVLudwig** [comment]
@Xiaoy312 Amazing Work. I used this table to review the Figma file so we are better aligned and made a few changes
<img width="253" alt="image" src="https://github.com/unoplatform/Uno.Themes/assets/29584087/399e3b98-9821-49c9-be3a-4b614100134a">

**Figma updates**
...LowBrushes are all 32% opacity (from 34)
...MediumBrushes are all 64% opacity (from 60 and 74)
...DisabledBrushes are all 12% opacity (from 8 and 12)
...SelectedBrushes are all 16% opacity (from 8)

**Requested Theme updates**
<img width="236" alt="image" src="https://github.com/unoplatform/Uno.Themes/assets/29584087/f2253ab6-6589-48f0-bd5a-cd09987aef1a">

I don't have any references to "DisabledLow" in the Figma file I guess it was created to deal with the previously 8% brushes (I guess you can bump them up to 12 and keep the name if it's easier but it has no equivalent in the Figma anymore)

**Comment by agneszitte** [comment]
> @Xiaoy312 Amazing Work. I used this table to review the Figma file so we are better aligned and made a few changes <img alt="image" width="253" src="https://user-images.githubusercontent.com/29584087/272996743-399e3b98-9821-49c9-be3a-4b614100134a.png">
> 
> **Figma updates** ...LowBrushes are all 32% opacity (from 38) ...MediumBrushes are all 64% opacity (from 60 and 74) ...DisabledBrushes are all 12% opacity (from 8 and 12) ...SelectedBrushes are all 16% opacity (from 8)
> 
> **Requested Theme updates** <img alt="image" width="236" src="https://user-images.githubusercontent.com/29584087/273004379-f2253ab6-6589-48f0-bd5a-cd09987aef1a.png">
> 
> I don't have any references to "DisabledLow" in the Figma file I guess it was created to deal with the previously 8% brushes (I guess you can bump them up to 12 and keep the name if it's easier but it has no equivalent in the Figma anymore)
> 
> Here is the branch with the changes, let me know if we agree and I can merge this [figma.com/file/trM3i5qUPmFBcnxWXXmnuF/branch/pFOZn3adihAKdAAoznJKqy/Uno-Platform-Material-Toolkit?type=design&node-id=418%3A11077&mode=design&t=8UIsdUtDPryERAZ4-1](https://www.figma.com/file/trM3i5qUPmFBcnxWXXmnuF/branch/pFOZn3adihAKdAAoznJKqy/Uno-Platform-Material-Toolkit?type=design&node-id=418%3A11077&mode=design&t=8UIsdUtDPryERAZ4-1)

@Xiaoy312 Re-Opening this issue so we make sure to align with @NVLudwig's latest comment + we need to give him the go after so he can merge his branch on the main figma file

**Comment by Xiaoy312** [comment]
lets continue this in #1236 instead
