### ISSUE TITLE
[Material] Lightweight Styling - PipsPager Styles

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#1009]
Following the guidelines from https://github.com/unoplatform/Uno.Themes/issues/854, refactor the resources for all styles related to this control into ThemeDictionaries ("Default"/"Light") and make sure to reference these resources using the `ThemeResource` binding in ALL places within the style

**Comment by agneszitte** [comment]
Blocked by https://github.com/unoplatform/uno/issues/12496, will need to be investigated and fixed first

**Comment by agneszitte** [comment]
> Blocked by [unoplatform/uno#12496](https://github.com/unoplatform/uno/issues/12496), will need to be investigated and fixed first

Should be fixed by https://github.com/unoplatform/uno/pull/13016

**Comment by agneszitte** [comment]
> > Blocked by [unoplatform/uno#12496](https://github.com/unoplatform/uno/issues/12496), will need to be investigated and fixed first
> 
> Should be fixed by [unoplatform/uno#13016](https://github.com/unoplatform/uno/pull/13016)

Fixed in latest Uno

**Comment by agneszitte** [comment]
Closed with #1111 & #1147
