### ISSUE TITLE
[Chefs, TubePlayer] Need a Material style for the MediaPlayer

### ISSUE THREAD

**Issue by NVLudwig** [unoplatform/Uno.Themes#1032]
## What would you like to be added:
In Material the media player should display without using Windows specific elements such as: Acrylic background, Fluent font icons, Win UI scrubber.

## Why is this needed:
Porting compoenent to Material

## For which Platform:

- [x] UWP
- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] macOS

## Anything else we need to know?
Here is the link to the Figma File aka Source of truth :)
https://www.figma.com/file/trM3i5qUPmFBcnxWXXmnuF/branch/LXYP010W9oJANcAFpbDbef/Uno-Platform-Material-Toolkit?type=design&node-id=3082%3A107842&t=fdxl4yDystednvDw-1

**Comment by iurycarlos** [comment]
Related to https://github.com/unoplatform/Uno.Figma/pull/1700
