### ISSUE TITLE
[Lightweight Styling] Extract non-Brush values into lightweight resources

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#1067]
Following the example from the Button styles [here](https://github.com/unoplatform/Uno.Themes/blob/321b2154bc547e0b3202cca160b2def25d3b3685/src/library/Uno.Material/Styles/Controls/v2/Button.xaml#L17-L41), we should be extracting hardcoded values for things such as Margin, Padding, CornerRadius, etc. and placing them into lightweight styleable resources.

Taking the above Button style as an example, the only remaining step would be to move those resource definitions inside of the ThemeDictionaries and duplicate them across all dictionaries in the ThemeDictionaries

- [x] Button
- [x] CheckBox
- [x] TextBox
- [x] PasswordBox
- [x] ToggleButton
- [x] RadioButton
- [x] Slider
- [x] ProgressRing
- [x] ProgressBar
- [x] ComboBox
- [x] DatePicker
- [x] FloatingActionButton
- [ ] TextBlock Style
- [x] PipsPager
- [x] HyperlinkButton Style
- [x] NavigationView

**Comment by pictos** [comment]
Can I work on the `Button` control?

**Comment by nguyeenvy** [comment]
PasswordBox: https://github.com/unoplatform/Uno.Themes/pull/1051/files
CheckBox: https://github.com/unoplatform/Uno.Themes/pull/1048

**Comment by carlh98** [comment]
https://github.com/unoplatform/Uno.Themes/pull/1100
