### ISSUE TITLE
[Tube Player, Chefs] Need Themes to support new Navigation Bar with rich Content

### ISSUE THREAD

**Issue by NVLudwig** [unoplatform/Uno.Themes#1076]
[Tube Player] Need Themes to support [new Navigation Bar](https://www.figma.com/file/trM3i5qUPmFBcnxWXXmnuF/branch/EHVGWH2msgPMQYAWJC4cQy/Uno-Platform-Material-Toolkit?type=design&node-id=3082%3A106933&mode=design&t=mAZp3PdnbplpZHP1-1) with rich Content

## What would you like to be added:
Navigation Bar Figma compoenent was updated changes include:
• Option to have no leading action
• Option to display either:
     - none title
     - (Bitmap) image compoenent (or any other component)
     - Title

## Why is this needed:
Support more user scenarios like: 
     - NavBars withtout content, 
     - NavBars with Branding elements (tube Player, Chefs), 
     - Rich NavBars (Search Box à la Outlook)
     - NavBars withtout leading actions (Commerce App)

## For which Platform:

- [x] UWP
- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] macOS

## Anything else we need to know?

@carldebilly Tagging you because Plugin also needs to support this

**Comment by agneszitte** [comment]
@carldebilly can we open an issue on the plugin side please and the link the two ?

**Comment by weitzhandler** [comment]
The plugin issue has been closed, is this one resolved as well?
