### ISSUE TITLE
[Material] Lightweight Styling - ToggleButton Styles

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/Uno.Themes#1110]
Following the guidelines from https://github.com/unoplatform/Uno.Themes/issues/854, refactor the resources for all styles related to this control into ThemeDictionaries ("Default"/"Light") and make sure to reference these resources using the `ThemeResource` binding in ALL places within the style

**Comment by carlh98** [comment]
https://github.com/unoplatform/Uno.Themes/pull/1113 PR was merged

**Comment by agneszitte** [comment]
Closed with #1113 & #1131
