### ISSUE TITLE
[WinUI/Material] ComboBox ItemsSource crashing on Windows

### ISSUE THREAD

**Issue by eriklimakc** [unoplatform/Uno.Themes#1128]
## Current behavior

Adding ItemsSource to a ComboBox with Material style cause the app to crash on Windows (WinUI) with this:
> Microsoft.UI.Xaml.Markup.XamlParseException: 'XAML parsing failed.'

```xml
<!--WORKS-->
<!--<ComboBox PlaceholderText="Placeholder" 
		  ItemsSource="{x:Bind MyItems}"/>-->

<!--DOESN'T WORK - BUT SHOULD-->
<ComboBox Style="{StaticResource MaterialComboBoxStyle}" 
		  PlaceholderText="Placeholder" 
		  ItemsSource="{x:Bind MyItems}"/>

<!--DOESN'T WORK - SHOULD?-->
<!--<ComboBox PlaceholderText="Placeholder" 
			  ItemsSource="ABCDEFG"/>-->
```

Repro app and Details -> [CbbRepro.zip](https://github.com/unoplatform/Uno.Themes/files/12233400/CbbRepro.zip)

Affected platform(s): WinUI
Relevant Packages:
- \<PackageReference Include="Uno.WinUI" Version="5.0.0-dev.1734" />
- \<PackageReference Include="Uno.Material.WinUI" Version="3.0.0-dev.319" />

## Anything else we need to know?
Not crashing when using an Uno sample app using Fluent (without Material)

**Comment by Xiaoy312** [comment]
missing library initialization in AppResources.xaml:
```diff
<ResourceDictionary.MergedDictionaries>
	<!-- Load WinUI resources -->
	<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
+	<MaterialTheme xmlns="using:Uno.Material" />

</ResourceDictionary.MergedDictionaries>
```

**Comment by agneszitte** [comment]
@kazo0 / @Xiaoy312 
So after verifying with @eriklimakc after he did a couple of tests, here are the details:
- Yes @eriklimakc forgot to initialize Material in AppResources.xaml for his sample app (in attachment)

- Using `ItemsSource="ABCDEFG"` (for test purposes) is working fine with UWP but not with WinUI
I have opened an issue for it for WinUI:
https://github.com/microsoft/microsoft-ui-xaml/issues/8696

- Using `ItemsSource="{x:Bind MyItems}"` will throw an exception when used in the `Uno.Toolkit sample app` only when it is inside a `<sample:SamplePageLayout...>`, outside of it the exception is gone.
