### ISSUE TITLE
[Windows][Material][ToggleButton] Using MaterialIconToggleButtonStyle without setting AlternateContent causes a crash when toggling

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#1132]
WINDOWS ONLY

When using a ToggleButton with the style: `MaterialIconToggleButtonStyle`, if I do not set the `um:ControlExtensions.AlternateContent`, the app will crash when I attempt to toggle the button by clicking on it.

So the following XAML causes a crash:

```xml
<ToggleButton Style="{StaticResource MaterialIconToggleButtonStyle}">
	<ToggleButton.Content>
		<SymbolIcon Symbol="Accept" />
	</ToggleButton.Content>
</ToggleButton>
```

While the following XAML works fine:

```xml
<ToggleButton Style="{StaticResource MaterialIconToggleButtonStyle}">
	<ToggleButton.Content>
		<SymbolIcon Symbol="Accept" />
	</ToggleButton.Content>
	<um:ControlExtensions.AlternateContent>
		<SymbolIcon Symbol="Delete" />
	</um:ControlExtensions.AlternateContent>
</ToggleButton>
```

## Repro app

[UnoApp5.zip](https://github.com/unoplatform/Uno.Themes/files/12252091/UnoApp5.zip)

**Comment by agneszitte** [comment]
Re-Open for Backport PR

**Comment by trydalch** [comment]
I'm running into a related issue here. 

I don't need to use the alternate content, and would like the Content to not be hidden when I toggle the button. Is there a way to only hide the Content if AlternateContent is set?
