### ISSUE TITLE
Fix Microsoft.UI.Xaml version and adjust PipsPager and ProgressRing styles

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#1142]
We should update the Microsoft.UI.Xaml version to [2.7.1](https://www.nuget.org/packages/Microsoft.UI.Xaml/2.7.1)

[Here](https://github.com/unoplatform/Uno.Themes/blob/017808ccb1c088724bd4e8ddca3e64e2190c5dbd/src/library/Uno.Material/Uno.Material.csproj#L103) and [here](https://github.com/unoplatform/Uno.Themes/blob/017808ccb1c088724bd4e8ddca3e64e2190c5dbd/src/library/Uno.Cupertino/Uno.Cupertino.csproj#L92)

and bump the [samples version](https://github.com/unoplatform/Uno.Themes/blob/017808ccb1c088724bd4e8ddca3e64e2190c5dbd/src/samples/UWP/Uno.Themes.Samples.UWP/Uno.Themes.Samples.UWP.csproj#L16) of MUX to the latest stable version ([2.8.5](https://www.nuget.org/packages/Microsoft.UI.Xaml/2.8.5))

This means that we would **not** support DeterminateSource or IndeterminateSource for Windows as part of ProgressRing and that we could consolidate the ProgressRing styles as well as the PipsPager styles and not longer need to split the .xaml files between UWP and WinUI.

Once the versions are bumped we need to:

- Use ProgressRingWinUI.xaml as the style file for everything (so rename it to ProgressRing.xaml and get rid of the old ProgressRing.xaml) and ensure that any reference to the old names is fixed like [here](https://github.com/unoplatform/Uno.Themes/blob/017808ccb1c088724bd4e8ddca3e64e2190c5dbd/src/library/Uno.Material/Uno.Material.csproj#L194-L197) and [here](https://github.com/unoplatform/Uno.Themes/blob/017808ccb1c088724bd4e8ddca3e64e2190c5dbd/src/library/Uno.Cupertino/Uno.Cupertino.csproj#L140-L142) for the xamlmerge targets 
- PipsPager.xaml should be combined with PipsPager.Base.xaml and then just delete PipsPager.UWP.xaml and remove references to the old files in the xamlmerge targets

**Comment by agneszitte** [comment]
Re-open for backport PRs
