### ISSUE TITLE
Cannot re-initialize MaterialTheme to override colors with a new palette

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#1145]
Attempting to reinitialie MaterialTheme with a different color palette results in the same color palette from App.xaml being used.

Repro sample:
[testcolors.zip](https://github.com/unoplatform/Uno.Themes/files/12322216/testcolors.zip)

**Comment by agneszitte** [comment]
(only working on Windows at the moment but not for the other platforms)

**Comment by kazo0** [comment]
Caused by https://github.com/unoplatform/uno/issues/13724

**Comment by kazo0** [comment]
fixed by https://github.com/unoplatform/uno/pull/13866
