### ISSUE TITLE
 [Gallery-4X][Wasm]FAB- when changing theme FAB buttons are not getting properly refresh.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/Uno.Themes#1149]
### Current behavior

![FAB button issue](https://github.com/unoplatform/uno/assets/74563602/c169c11d-9132-4ff4-a2d1-af2a7b06743e)

### Expected behavior

![FAB button correct](https://github.com/unoplatform/uno/assets/74563602/1feebea5-993f-4ff5-9340-485d6a8bedd5)

### How to reproduce it (as minimally and precisely as possible)

Open Uno Gallery APP .
Click/tap Burger Menu on the left top right.
Click/tap "Floating Action Button" from the "Component" list.
Click on the theme toggle button.
Notice that theme change to dark theme.
Observe that FAB buttons are not getting refreshed with changing theme.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by Marc-Antoine-Soucy** [comment]
I could reproduce it in an old version but in the latest version of mater, it doesnt happen anymore.

**Comment by agneszitte** [comment]
@Marc-Antoine-Soucy #723 is merged and `3.1.0-dev.39` was release. 
Can you please do a sanity check testing the new version on the legacy/4x branch of canary with this package before I close the issue please

**Comment by agneszitte** [comment]
> @Marc-Antoine-Soucy #723 is merged and Uno.Toolkit `3.1.0-dev.39` package was released. Can you please do a sanity check testing the legacy/4x branch with this package before I close the issue, please Thanks in advance

Confirmed with @Marc-Antoine-Soucy that is is fixed with Uno.Toolkit latest `3.1.0-dev.39` package when testing locally Gallery-4X.

@sakshi173 if you can please test this issue with the new canary build for tomorrow.

**Comment by sakshi173** [comment]
@agneszitte, sorry I got confused, I need to retest this defect today or tomorrow?

**Comment by Marc-Antoine-Soucy** [comment]
Tomorrow
