### ISSUE TITLE
Breaking changes in #1028 caused by missing navigationview resources

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/Uno.Themes#1170]
## Current behavior

#1028 removed the `MaterialNavigationViewBackground` key (and probably others) which may be an unwanted breaking change.

## Expected behavior

Apps using older versions of themes should still be compatible with 2.7 builds of uno.themes.

## Environment

Nuget Package: 2.7.0

**Comment by agneszitte** [comment]
fyi @kazo0

**Comment by agneszitte** [comment]
We will need to do a Migration doc for theme/toolkit in order to list the breaking changes regarding lightweight styling work

**Comment by Xiaoy312** [comment]
styles diff log for themes+toolkit: [20230906 migration doc.md](https://github.com/unoplatform/Uno.Themes/files/12553659/20230906.migration.doc.md)
	^ script method: Specialized.ListExposedThemeV2Styles();
	^ script method: Specialized.ListExposedToolkitV2Styles();

inner resources diff log for themes: [diff-log.md](https://github.com/unoplatform/Uno.Themes/files/12553663/diff-log.md)
inner resources diff log for toolkit: // todo
	^ script method: Specialized.DiffThemeV2InnerResources();

relevant script: [20220412 resource parser.linq](https://github.com/Xiaoy312/bag-o-scripts/blob/f37ce08a51bac7130587413618f8fbf2d5bb9994/temp/20220412%20resource%20parser.linq)
