### ISSUE TITLE
[Docs][Lightweight Styling] Fix XAML/Screenshot sample

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#1181]
<img alt="image" src="https://github.com/unoplatform/Uno.Themes/assets/4793020/e1462a9f-dc05-41fd-9005-a5d64f74288d">

The XAML does not fully match with the screenshot of the buttons, we should show the xaml for the Default button as well and have an example of the Overridden button without the pointer over state so we can see all lightweight styling resource overrides at work

**Comment by carlh98** [comment]
@kazo0 where does the screenshot comes from? From the uno.theme sample?

**Comment by kazo0** [comment]
No its just custom xaml from a random app, you can use the sample app to just paste some xaml and grab a screenshot of just the relevant controls

**Comment by carlh98** [comment]
![image](https://github.com/unoplatform/Uno.Themes/assets/7770915/f8177e22-ecbd-4399-940e-d73e17bc07c0)
![image](https://github.com/unoplatform/Uno.Themes/assets/7770915/5b6f66c5-b749-4428-8b25-b102194e365e)

this?

**Comment by kazo0** [comment]
Yes but try and get it with the pointer visible over the red button, to show that you are hovering over it, or fake it with a picture of a pointer :)

**Comment by carlh98** [comment]
![image](https://github.com/unoplatform/Uno.Themes/assets/7770915/92c452eb-45bc-4b96-afc7-4f3945a2781a)

**Comment by carlh98** [comment]
Updated image

**Comment by kazo0** [comment]
@carlh98 

1. Let's split the xaml into three separate Buttons, one Default, one Overridden like the Green one, and then a separate one that has the PointerOver resources overridden
3. You can just provide the code block of the XAML here instead of a screenshot, that way I can copy paste it into the docs and the release blog post

**Comment by Arieldelossantos** [comment]
we can create the PR with those changes instead :p

**Comment by Arieldelossantos** [comment]
created PR @kazo0

**Comment by kazo0** [comment]
Something like this:

```xml
<StackPanel>
	<Button Content="Default Button Style"
			Style="{StaticResource FilledButtonStyle}" />

	<Button Content="Overridden Button Style"
			Style="{StaticResource FilledButtonStyle}">
		<Button.Resources>
			<SolidColorBrush x:Key="FilledButtonForeground" Color="DarkGreen" />
			<SolidColorBrush x:Key="FilledButtonBackground" Color="LightGreen" />
			<SolidColorBrush x:Key="FilledButtonBorderBrush" Color="DarkGreen" />
		</Button.Resources>
	</Button>

	<Button Content="Overridden Button Style (PointerOver)"
			Style="{StaticResource FilledButtonStyle}">
		<Button.Resources>
			<Thickness x:Key="ButtonBorderThickness">2</Thickness>
			<SolidColorBrush x:Key="FilledButtonForegroundPointerOver" Color="DarkRed" />
			<SolidColorBrush x:Key="FilledButtonBackgroundPointerOver" Color="LightPink" />
			<SolidColorBrush x:Key="FilledButtonBorderBrushPointerOver" Color="DarkRed" />
		</Button.Resources>
	</Button>
</StackPanel>
```

**Comment by Arieldelossantos** [comment]
done @kazo0
