### ISSUE TITLE
[Gallery][iOS] Material checkbox does not show checked state

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/Uno.Themes#1184]
### Current behavior

When clicking on this checkbox:
![image](https://github.com/unoplatform/uno/assets/5839577/fb74092e-f560-48b3-8015-40f08ae94be2)

The checked state is never appearing. This does not repro with the fluent style.

Happens on both 4x and 5x canaries. Not tested on Android.

**Comment by jeromelaban** [comment]
@sakshi173 could you re-validate this issue please?

**Comment by agneszitte** [comment]
@sakshi173 to be tested on 2023-08-31 please

**Comment by agneszitte** [comment]
Thanks a lot, @sakshi173 for the verification, really appreciated.
Closing the issue
