### ISSUE TITLE
Add more lightweight styling keys to PasswordBox.

### ISSUE THREAD

**Issue by ADD-David-Antolin** [unoplatform/Uno.Themes#1204]
## What would you like to be added:

I have noticed that in PasswordBox styles there are some values that are still hardcoded instead of be in keys. For example it is missing:

MaterialOutlinedPasswordBoxCornerRadius
MaterialOutlinedPasswordBoxBorderPadding
MaterialOutlinedPasswordBoxBorderThickness
MaterialOutlinedPasswordBoxBorderThicknessPointerOver (this does not change on TextBox on that VisualState so I do not know if it the setter should be removed).
MaterialOutlinedPasswordBoxBorderThicknessFocused
MaterialOutlinedPasswordBoxMinHeight
MaterialOutlinedPasswordBoxPadding.

And the equivalent ones on Filled PasswordBox.

## Why is this needed:

To achieve styling parity between TextBox and PasswordBox.

## For which Platform:

- [X] UWP
- [X] iOS
- [X] Android
- [X] WebAssembly
- [X] macOS

**Comment by agneszitte** [comment]
@Arieldelossantos the current documentation with the resource keys will need to be also updated here please
https://github.com/unoplatform/Uno.Themes/blob/master/doc/styles/PasswordBox.md

**Comment by Arieldelossantos** [comment]
doc updated @agneszitte
