### ISSUE TITLE
[Docs][Material] Highlight brush changes when migrating from Material v1 (Material Design 2) to v2 (Material Design 3)

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#1212]
Add a NOTE/WARN to the [Color Update section of the v1 Material migration guide](https://platform.uno/docs/articles/external/uno.themes/doc/material-migration.html#color-update) to notify that the Brush resources are now placed in ThemeDictionaries and should be referenced using the `ThemeResource` binding

**Comment by kazo0** [comment]
related: https://github.com/unoplatform/Uno.Themes/issues/1157

**Comment by Darsh0307** [comment]
Hello @kazo0 i am not sure which one to do 1157 or 1212
