### ISSUE TITLE
[Material][Button] FilledTonalButtonStyle Leading icon incorrect fill color for Enabled state

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#1218]
Expected:
![image](https://github.com/unoplatform/Uno.Themes/assets/4793020/d4409ad5-9776-4d22-94c0-46f81eaa3bc4)

Actual:
![image](https://github.com/unoplatform/Uno.Themes/assets/4793020/b1bd9b88-1514-4440-af22-7d6efc404e86)

**Comment by iurycarlos** [comment]
Not so sure if it is related, but it is similar:

https://github.com/unoplatform/Uno.Figma/issues/1848

**Comment by kazo0** [comment]
@iurycarlos that one is related to https://github.com/unoplatform/Uno.Themes/issues/1220 which should now be fixed by https://github.com/unoplatform/Uno.Themes/pull/1231 which is now merged and is part of the `4.0.0-dev.167` package :)

**Comment by iurycarlos** [comment]
Thanks!
