### ISSUE TITLE
NavigationView colors different from FigmaFile

### ISSUE THREAD

**Issue by iurycarlos** [unoplatform/Uno.Themes#1219]
## Current behavior

Background Pane color is different between Themes and Figma File

![image](https://github.com/unoplatform/Uno.Themes/assets/6876973/9bd20992-841a-4efe-8783-8e3040f1b34a)

## Expected behavior

We need to have the same colors on both sides

## How to reproduce it (as minimally and precisely as possible)

Just use the latest version of the QA Figma File and process a screen with a Nav View.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] UWP
- [ ] MacOS

**Comment by agneszitte** [comment]
FYI @kazo0

**Comment by kazo0** [comment]
@iurycarlos I believe the Pane background needs to be set by overriding certain lightweight styling resources. 

https://learn.microsoft.com/en-us/windows/apps/design/controls/navigationview#pane-backgrounds

cc @carldebilly / @agneszitte

**Comment by iurycarlos** [comment]
Latest version of Figma File was changed, now they are equal:

![image](https://github.com/unoplatform/Uno.Themes/assets/6876973/789f8b1c-2919-47ad-b1f7-d3e7fbee67d5)

**Comment by Marc-Antoine-Soucy** [comment]
@iurycarlos  One thing I'm not sure about is, in the non collapsed version, the label is shown as "item label" and in the collapsed version, it's "label", should we just cutoff the words like that and leave enough space for a certain number of letters, or are we supposed to have separate name for the collapsed and the non-collapse version?

**Comment by iurycarlos** [comment]
@NVLudwig, i think you are the one to answer that :)
