### ISSUE TITLE
ToggleSwitch has a strange MinWidth 

### ISSUE THREAD

**Issue by iurycarlos** [unoplatform/Uno.Themes#1225]
## Current behavior

Using a toggle switch inside an Autolayout with SpaceBetween uncovered that ToggleSwitch has a MinWidth set and it is causing alignment issues:

https://playground.platform.uno/#b80b413a

## Expected behavior

The link above has a forced expected result using a MinWidth and the second result is the original and wrong one.

## How to reproduce it (as minimally and precisely as possible)

Just use the provided link.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] UWP
- [ ] MacOS

**Comment by iurycarlos** [comment]
![image](https://github.com/unoplatform/Uno.Themes/assets/6876973/f0b94a22-a760-43ae-8f02-44efebcbdb01)

**Comment by eriklimakc** [comment]
This is actually an Uno issue and also affects the Fluent ToggleSwitch. The `MinWidth="154"` is defined in:

 - [Uno.UI/UI/Xaml/Style/Generic/SystemResources.xaml#L3972](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Style/Generic/SystemResources.xaml#L3972)

 - [Uno.UI.FluentTheme.v1/themeresources_v1.xaml#L19731](https://github.com/unoplatform/uno/blob/master/src/Uno.UI.FluentTheme.v1/themeresources_v1.xaml#L19731)

 - [Uno.UI.FluentTheme.v2/themeresources_v2.xaml#L23315](https://github.com/unoplatform/uno/blob/master/src/Uno.UI.FluentTheme.v2/themeresources_v2.xaml#L23315)
 
Repro in Playground: http://playground.platform.uno/#ccfdf8c8

Would the fix be removing the `MinWidth` from Uno? On WinUI/UWP we don't have the MinWidth issue.

![image](https://github.com/unoplatform/Uno.Themes/assets/114886335/3df5770c-2f98-47a5-ac8b-b1d6a872faf4)

@iurycarlos @jeromelaban @kazo0

**Comment by iurycarlos** [comment]
IMO that will solve the case. 
I can't see how a minWidth could be mandatory situations like that.

**Comment by iurycarlos** [comment]
On windows, it shows a label (on / off) and it is affected by localization. Here i receive Ligado / Desligado. 
Probably it is related to that label.

**Comment by eriklimakc** [comment]
Hmm, it does affect Windows. But only for Fluent styles:

![image](https://github.com/unoplatform/Uno.Themes/assets/114886335/0ee0fc02-b086-49b8-b37a-a0b31693dfc4)

```
<StackPanel>
	<TextBlock Text="Fluent" />
	<StackPanel Orientation="Vertical" Spacing="10" Margin="10">
		<ToggleSwitch IsOn="True" MinWidth="53" Background="Red" />
		<ToggleSwitch IsOn="True" Background="Red" />
		<ToggleSwitch IsOn="True" Background="Red" MinWidth="154" />
	</StackPanel>

	<TextBlock Text="Material" />
	<StackPanel Orientation="Vertical" Spacing="10" Margin="10">
		<StackPanel.Resources>
			<MaterialTheme xmlns="using:Uno.Material" />
		</StackPanel.Resources>
		<ToggleSwitch IsOn="True" MinWidth="53" Background="Red" />
		<ToggleSwitch IsOn="True" Background="Red" />
		<ToggleSwitch IsOn="True" Background="Red" MinWidth="154" />
	</StackPanel>
</StackPanel>
```

@xiao @iurycarlos

**Comment by eriklimakc** [comment]
Between Skia.GTK and UWP the only **constraint** that is different is the first one which is:

- Skia.Gtk: `Constraints=[154,NaN,∞]x[0,NaN,∞]`
 
- UWP: `Constraints=[0,NaN,∞]x[0,NaN,∞]`

Apart from that other values for **Actual** also varies between GTK and UWP.

You can see the whole TreeGraph comparassion here https://www.diffchecker.com/x1dQjV3U/. Skia is first UWP is second.

@Xiaoy312 @iurycarlos

**Comment by eriklimakc** [comment]
Can/Should we workaround this with a `<Setter Property="MinWidth" Value="56" />` in the Material ToggleSwitch style to unblock the Figma Plugin?

![image](https://github.com/unoplatform/Uno.Themes/assets/114886335/f210e998-70d6-4300-ada8-d18889cb9828)

cc @Xiaoy312 @kazo0 @iurycarlos

**Comment by iurycarlos** [comment]
IMHO, I think we should override the native minWidth to force the control follow Material / Cupertino behaviors. 
And we should let Fluent (for all platforms) exactly as native (windows) works. 

All design systems will be fine.

**Comment by eriklimakc** [comment]
It also affects Cupertino:

![image](https://github.com/unoplatform/Uno.Themes/assets/114886335/234a28ff-cf01-4050-bac8-1400240f4466)

**Comment by kazo0** [comment]
We can set `ToggleSwitchThemeMinWidth` to whatever value we want in our theme dictionary inside of ToggleSwitch.xaml, right? So if we were to set that to 0, would we avoid this?

@eriklimakc
