### ISSUE TITLE
Issue with shadows using ElevatedView

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#1229]
Since this week a new hard shadow has appeared in the example app and I have no idea why. The plugin itself is also plagued with this new hard shadow

<img width="988" alt="image" src="https://github.com/unoplatform/Uno.Figma/assets/29584087/aeb1a538-5faf-43fa-ad17-09a557f4ea48">

Plugin hard shadows
<img width="438" alt="image" src="https://github.com/unoplatform/Uno.Figma/assets/29584087/4dbda358-b26f-4c14-8028-93a0a6dba102">

_Originally posted by @NVLudwig in https://github.com/unoplatform/Uno.Figma/issues/1009#issuecomment-1747041915_

**Comment by agneszitte** [comment]
(Issue visible on Gallery canary on WASM, other platforms will need to be tested as well to see if it is a WASM only issue)

**Comment by kazo0** [comment]
@Youssef1313 has this been fixed?

**Comment by Youssef1313** [comment]
It should be. It would be good if someone can confirm first before we close.

**Comment by agneszitte** [comment]
Related PR : https://github.com/unoplatform/uno/pull/13919
