### ISSUE TITLE
Weird Elevated Colors when changing theme

### ISSUE THREAD

**Issue by iurycarlos** [unoplatform/Uno.Themes#1248]
## Current behavior

When parsing a light layout using plugin set to Dark color (and vice versa), it will generate weird color results:

![image](https://github.com/unoplatform/Uno.Figma/assets/6876973/e0300284-e449-4efd-be96-cf702d4a1647)

## Expected behavior

It should follow the known colors.

## How to reproduce it (as minimally and precisely as possible)

Just try to parse an elevated button, for example and then try to change the plugins theme.

## Environment

Related to figma issue [1475](https://github.com/unoplatform/Uno.Figma/issues/1475)

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] UWP
- [ ] MacOS

**Comment by kazo0** [comment]
For whoever picks this up, we should just be removing the SurfaceTint Extensions altogether and remove its usage.

**Comment by iurycarlos** [comment]
Let me try that one
