### ISSUE TITLE
Include word is used Two times. 

### ISSUE THREAD

**Issue by Darsh0307** [unoplatform/Uno.Themes#1274]
## On which page?

https://platform.uno/docs/articles/external/uno.themes/doc/themes-overview.html

![Screenshot 2023-11-06 at 10 46 42 AM](https://github.com/unoplatform/Uno.Themes/assets/90713481/81b39793-61cf-4cfd-bcda-8d6fab67aa2d)

## What's wrong?

The "Include" word is used Twice

## Any feedback?

I think that changing the line to "Both libraries help you style your application with just a few lines of code, **including**:" will make more sense

**Comment by sfazli96** [comment]
Hi! I might be able to find where the double word is coming from and delete it. I can take a look. I am a first-timer contributor still learning.

**Comment by agneszitte** [comment]
> Hi! I might be able to find where the double word is coming from and delete it. I can take a look. I am a first-timer contributor still learning.

Hi @sfazli96, we will happily accept your contribution to this issue. Here is our [Contribution Guide](https://github.com/unoplatform/uno/blob/master/CONTRIBUTING.md#contributing-code-and-content) for all the details.
As it is detailed in it, your commit **must** be in the [Conventional Commits format](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/git-conventional-commits.md) please.

Here is the updated sentence that we should have in this case instead:
`Both libraries help you style your application with a few lines of code, including:`

And here is the current related code:
https://github.com/unoplatform/Uno.Themes/blob/52d545d39ed086c10151fd80c95518a776171abb/doc/themes-overview.md?plain=1#L21

Please let us know if you have any additional questions or blockers and we will be happy to help you!

**Comment by sfazli96** [comment]
Ok I made a pull request and fixed the wording.

**Comment by agneszitte** [comment]
> your commit **must** be in the [Conventional Commits format](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/git-conventional-commits.md) please.

Thank you a lot for your PR, it is really appreciated!
I left you a comment https://github.com/unoplatform/Uno.Themes/pull/1279#issuecomment-1802713245

**Comment by sfazli96** [comment]
yeah I saw the comment and updated the title.

**Comment by morning4coffe-dev** [comment]
CC @agneszitte, @Darsh0307 Closing this issue as it was fixed by https://github.com/unoplatform/Uno.Themes/pull/1308
