### ISSUE TITLE
[WPF] ListView Multiple mode display issue

### ISSUE THREAD

**Issue by lld1995** [unoplatform/Uno.Themes#1291]
### Current behavior

I test ListView on Uno.WinUI(5.0.48) on WPF
`<ListView x:Name="lv"  SelectionMode="Multiple" IsMultiSelectCheckBoxEnabled="True" VerticalAlignment="Top"></ListView>`

When i select item,the left checkbox not display checked

### Works on UWP/WinUI

None

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

**Comment by eriklimakc** [comment]
I can reproduce it on Themes sample app (Skia.GTK, WASM, and Android).

**Comment by Darsh0307** [comment]
same here , i am also not getting the tick symbol 
<img width="1077" alt="Screenshot 2023-12-04 at 11 52 46 AM" src="https://github.com/unoplatform/Uno.Themes/assets/90713481/d057e5ce-6735-45d9-836c-14cbb4efbfff">
