### ISSUE TITLE
[Material] Button visual does not update when the button itself changes IsEnable to disable

### ISSUE THREAD

**Issue by rafael-rosa-knowcode** [unoplatform/Uno.Themes#1293]
## What would you like to be added:

When the button itself updates its IsEnable to false, the button's appearance is not as it should be.
What happens correctly in case IsEnable is modified without using the button's own event.

Watch the video below for better understanding.

https://github.com/unoplatform/Uno.Themes/assets/116665025/b246661d-3953-4f92-aa60-690d2465864e

## Why is this needed:

In Uno Studio we need the button that changes navigation pages to be disabled when you reach the last one.

## For which Platform:

- [ ] UWP
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] macOS

## Anything else we need to know?

To solve this case in Uno Studio, I duplicated the MaterialFilledTonalButtonStyle and removed this line
https://github.com/unoplatform/Uno.Themes/blob/ef221bd881c94339051b75023d0a693595d6ede4/src/library/Uno.Material/Styles/Controls/v2/Button.xaml#L768C6-L768C6
```
The <VisualState x:Name="Unfocused" />
````

**Comment by rafael-rosa-knowcode** [comment]
Repro.

[ButtonUnoThemeDisableEvent.zip](https://github.com/unoplatform/Uno.Themes/files/13528127/ButtonUnoThemeDisableEvent.zip)

**Comment by nickrandolph** [comment]
The issue would appear that the FocusStates and CommonStates modify the same properties - this is bad practice as it will result in unknown states. For example in this case the button is Disabled, so should be in Disabled state but it's also in Focussed state - both modify Root.Background, which will cause an issue.
cc @kazo0 @NVLudwig this is an issue that will need to be resolved across all controls to make sure we don't see this issue across any of the Material controls

**Comment by NVLudwig** [comment]
That's a good catch. Why can you focus a disabled control?

**Comment by limeniye** [comment]
https://github.com/unoplatform/uno/issues/14633
