### ISSUE TITLE
MaterialFlyoutPresenterStyle shouldn't set Min/Max Height/Width to NaN

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/Uno.Themes#1336]
## Current behavior

MaterialFlyoutPresenterStyle style for FlyoutPresenter throws and excpetion when attempting to show a flyout that uses this style. The exception complains because MinWidth, MaxWidth, MinHeight and MaxHeight need to be not-null values that are **not** NaN or negative.

## Expected behavior

MaterialFlyoutPresenterStyle should be able to be used

## How to reproduce it (as minimally and precisely as possible)

Create a flyout that uses the MaterialFlyoutPresenterStyle style for the presenter
Run on WASM and attempt to launch flyout

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] UWP
- [ ] MacOS

**Comment by kazo0** [comment]
Should require the same fix as https://github.com/unoplatform/uno.toolkit.ui/pull/1010
