### ISSUE TITLE
Dsp Documentation lacking information on how to clearly use the Dsp Tasks

### ISSUE THREAD

**Issue by dansiegel** [unoplatform/Uno.Themes#1382]
## On which page?

https://platform.uno/docs/articles/external/uno.themes/doc/material-dsp.html

## What's wrong?

The `UnoDspImportColors` item is not properly documented. It's important that we document any and all attributes on custom items like the `UnoDspImportColors`.

## Any feedback?

```xml
<UnoDspImportColors Include="Styles\*.zip" Generator="Xaml" />
<UnoDspImportColors Include="Styles\*.zip" Generator="CSharp" />
```

Be sure to note that the Uno.Sdk (starting with 5.2) will automatically include this for you assuming have the UnoFeature `CSharpMarkup` it will use the `CSharp` Generator while it will use the `Xaml` Generator by default.

**Comment by agneszitte** [comment]
cc @carldebilly, @iurycarlos to support @kazo0
