### ISSUE TITLE
Cards

### ISSUE THREAD

**Issue by MatFillion** [unoplatform/Uno.Themes#14]
https://app.zeplin.io/project/5e344ca7405a53a6ef303bc1/screen/5e4b29380cb31fa82743d819

Let's not include swipe actions for V1. Just plain cards

**Comment by MatFillion** [comment]
@agneszitte-nventive I updated description

**Comment by MatFillion** [comment]
@agneszitte-nventive let's add a sample of a card in a list, just to showcase it and see how it plays out with pressed states along with the ListViewItem. I'm afraid we might need to make a custom ListViewItem style?

Also for the expand section, we can keep it for a v2, we need to have it animate.

**Comment by MatFillion** [comment]
ElevatedView should be in our v1, it's working. Except for issue #50

**Comment by agneszitte-nventive** [comment]
@MatFillion 
- Ok I will next work on card in a list in the next PR.
- For the expander I already add the animation part in the Card control (or maybe I did not understand your sentence)
 - For ElevatedView nothing was showing up when I tried the other day, but I will work on that also and understand why it was not showing up correctly.
