### ISSUE TITLE
Combobox formatting not correct in Outline mode.

### ISSUE THREAD

**Issue by MarkLFT** [unoplatform/Uno.Themes#1404]
## Current behavior

The format of the combobox when using the outline mode is not consistent with the text boxes.  The height is different, smaller, and this causes the label and the selected value to overlap.

## Expected behavior

The size and layout should be identical to the Textbox.

## How to reproduce it (as minimally and precisely as possible)

Create  a project using Material Design
Add a Combobox to a page,
Select Outline style.
The selected value overlaps the label.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] UWP
- [ ] MacOS

## Anything else we need to know?

![Combobox Layout](https://github.com/unoplatform/Uno.Themes/assets/5136699/c4ff9e3b-297e-40bf-aa70-0c1b0004bf07)

**Comment by kazo0** [comment]
Hi @MarkLFT,

Thanks for the report!

We are testing on our side and so far unable to repro that overlapping of the labels:

![image](https://github.com/unoplatform/Uno.Themes/assets/4793020/6d859c05-bf7f-4eb0-bba6-57594ae2670a)

Would you be able to provide the XAML or a .zip of a repro project that we can take a look at?

**Comment by MarkLFT** [comment]
There is a copy of the project at https://github.com/MarkLFT/RMUtility.Problems

**Comment by Kunal22shah** [comment]
Hello @MarkLFT ,

The issue seems to be with the `.Style(Theme.ComboBox.Styles.Default)` line. You can go ahead and **_remove it_** from the ComboBox styling to avoid the overlap. It seems to be C# markup specific issue and the team will look into it further, but it should not change anything on your side since the outlined combobox style is the default style for the combobox when you are using Material anyway.

**Comment by agneszitte** [comment]
> Hello @MarkLFT ,
> 
> The issue seems to be with the `.Style(Theme.ComboBox.Styles.Default)` line. You can go ahead and **_remove it_** from the ComboBox styling to avoid the overlap. It seems to be C# markup specific issue and the team will look into it further, but it should not change anything on your side since the outlined combobox style is the default style for the combobox when you are using Material anyway.

Probably related to https://github.com/unoplatform/uno.csharpmarkup/issues/722 for the C# markup-specific issue from @dansiegel and @kazo0 discussion.

**Comment by agneszitte** [comment]
> Probably related to [unoplatform/uno.csharpmarkup#722](https://github.com/unoplatform/uno.csharpmarkup/issues/722) for the C# markup-specific issue from @dansiegel and @kazo0 discussion.

@Kunal22shah now that https://github.com/unoplatform/uno.csharpmarkup/issues/722 is closed, can you check now if this is properly fixed please

**Comment by Kunal22shah** [comment]
> > Probably related to [unoplatform/uno.csharpmarkup#722](https://github.com/unoplatform/uno.csharpmarkup/issues/722) for the C# markup-specific issue from @dansiegel and @kazo0 discussion.
> 
> @Kunal22shah now that [unoplatform/uno.csharpmarkup#722](https://github.com/unoplatform/uno.csharpmarkup/issues/722) is closed, can you check if this is properly fixed please

@agneszitte just checked it fixed now!

**Comment by agneszitte** [comment]
Thank you for the confirmation @Kunal22shah. I am closing this issue then. 
Can be re-open with more details if needed.
