### ISSUE TITLE
Error on OnSurfaceLowBrush.

### ISSUE THREAD

**Issue by ADD-Eugenio-Lopez** [unoplatform/Uno.Themes#1422]
Making the change to the latest version of the Uno libraries we have seen that the color of some controls has changed. Investigating we have detected that there is an error in the OnSurfaceLowBrush, the opacity that is being used to create it is DisabledOpacity when it should be LowOpacity.

## Current behavior

OnSurfaceLowBrush use DisabledOpacity.

## Expected behavior

OnSurfaceLowBrush use LowOpacity.

## How to reproduce it (as minimally and precisely as possible)

See the line 279 at file https://github.com/unoplatform/Uno.Themes/blob/master/src/library/Uno.Themes/Styles/Applications/Common/SharedColors.xaml

## Environment

Nuget Package:
Uno.Themes.WinUI

Package Version(s):
5.0.13

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [X] UWP
- [ ] MacOS

**Comment by Xiaoy312** [comment]
regression from #1002
relevant discussion: https://github.com/unoplatform/Uno.Themes/pull/1002/files/50de5e1a32444bf40d3810a86543592518e68dbc#r1213858128

@kazo0
