### ISSUE TITLE
The fab button text is missing left spacing

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/Uno.Themes#1430]
> @jeromelaban indeed the canary link does not have this bug.
> 
> 
> 
> I noticed 2 sperate issues while looking into the one above:
> 
> 
> 
> 1. FAB seems ro have a problem in the canary (Safari and Chrome) that is not present in prod. Should I make a new issue? It's the icon that has no spacing with the label in canary only.
> 
> <img width="414" alt="Screenshot 2024-05-28 at 10 05 32 AM" src="https://github.com/unoplatform/Uno.Gallery/assets/29584087/9359957b-6e88-420c-bacf-a64752d80c5e">
> 
> 

 _Originally posted by @NVLudwig in [#985](https://github.com/unoplatform/Uno.Gallery/issues/985#issuecomment-2135321725)_

**Comment by Xiaoy312** [comment]
![image](https://github.com/unoplatform/Uno.Themes/assets/2359550/f1f72288-37b6-4de8-acfe-bb249034c096)
i cant seem to repro on windows with chrome:
- https://unogallerycanary.z27.web.core.windows.net/
- navigate to: Toolkit\ShadowContainer
- scroll down to: Neumorphism Styles
- select from dropdown: FAB

**Comment by NVLudwig** [comment]
Alos working on Safari now:
<img width="377" alt="image" src="https://github.com/unoplatform/Uno.Themes/assets/29584087/a4066077-e0e6-4c75-9fe7-bce6d14e066d">
