### ISSUE TITLE
[Gallery][UI Components][TextBox] Texts are not align with the Icon

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/Uno.Themes#1443]
## Current behavior
Star Icon and text are not align. Text seems upwards than the icon.
![Screenshot 2024-07-15 at 10 30 05 AM](https://github.com/user-attachments/assets/3bbfecce-3e35-49bf-a547-37e8e4c98dee)

## Expected behavior
Text should be align with Icon

## How to reproduce it (as minimally and precisely as possible)

1. Open Gallery Canary
2. Navigate to Menu -> UI Components -> TextBox
3. Observe the TextBox with Icon

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [Y] iOS
- [Y] Android
- [Y] WebAssembly
- [ ] UWP
- [ ] MacOS

**Comment by Kunal22shah** [comment]
Despite trying various padding, margin, and alignment adjustments, the issue persists.
Changes Attempted: Padding Adjustments, Ensured VerticalAlignment was set to Center for the IconPresenter, ScrollViewer, HeaderElement, and PlaceholderElement within the ControlTemplate.

It was suggested by Steve that the issue might be related to the actual font being used.

**Comment by Xiaoy312** [comment]
you can also try some of the ideas suggested here: unoplatform/Uno.Themes#832 and the linked pr

**Comment by agneszitte** [comment]
> you can also try some of the ideas suggested here: #832 and the linked pr

@Kunal22shah you already tried what @Xiaoy312 suggested please?

**Comment by Kunal22shah** [comment]
> > you can also try some of the ideas suggested here: #832 and the linked pr
> 
> @Kunal22shah you already tried what @Xiaoy312 suggested please?

@agneszitte Yes, i already tried the line height approach from that PR but the issue still persists.

**Comment by agneszitte** [comment]
> > > you can also try some of the ideas suggested here: #832 and the linked pr
> > 
> > 
> > @Kunal22shah you already tried what @Xiaoy312 suggested please?
> 
> @agneszitte Yes, i already tried the line height approach from that PR but the issue still persists.

@Xiaoy312 /@kazo0 / @MartinZikmund  do you have additional feedback/suggestions for this issue please?

**Comment by kazo0** [comment]
Is it maybe just the icon itself that have maybe some spacing included or something? What if we gave each of the layers a different background color so we can see the bounds of everything more clearly to see what exactly is off center
