### ISSUE TITLE
ComboBox header is not visible with Material theme

### ISSUE THREAD

**Issue by DCorrBECare** [unoplatform/Uno.Themes#1450]
### Current behavior

The header of the ComboBox is not visible while using the Material theme.

### Expected behavior

The header of the ComboBox should be visible

### How to reproduce it (as minimally and precisely as possible)

Add a ComboBox with some header.
[UnoAppComboBox.zip](https://github.com/user-attachments/files/16414219/UnoAppComboBox.zip)

### Workaround

Use the Fluent design theme

### Works on UWP/WinUI

No

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.Sdk: 5.3.90

### Affected platforms

WebAssembly, Windows (WinAppSDK)

### IDE

Visual Studio 2022

**Comment by kazo0** [comment]
I believe this is by design:

![image](https://github.com/user-attachments/assets/190e7f2b-ae7e-4229-a75f-f2ec3b72d06c)

From the Material Uno Figma design file: https://www.figma.com/community/file/1110792522046146058

@NVLudwig is there any guidance for headers on top of comboboxes?

**Comment by NVLudwig** [comment]
So in Material there is no native ComboBox the guidance is to use Menues+other controls which results in a DropDown:
"Menus display a list of choices on a temporary surface. They appear when users interact with a button, action, or other control. "

Here is the [guidance](https://m3.material.io/components/menus/overview#b39b2819-a579-4de1-bca2-8d7dbd3b332c)

Like this:
<img width="582" alt="image" src="https://github.com/user-attachments/assets/60c25ae6-e702-4d7b-bf28-399f2f4856fe">


This way the Header is always visible.

**Comment by kazo0** [comment]
Oh sorry I think I misunderstood the issue. Currently there is no header/placeholder that will display as the small text header like we have in TextBox:

![image](https://github.com/user-attachments/assets/9eb49e0a-256b-4668-bb1b-d23c15b3c991)

@DCorrBECare currently the header in the ComboBox is driven by the `PlaceholderText` property. So if I were to set `PlaceholderText="Hello"` on the `ComboBox`, you will have the header displayed when a value is set:

![image](https://github.com/user-attachments/assets/27d9e8aa-11ae-41b3-adce-b73f0478e43c)

Is this what you are trying to accomplish?

@eriklimakc fyi we should align this with the TextBox and have support for the Header and PlaceholderText together as well

**Comment by DCorrBECare** [comment]
@kazo0 Yes that's what I have been trying to accomplish, I thought the Header property was the right one.

The PlaceHolderText works fine as the header of the ComboBox.
