### ISSUE TITLE
[Gallery][WASM][UI Components -TextBox] In outline the disabled TextBox is not disabled

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/Uno.Themes#1457]
## Current behavior
in Outlined the Disabled texbox allows user to enter text.

https://github.com/user-attachments/assets/7f416c2f-1729-4e94-b00c-56dcede7fd6a

## Expected behavior
The Disabled textBox should not allow user to enter text.

## How to reproduce it (as minimally and precisely as possible)

1. Open Gallery Canary (https://unogallerycanary.z27.web.core.windows.net/)
2. From side Menu expand UI components
3. From UI components, Click on Textbox
4. Scroll down to **Outline**
5. Observe the 'Disabled' textbox.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] UWP
- [ ] MacOS

**Comment by agneszitte** [comment]
@jhanvi03 if you can recheck this issue tomorrow with the next canary build please

**Comment by jhanvi03** [comment]
QA Pass: Tested Disabled TextBox in outline is Disabled now.
![image](https://github.com/user-attachments/assets/d985365f-f864-4d23-ba56-40b21bdde772)
