### ISSUE TITLE
[Gallery][MacOS/iOS][UI Components-TextBox] Overlapping texts for disabled textbox

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/Uno.Themes#1460]
## Current behavior

for the disabled 'Header' and 'Placeholder' texbox the placeholder text seems to be overlapping in both **Default** and **Outline**
MacOS:
![Screenshot 2024-08-21 at 2 39 17 PM](https://github.com/user-attachments/assets/7fe7865d-9735-45a9-9b61-12f6bd0427d5)
![Screenshot 2024-08-21 at 2 38 38 PM](https://github.com/user-attachments/assets/7da83e5e-4ae4-4286-ae92-7c790077afea)

iOS:
![IMG_2461](https://github.com/user-attachments/assets/80255fc5-30f9-4dea-843d-fd4c634bd1ac)

## Expected behavior
Text should not overlap and clearly visible.

## How to reproduce it (as minimally and precisely as possible)

1. Download and Install Gallery canary from TestFlight
2. From the side Menu expand UI components
3. From UI components click on TextBox
4. Observe the Disabled 'Header' and 'placeholer' textbox present in both 'Default' and 'Outline'

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] UWP
- [x] MacOS

**Comment by agneszitte** [comment]
@jhanvi03 if you can recheck this issue tomorrow with the next canary build please

**Comment by jhanvi03** [comment]
QA Pass: Tested on Mac and iOS Texts are not overlapping. 
![IMG_2462](https://github.com/user-attachments/assets/6f8cc50d-20f7-4a68-8e63-2a34689d9a91)
![IMG_2464](https://github.com/user-attachments/assets/818b606e-b41c-406b-b44e-4d8073f9c102)
