### ISSUE TITLE
[Material][TextBox] Make all property values on Setters from VisualStates accessible via ThemeResources

### ISSUE THREAD

**Issue by ADD-Noureddine-Maachi** [unoplatform/Uno.Themes#1469]
## What would you like to be added:

ThemeResources for property values that are currently set directly to Setters in VisualStates. 

https://github.com/unoplatform/Uno.Themes/blob/569a9c0c6e5b3a2295702c85c9b2cd59e2758572/src/library/Uno.Material/Styles/Controls/v2/TextBox.xaml#L679-L688

As you can see, the properties `RootBorder.BorderThickness` and `RootBorder.Padding` have no ThemeResources like the other Setters.

## Why is this needed:

It would be very useful since this way you can easily customize the style referring to the key of the `ThemeResource`. It would not be convenient to modify the setters in any other way.

## Anything else we need to know?

I am having this problem with the Style `MaterialOutlinedTextBoxStyle`.

**Comment by ADD-Noureddine-Maachi** [comment]
Besides that, we have found that the behavior of the `MinHeight` property is not working correctly. 

A default Material `TextBox` with the Style `MaterialOutlinedTextBoxStyle` has the following values:


![Image](https://github.com/user-attachments/assets/6c877bf0-1d88-4469-a95f-fd57e788abd2)

We understand that the `ActualHeight` should also be **56**.

Thanks in advance.

**Comment by kazo0** [comment]
FYI @agneszitte as I know we had worked on fiddling with these numbers previously

**Comment by Kunal22shah** [comment]
@kazo0 For the `ThemeResource` property setters, what should we do for the properties that are not specifically used at the moment but available for the control?
cc: @agneszitte

**Comment by agneszitte** [comment]
> @kazo0 For the `ThemeResource` property setters, what should we do for the properties that are not specifically used at the moment but available for the control? cc: @agneszitte

Talking about the principal main setters @kazo0 to be clearer (cf. [here](https://github.com/microsoft/microsoft-ui-xaml/blob/d74a0332cf0d5e58f12eddce1070fa7a79b4c2db/src/controls/dev/CommonStyles/TextBox_themeresources.xaml#L180) as an example)

**Comment by agneszitte** [comment]
Hi @ADD-Noureddine-Maachi 

The fixes are now available with the latest dev build of Uno Themes, but they haven’t yet been released in a stable version of `uno.sdk`. We’ll need to conduct additional QA to ensure these changes don’t introduce any regressions.

In the meantime, you can test the changes by overriding the Uno Themes version specifically (alongside the current `uno.sdk` version you're using). To do so, add the following to your `Directory.Build.props` file:

```
<PropertyGroup>
    <UnoThemesVersion>5.4.0-dev.18</UnoThemesVersion>
</PropertyGroup>
```
>[!WARNING]
> Please remember to remove this override when it’s no longer necessary, once the fixes are included in a stable release of uno.sdk.

**Here are the details of the related changes to the Resource Keys with the latest updates:
[Material Migration Guide - Upgrading to Uno Themes v-next](https://github.com/unoplatform/Uno.Themes/blob/master/doc/material-migration.md#upgrading-to-uno-themes-v-next)**

Please feel free to reach out to us with any additional feedback as needed.
