### ISSUE TITLE
When introducing text in a TextBox in WASM, sometimes the Header does not move up as expected.

### ISSUE THREAD

**Issue by Suriman** [unoplatform/Uno.Themes#1472]
## Current behavior

In WASM, when writing in the TextBox the Header should move up but sometimes it doesn't. This causes a mix of the Header and the introduced text, and this is incorrect.

## Expected behavior

When introducing text in a TextBox, the Header should always move up.

## How to reproduce it (as minimally and precisely as possible)

 1. Open the attached solution and compile it.
 2. Execute it WASM head.
 3. Write in the TextBox till this behavior happens.

## Environment

NuGet package(s): Uno.WinUI
NuGet package version(s): Uno.WinUI 5.3.144

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] UWP
- [ ] MacOS

## Anything else we need to know?

Workaround:
No known workaround.

Works on UWP/WinUI: yes

IDE:
Visual Studio 2022

IDE version:
17.11.2
[TextBoxHeaderWasm.zip](https://github.com/user-attachments/files/16966315/TextBoxHeaderWasm.zip)

**Comment by kazo0** [comment]
FYI @eriklimakc

**Comment by ADD-Noureddine-Maachi** [comment]
Here is an snip of the behavior:

![Screenshot 2024-09-11 130614](https://github.com/user-attachments/assets/fccd525f-002b-4e52-bcfe-5f618fb5cbe0)

**Comment by kazo0** [comment]
@ADD-Noureddine-Maachi This has been fixed in the latest packages for Uno.Material.WinUI. The backport to Uno Material 5.1 has just been published. You should be able to use the latest stable packages for Material by placing this in you .csproj

```xml
<PropertyGroup>
    <UnoThemesVersion>5.1.9</UnoThemesVersion>
</PropertyGroup>
```

There should soon be a new Uno.Sdk 5.3.x version published that will include the latest Uno Material stable version

Let me know if you are still experiencing this issue after bumping to latest stable

**Comment by ADD-Noureddine-Maachi** [comment]
Thank you so much @kazo0! We are no longer experiencing the problem. I will be attentive to a new Uno.Sdk 5.3.x including that Uno Material stable version. :)

**Comment by agneszitte** [comment]
@kazo0 can this issue be closed?

**Comment by agneszitte** [comment]
> Thank you so much @kazo0! We are no longer experiencing the problem. I will be attentive to a new Uno.Sdk 5.3.x including that Uno Material stable version. :)

Hi @ADD-Noureddine-Maachi / @Suriman, the fix is available starting with **Uno.Sdk 5.3.112**.
(You will be able to remove the specific Uno Themes version `<UnoThemesVersion>5.1.9</UnoThemesVersion>`)
