### ISSUE TITLE
[WinUI][Material] HyperlinkButton content it is not underlined

### ISSUE THREAD

**Issue by ADD-Noureddine-Maachi** [unoplatform/Uno.Themes#1483]
### Current behavior

The `HyperlinkButton` content should be underlined, as shown in Uno Gallery.  For WASM & WPF heads works as expected, but somehow for WinUI isn't underlined.

### Expected behavior

The `HyperlinkButton` content should be underlined too.

### How to reproduce it (as minimally and precisely as possible)

Take this snippet to a XAML and test it on WinUI head:
```
<HyperlinkButton
    Content="Hyperlink"
    Style="{StaticResource MaterialHyperlinkButtonStyle}" />
``` 

### Works on UWP/WinUI

No

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI version 5.3.144

### Affected platforms

WinAppSDK

### IDE

Visual Studio 2022

### IDE version

17.11.3

**Comment by morning4coffe-dev** [comment]
CC @ramezgerges should we close this issue?

**Comment by ramezgerges** [comment]
Yes! Thanks.

**Comment by ADD-Noureddine-Maachi** [comment]
Thank you for solving it! :) 

It could be possible to have it backported to the 5.4?

**Comment by morning4coffe-dev** [comment]
@ADD-Noureddine-Maachi For sure, the backports have been created for 5.3 (Uno.Themes has a bit different versioning, but it should be available with the latest versions). Thanks

**Comment by ADD-Noureddine-Maachi** [comment]
Perfect. Thanks!
