### ISSUE TITLE
A multiline TextBox does not move up the header

### ISSUE THREAD

**Issue by Suriman** [unoplatform/Uno.Themes#1487]
## Current behavior

Using a multiline TextBox with a header when you write some lines the header does not move up to the top of the field.

## Expected behavior

The Header is moved up when write in the field.

## How to reproduce it (as minimally and precisely as possible)

1. Open the attached solution and compile it.
2. Execute it in any platform.
3. Write in the TextBox.

## Workaround:

There is a TestTextBox style in the attached solution with VerticalAlignment of the HeaderElement changed to Top, you can use it.

## Environment

Visual Studio 2022 17.11.4

Nuget Package:

Package Version(s):

Uno.WinUI 5.4.27

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [X] Skia (WPF)
- [X] WinAppSDK
- [ ] MacOS

## Anything else we need to know?

[TestBoxMultilineHeader.zip](https://github.com/user-attachments/files/17291134/TestBoxMultilineHeader.zip)

**Comment by kazo0** [comment]
fyi @eriklimakc

**Comment by Xiaoy312** [comment]
![material outline multiline textbox](https://github.com/user-attachments/assets/ace125a0-2eb3-4f8f-ab01-3fa8db8ab160)

**Comment by agneszitte** [comment]
@Suriman same comment as https://github.com/unoplatform/Uno.Themes/issues/1469#issuecomment-2465263566 to be able to have the fixes with the latest Uno Themes dev version.

**Comment by Xiaoy312** [comment]
The fix didn't make it into sdk@5.5.48 -> themes@5.3.1
It is only available from themes@5.4.0-dev.6 and onward.

**Comment by Xiaoy312** [comment]
@agneszitte @kazo0 any plan to backport this, or when this will make it to the vNext?
