### ISSUE TITLE
[Material][PasswordBox] Content moves on pointer-over

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/Uno.Themes#1493]
## Current behavior
notice the single pixel translation on the content:
![material outlined passbox on hover](https://github.com/user-attachments/assets/526de51a-1918-4fe2-aa6c-76589afe4dc0)
![material outlined passbox on hover](https://github.com/user-attachments/assets/83130619-ecc8-4c0c-ae95-c65271b3f1a8)

## Expected behavior
^ should not happen

## How to reproduce it (as minimally and precisely as possible)
- https://unogallerycanary.z27.web.core.windows.net/
- navigate to UI Components\PasswordBox
- hover on the "Outlined" one

## Environment
Nuget Package: 
Package Version(s): f4256d1e3fee2
Affected platform(s): any plat
## Anything else we need to know?

**Comment by morning4coffe-dev** [comment]
@agneszitte Does the https://github.com/unoplatform/uno.studio/issues/537 no longer repro after/before the latest changes? Last week, I was able to repro the issue only on WASM with Uno.Themes master. I also discussed this issue with Martin and there might be some difference in how borders are rendered on WASM for now, which would be beneficial to investigate.

**Comment by agneszitte** [comment]
> @agneszitte Does the [unoplatform/uno.studio#537](https://github.com/unoplatform/uno.studio/issues/537) no longer repro after/before the latest changes? Last week, I was able to repro the issue only on WASM with Uno.Themes master. I also discussed this issue with Martin and there might be some difference in how borders are rendered on WASM for now, which would be beneficial to investigate.

FYI @Xiaoy312, @jeromelaban

**Comment by morning4coffe-dev** [comment]
@agneszitte I can confirm, I no longer see the issue on WASM as well with the fixes, but the root cause may still be there in core. CC @MartinZikmund 
While doing the testing, I noticed that we might need to apply the same fix for ComboBox/other controls with outline as well:
 
https://github.com/user-attachments/assets/ac01226f-8eea-4a18-82d8-03d461f7bae8

**Comment by Xiaoy312** [comment]
> While doing the testing, I noticed that we might need to apply the same fix for ComboBox/other controls with outline as well:

we will track that in #1500
