### ISSUE TITLE
[Material] [Button] Icon misaligned for when using PathIcon

### ISSUE THREAD

**Issue by Kunal22shah** [unoplatform/Uno.Themes#1501]
## Current behavior

 if i replace the FontIcon to Path icon here, the icon isn't aligned with the content:
https://github.com/unoplatform/Uno.Themes/blob/4a892520654ee311755ab151020327e237291b4e/src/samples/UWP/Uno.Themes.Samples.Shared/Content/Controls/ButtonSamplePage.xaml#L410
 ```
 								<Button Content="Text Button"
										Style="{StaticResource MaterialTextButtonStyle}">
									<ut:ControlExtensions.Icon>
										<PathIcon Data="M19 6.41L17.59 5L12 10.59L6.41 5L5 6.41L10.59 12L5 17.59L6.41 19L12 13.41L17.59 19L19 17.59L13.41 12L19 6.41Z" />
									</ut:ControlExtensions.Icon>
								</Button>
```
![image](https://github.com/user-attachments/assets/33a5c611-c821-4bbe-bfdd-98ed7c868a99)

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] UWP
- [ ] MacOS

**Comment by Xiaoy312** [comment]
cause your svg icon is not centered on a 20x20 grid:
![image](https://github.com/user-attachments/assets/7e0cbc87-5845-4f87-874e-4569d8a6cc4d)

use:
```
M17 4.41 15.59 3 10 8.59 4.41 3 3 4.41 8.59 10 3 15.59 4.41 17 10 11.41 15.59 17 17 15.59 11.41 10 17 4.41Z
```
