### ISSUE TITLE
[Material] Support RadioMenuFlyoutItem

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#1508]
We should be supporting a Material style for the `RadioMenuFlyoutItem` type

This would map nicely to the Selectable Menu Items spec: https://m3.material.io/components/menus/specs#dc2e3722-43be-4a95-a09b-b9fba9180401

<img width="1012" alt="image" src="https://github.com/user-attachments/assets/8a04269c-4458-48e8-b08e-f9b814383057" />

**Comment by agneszitte** [comment]
@kazo0 is it just me or I don't see the example you added for this on the Flyout sample page on the Uno.Themes sample app ?
([Wasm 🧪](https://unothemesqa.z9.web.core.windows.net/) or [Wasm 🐤](https://unothemescanary.z9.web.core.windows.net/))

Wondering to make sure @jhanvi03 and @Darsh0307 can do some QA for it.

Also, should an example be added to the Gallery sample app as well?
