### ISSUE TITLE
SnackBar

### ISSUE THREAD

**Issue by MatFillion** [unoplatform/Uno.Themes#36]
## What would you like to be added:
https://material.io/components/snackbars
## Why is this needed:
It's part of the Material Design specs and gives great contextual information
## For which Platform:

- [x] UWP
- [x] iOS
- [x] Android
- [x] WebAssembly

**Comment by MatFillion** [comment]
As an additional requirement, for snackbar we should have a way to trigger it in C#. Similar to the Android API

SnackBar.Make(...).Show()

To discuss!

**Comment by agneszitte-nventive** [comment]
Issue closed for Uno.Themes as the SnackBar control was removed and another issue is now open for Uno.Toolkit.UI (https://github.com/unoplatform/uno.toolkit.ui/issues/171) in order to create a better cross-platform control in Toolkit.
