### ISSUE TITLE
Workaround for WASM Ripple effect only triggering once

### ISSUE THREAD

**Issue by NicolasChampagne** [unoplatform/Uno.Themes#373]
## With workaround behavior
Wasm ripple effect occurs when parent captures a pointer

## Without workaround behavior
Wasm ripple effect only works once. 

## Location
Ripple.cs

## Environment

Affected platform(s):

- [] iOS
- [ ] Android
- [x] WebAssembly
- [ ] UWP
- [ ] MacOS

**Comment by agneszitte-nventive** [comment]
Issue closed with #588.
