### ISSUE TITLE
Feature: Modal Bottom Sheet

### ISSUE THREAD

**Issue by NicolasChampagne** [unoplatform/Uno.Themes#399]

**Comment by Xiaoy312** [comment]
implemented in Toolkit as [DrawerControl](https://github.com/unoplatform/uno.toolkit.ui/blob/main/doc/controls/DrawerControl.md) and [DrawerFlyoutPresenter](https://github.com/unoplatform/uno.toolkit.ui/blob/main/doc/controls/DrawerFlyoutPresenter.md).
