### ISSUE TITLE
RadioButton

### ISSUE THREAD

**Issue by MatFillion** [unoplatform/Uno.Themes#4]

**Comment by StewartPolsky** [comment]
When tapping "See Style" the displayed style code snippet is cut off on the right side

![Uno Material_RadioButton Style](https://user-images.githubusercontent.com/49959074/82467540-c38cb200-9a8f-11ea-867e-f212f29fb61b.gif)

**Comment by XiaotianNetlift** [comment]
The xaml issue will be fixed in #165
