### ISSUE TITLE
[WASM] ToggleSwitch thumb slot seems too narrow

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/Uno.Themes#441]
## How to reproduce it (as minimally and precisely as possible)
1. Open https://unogallery-wasm-staging.azurewebsites.net/
2. Check the "Overview" pane
3. Go to __ToggleSwitch__ section
4. Start dragging the first __ToggleSwitch__ control
5. Overve thumb can't go to the far right side of the control, live it's stuck a little before the end of it...
![image](https://user-images.githubusercontent.com/4174207/104938175-b4426900-597c-11eb-9806-00f17501858a.png)

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

**Comment by Xiaoy312** [comment]
issue is also occuring on UWP too, but only with MaterialToggleSwitchStyle, not the default one
```
UpdateSwitchKnobPosition(double relativeOffset) => _knobTranslateTransform?.X = GetAbsoluteOffset(relativeOffset);
    double GetAbsoluteOffset(double relativeOffset) =>
        $clamp(0, (IsOn ? maxOffset : 0) + relativeOffset, GetMaxOffset());
    GetMaxOffset() =>
        (_switchKnobBounds?.ActualWidth - _switchKnob?.ActualWidth) ?? 0; // 40 - 22 = 18

// _knobTranslateTransform?.X -> { dragging: [0..18], on: 22 }
// !!! Grid.Column[0].ActualWidth (44) != _switchKnobBounds.ActualWidth (40)
```

The `SwitchKnobBounds` marker used to calculate the draggable range has a `Margin="2,0"` on it, causing this issue.
Dropping that fixed it, but to preserve the look, existing `SwitchKnobBounds` was renamed to `HighlightBorder` 
and another `SwitchKnobBounds` without margin was added.
