### ISSUE TITLE
Add Cupertino ToggleSwitch

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#461]
## What would you like to be added:

Cupertino theme for ToggleSwitch (ToggleButton?)
https://developer.apple.com/design/human-interface-guidelines/ios/controls/switches/
https://api.flutter.dev/flutter/cupertino/CupertinoSwitch-class.html
https://github.com/dotnet/GraphicsControls/blob/master/src/GraphicsControls/Controls/Switch/Switch.cupertino.shared.cs

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/switch.dart

if (IsToggled)
Cupertino.Color.SystemColor.Light.Green
            else
 Cupertino.Color.SystemGray.Light.Gray4

## For which Platform:

- [x] UWP
- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] macOS

![image](https://user-images.githubusercontent.com/4793020/109499516-01792680-7a63-11eb-9a87-7d462a48d2f8.png)![image](https://user-images.githubusercontent.com/4793020/109500072-bd3a5600-7a63-11eb-9403-323e5f90f939.png)

**Comment by Romana-Nan** [comment]
Verified on build  1.0.0 (716)
