### ISSUE TITLE
Add Cupertino Slider

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#464]
## What would you like to be added:
Add Cupertino theme for Slider 

https://developer.apple.com/design/human-interface-guidelines/ios/controls/sliders/
https://api.flutter.dev/flutter/cupertino/CupertinoSlider-class.html
https://github.com/dotnet/GraphicsControls/blob/master/src/GraphicsControls/Controls/Slider/Slider.cupertino.shared.cs

SliderTrackBackgroundColor = "#8E8E93";
SliderTrackProgressColor = "#007AFF";
SliderThumbColor = "#161313";

## For which Platform:

- [x] UWP
- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] macOS

**Comment by Romana-Nan** [comment]
Verified on build  1.0.0 (716)
