### ISSUE TITLE
General direction of Uno.Themes?

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/Uno.Themes#482]
I'm trying to understand the general direction of the Uno.Themes repo.

1) If I'm not mistaken this repo previously was named Uno.Material. The current name suggests that this now is intended to be a more general approach to provide custom theming for UNO. Is my understanding accurate or am I reading to much into it?

2) Regardless of any customizing the limitation to two 'themes' (dark and light) stemming from UWP still would apply, correct?

3) Despite any (color) customization the general layout of the themed controls would always be following the material guidelines, correct?

4) Is the theming available across virtually all controls? If no, what are the plans to fill the gaps?

5) Lastly ... theming is available across all UNO supported platform, correct? I saw some references to Android native which left be confused

Thanks in advance

**Comment by francoistanguay** [comment]
> 1. If I'm not mistaken this repo previously was named Uno.Material. The current name suggests that this now is intended to be a more general approach to provide custom theming for UNO. Is my understanding accurate or am I reading to much into it?

We renamed so we can add Cupertino (similar to https://flutter.dev/docs/development/ui/widgets/cupertino) and it might even make sense to move our Fluent default theme here.

> 2. Regardless of any customizing the limitation to two 'themes' (dark and light) stemming from UWP still would apply, correct?

Light/Dark will remain available. Look at Uno.Themes as the remove for various design system.s

> 3. Despite any (color) customization the general layout of the themed controls would always be following the material guidelines, correct?

Layout will be driven by the chosen Design system.

> 4. Is the theming available across virtually all controls? If no, what are the plans to fill the gaps?

What we're providing is convention for resource names and styles for many foundational controls. If a Control that you're using isn't styled, you can add the style to your app directly. 

> 5. Lastly ... theming is available across all UNO supported platform, correct? I saw some references to Android native which left be confused

Yes. Native styles and "BindableXXX" controls might eventually be deprecated.

**Comment by DierkDroth** [comment]
Thanks for clarification @francoistanguay. I definitely will keep an eye...
