### ISSUE TITLE
[Android/iOS][Dark / Light Mode] Changing the app to Dark / Light mode, a grey screen is displayed 

### ISSUE THREAD

**Issue by Romana-Nan** [unoplatform/Uno.Themes#499]
**Steps to Reproduce:**

1. Launch app
2. Tap Burger menu
3. Select Dark mode
4. Notice a grey screen is displayed
5. Change to Light mode
6. Notice a grey screen is displayed

**Current behaviour**

![thumbnail_Capture d’écran, le 2021-03-02 à 13 53 28](https://user-images.githubusercontent.com/73650950/109700698-1edfea80-7b60-11eb-8c20-eb6306bb1ef7.jpg)

**Expected behaviour**
![thumbnail_Capture d’écran, le 2021-03-02 à 13 53 41](https://user-images.githubusercontent.com/73650950/109700682-18517300-7b60-11eb-86a6-c96269839716.jpg)

**Repro rate**
100%

**Affected platform(s):**
Android
iOS

**Version & devices**
1.0.0 (650) 

iPhone 6S - 14.0.1
 Samsung S8 - 7

**Comment by Guidemarcus** [comment]
We will fix this by closing the navigation view every time we change the theme

**Comment by Romana-Nan** [comment]
Verified on build 1.0.0 (667)
