### ISSUE TITLE
Add Cupertino PasswordBox

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#506]
## For which Platform:

- [x] UWP
- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] macOS

![image](https://user-images.githubusercontent.com/4793020/109824901-45a52c00-7c07-11eb-9adc-de3c523f5519.png)![image](https://user-images.githubusercontent.com/4793020/109824948-535ab180-7c07-11eb-9843-fa3aaf58eb4e.png)

**Comment by Romana-Nan** [comment]
Verified on build  1.0.0 (716)
