### ISSUE TITLE
[Android/iOS][Controls] Changing app from Light  to Dark mode or Dark to Light mode, some text are missing

### ISSUE THREAD

**Issue by Romana-Nan** [unoplatform/Uno.Themes#508]
**Steps to Reproduce:**

1. Launch app on light or dark mode
2. From Burger menu select Controls
3. Tap any item
4. Notice all the content is displayed for selected item
5. From Burger menu change app in Light / Dark mode
6. Notice text displayed for selected item

**NOTE**
The issue occurs in all Controls item details

**Current behaviour**
![thumbnail_Capture d’écran, le 2021-03-03 à 10 57 52](https://user-images.githubusercontent.com/73650950/109836424-2233ae80-7c12-11eb-8c00-126e2695580d.jpg)

**Expected behaviour**
![Capture d’écran, le 2021-03-03 à 10 58 31](https://user-images.githubusercontent.com/73650950/109836441-25c73580-7c12-11eb-95b2-af62a3efcbcc.png)

**Repro rate**
100%

**Affected platform(s):**
Android
iOS

**Version & devices**
1.0.0 (661)

Samsung Galaxy A50 - 9
iPhone 6S - 14.0.1

**Comment by Guidemarcus** [comment]
This issue seems to come the fact that the text styles theme are not updated for some reason

**Comment by Guidemarcus** [comment]
This issue seems to be Android only now
