### ISSUE TITLE
Add Material theme for InfoBar

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#518]
## What would you like to be added:

InfoBar: https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.infobar?view=winui-2.5

Material Banners: https://material.io/components/banners

## For which Platform:

- [x] UWP
- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] macOS

**Comment by Romana-Nan** [comment]
Verified on build  1.0.0 (716)
