### ISSUE TITLE
[Material] Create style for MUXC NavigationView

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#571]
Default NavView Style:
https://github.com/unoplatform/uno/blob/master/src/Uno.UI/Microsoft/UI/Xaml/Controls/NavigationView/NavigationView.xaml

WinUI NavView:
https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.navigationview?view=winui-2.5

We should base this style off of what has already been done inside of Gallery:
https://github.com/unoplatform/Uno.Gallery/blob/master/Uno.Gallery/Uno.Gallery.UWP/Views/Styles/NavigationView.xaml

**Comment by agneszitte-nventive** [comment]
@kazo0 this one is still relevant right ?

**Comment by Xiaoy312** [comment]
first implemented to v1 in #622, later copied to v2 in #756.
