### ISSUE TITLE
[Material/Cupertino] Add styles for TabBar

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#578]
## What would you like to be added:

Material and Cupertino styles for the new TabBar control from Uno.UI.Toolkit

[Material Guidance](https://material.io/components/tabs)
![image](https://user-images.githubusercontent.com/4793020/119825163-ab324d00-bec4-11eb-9fbb-f58a10bf63e6.png)
![image](https://user-images.githubusercontent.com/4793020/124622963-8af19880-de49-11eb-9c7b-e2d01a13d344.png)

[Cupertino Guidance](https://developer.apple.com/design/human-interface-guidelines/ios/bars/tab-bars/)
![image](https://user-images.githubusercontent.com/4793020/119825120-a1a8e500-bec4-11eb-9d36-3b00210ac2ab.png)

## For which Platform:

- [x] UWP
- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] macOS

**Comment by agneszitte-nventive** [comment]
@kazo0 do you have the status of this issue please?
