### ISSUE TITLE
[ComboBox] Placeholder label not visible when a value is selected

### ISSUE THREAD

**Issue by avikeid2007** [unoplatform/Uno.Themes#596]
## What would you like to be added:
Need to have the placeholder label visible when a value is selected for the ComboBox similar to the TextBox control.

## Why is this needed:
Due to no placeholder visible when a value is selected, it looks odd that all other controls have the placeholder visible, and Combobox didn't in UI form.

![image](https://user-images.githubusercontent.com/11132795/125108090-2b241780-e0ff-11eb-9b09-c3447eb266a2.png)

## For which Platform:

- [x] UWP
- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] macOS

**Comment by agneszitte-nventive** [comment]
@jeromelaban 
Filled ComboBox style is also missing in addition to the Header for the Material styles. 
(For the TextBox control we both have the filled and outlined styles like in the guidelines).
I will work on it at the same time as properly adding the Header with the translate animation similar to the TextBox Control.

![image](https://user-images.githubusercontent.com/16295702/127222242-f12660e3-4688-4891-a301-42362bb2b114.png)

**Comment by agneszitte-nventive** [comment]
Separated issue entered for the Filled style missing:
https://github.com/unoplatform/Uno.Themes/issues/600

**Comment by avikeid2007** [comment]
Thanks
