### ISSUE TITLE
[TextBox][Android] MaterialOutlinedTextBoxStyle Placeholder is partially hidden while transitioning when the user is typing

### ISSUE THREAD

**Issue by takla21** [unoplatform/Uno.Themes#598]
## Current behavior
On some android devices, it seems that the placeholder is partially hidden while it transitions when the user is starting to type. This only apply for the outlined style.

**Tested on Samsung Galaxy Note8 Android 9** 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/17461593/125527660-ad42c40e-a263-4969-a8a4-db07d311806c.gif)

## Expected behavior

**Tested on One plus 7 pro Android 10**
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/17461593/125527733-511bb329-b5a4-4f5e-905b-1ad00210162c.gif)

## How to reproduce it (as minimally and precisely as possible)

- Download this sample [MaterialTextBoxSample.zip](https://github.com/unoplatform/Uno.Themes/files/6812114/MaterialTextBoxSample.zip)
- Deploy on android
- Type anything

## Environment

Nuget Package:

Uno.Material
Package Version(s):  1.0.0-dev.786

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] UWP
- [ ] MacOS

**Comment by jeromelaban** [comment]
Can you revalidate with 1.0.0-dev.788 ?

**Comment by takla21** [comment]
Yeah it seems fix on this version. And also smoother too

![ezgif com-gif-maker](https://user-images.githubusercontent.com/17461593/125795362-f6852d4a-d824-4780-b829-f36b928a782b.gif)

I'm closing this issue.

Thank you
