### ISSUE TITLE
[Material][ChipGroup] SelectedItem does not work

### ISSUE THREAD

**Issue by ExiledNarwal28** [unoplatform/Uno.Themes#612]
## Current behavior

Defining a SelectedItem (used as default or with `Mode=TwoWay`) does not display the selected item.

I got this by wrapping the `ChipGroup` in a `DelayControl` from `Nventive.View.Controls`, but that's not a proper solution. Also, this solution does not work on UWP.

Here's what I have on Wasm, following my repro steps : 

![image](https://user-images.githubusercontent.com/18317767/128088753-48ecf4b3-7453-4e99-b7a3-1cc280120439.png)

My repro steps are pretty basic. This issue comes from another project, where we use ViewModels to get both the ItemsSource and SelectedItem.

## Expected behavior

SelectedItem should work with a default value, highlighting the selected item at render.

## How to reproduce it (as minimally and precisely as possible)

- Clone this repo
- Add those two lines in `TestCollections` (`src\samples\Uno.Themes.Samples\Uno.Themes.Samples.Shared\Entities\Data\TestCollections.cs`)
```csharp
public static IEnumerable<SelectableData> TestArray { get; } = CreateItems();
public static SelectableData TestItem { get; } = TestArray.First();
```
- Add this to `ChipSamplePage.xaml` (`src\samples\Uno.Themes.Samples\Uno.Themes.Samples.Shared\Content\Controls\ChipSamplePage.xaml`)
```xaml
<!-- GroupChip Choice with selected item -->
<TextBlock Text="Choice with selected item"
		   Style="{StaticResource MaterialSubtitle1}" />
<smtx:XamlDisplay UniqueKey="ChipSamplePage_GroupChip_Choice_WithSelectedItem"
				  Style="{StaticResource XamlDisplayBelowStyle}">

	<ScrollViewer HorizontalScrollMode="Auto"
				  HorizontalScrollBarVisibility="Auto"
				  VerticalScrollMode="Disabled"
				  VerticalScrollBarVisibility="Hidden">

		<chips:ChipGroup ItemsSource="{Binding Data.TestArray}"
						 SelectedItem="{Binding Data.TestItem}"
						 Style="{StaticResource MaterialChipGroupStyle}"
						 ItemContainerStyle="{StaticResource MaterialPrimaryChipStyle}"
						 SelectionMode="Single"
						 Margin="8,0,8,8">

			<chips:ChipGroup.ItemTemplate>
				<DataTemplate>
					<TextBlock Style="{StaticResource MaterialBody1}">
					<Run Text="Item #" /><Run Text="{Binding Index}" />
					</TextBlock>
				</DataTemplate>
			</chips:ChipGroup.ItemTemplate>
		</chips:ChipGroup>
	</ScrollViewer>
</smtx:XamlDisplay>
```

## Environment

Nuget Package: Uno.Material

Package Version(s): 1.0.0-dev.788

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] UWP (chips simply don't work, check issue #611)
- [x] MacOS

**Comment by vincentcastagna** [comment]
After pairing with @agneszitte-nventive we identified another issue related to this one . 

https://github.com/unoplatform/Uno.Themes/issues/624
