### ISSUE TITLE
[Android][Chip] Chips have a overlapping background over the rounded part of the Border

### ISSUE THREAD

**Issue by MaximeDion-Work** [unoplatform/Uno.Themes#616]
## Current behavior

some part of the elevated view is overlapping the rounded part of the border

![image](https://user-images.githubusercontent.com/64613932/128378204-b7d5d27b-ab2c-4bfa-85f0-3165ffeffe30.png)

![image](https://user-images.githubusercontent.com/64613932/128378269-72d939fa-e776-4aec-9d08-9b54e81db873.png)

![image](https://user-images.githubusercontent.com/64613932/128378308-c54281d9-baaf-405e-af76-4f5842e683a5.png)

## Expected behavior

There should be no overlap.

## How to reproduce it (as minimally and precisely as possible)

Used a ChipGroup on android. Setting the border to 5 helps but is not required.

## Environment

Nuget Package:

Package Version(s): Uno.UI 3.0.0-dev.1533

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] UWP
- [ ] MacOS

**Comment by jeromelaban** [comment]
@MaximeDion-Work can you validate with a more recent version of Uno ? 3.0.0-dev is quite old.

**Comment by MaximeDion-Work** [comment]
Will do

**Comment by MaximeDion-Work** [comment]
Same result with 3.6.0 dev 275

**Comment by MaximeDion-Work** [comment]
From what I can tell the issue seems to be caused by the ElevatedView switching it to a grid (in the Uno.Theme project) solves the issue.

**Comment by jeromelaban** [comment]
> From what I can tell the issue seems to be caused by the ElevatedView switching it to a grid (in the Uno.Theme project) solves the issue.

I'm not sure to understand the comment. Is it fixed or did you find a workaround? If you did, can you post the change that you made ?

**Comment by MaximeDion-Work** [comment]
No I just open the Uno.Theme project and changed the elevated view used in the style template for a grid. But we are not looking to rewrite the style of the chip in our project.

**Comment by jeromelaban** [comment]
@MaximeDion-Work can you post the change that you made, so we can adjust it in uno.themes?

**Comment by MaximeDion-Work** [comment]
I can but obviously changing an elevated view for a grid means that you loose on he drop shadow.

**Comment by MaximeDion-Work** [comment]
Ok turns out I was wrong. The elevatedView is not at fault but it's about the BorderBrushColor not being opaque. I switch the border brush to Black and you don't see any overlap.

`<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
					xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
					xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
					xmlns:controls="using:Uno.Material.Controls"
					xmlns:win="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
					xmlns:not_win="http://uno.ui/not_win"
					xmlns:toolkit="using:Uno.UI.Toolkit"
					mc:Ignorable="not_win">

	<x:String x:Key="ClearGlyphPathData">M10.661012,7.5689991L7.5990001,10.650999 12.939089,15.997999 7.5990001,21.336999 10.661012,24.405 16.007082,19.065 21.369997,24.405 24.430058,21.336999 24.429081,21.336 19.088991,15.998999 24.429081,10.662001 21.345095,7.5819996 16.007082,12.919001z M15.997072,0C24.828983,0 31.994999,7.1770013 31.994999,15.999998 31.994999,24.826997 24.828007,31.999999 15.997072,31.999999 7.1569835,31.999999 1.5270052E-07,24.826997 0,15.999998 1.5270052E-07,7.1799997 7.1569835,0 15.997072,0z</x:String>
	<x:String x:Key="CheckGlyphPathStyle">M28.718018,0L32,3.2819897 10.666016,24.616999 0,13.951997 3.2810059,10.670007 10.666016,18.055033z</x:String>

	<x:Double x:Key="ChipHeight">32</x:Double>
	<x:Double x:Key="ChipElevation">8</x:Double>
	<x:Double x:Key="CheckGlyphHeight">12</x:Double>
	<CornerRadius x:Key="ChipCornerRadius">16</CornerRadius>

	<x:Double x:Key="ThumbnailSize">24</x:Double>
	<CornerRadius x:Key="ThumbnailCornerRadius">12</CornerRadius>

	<Style x:Name="DeleteButtonStyle"
		   TargetType="Button">
		<Setter Property="Template">
			<Setter.Value>
				<ControlTemplate TargetType="Button">
					<Grid x:Name="ButtonLayoutGrid"
						  Background="Transparent">

						<VisualStateManager.VisualStateGroups>
							<VisualStateGroup x:Name="CommonStates">
								<VisualState x:Name="Normal" />
								<VisualState x:Name="PointerOver">
									<VisualState.Setters>
										<Setter Target="BorderRoot.BorderBrush"
												Value="{StaticResource MaterialOnSurfaceBrush}" />
										<Setter Target="BorderRoot.BorderThickness"
												Value="1" />
									</VisualState.Setters>
								</VisualState>
								<VisualState x:Name="Pressed">
									<VisualState.Setters>
										<Setter Target="BorderRoot.BorderBrush"
												Value="{StaticResource MaterialOnSurfaceBrush}" />
										<Setter Target="BorderRoot.BorderThickness"
												Value="1" />
									</VisualState.Setters>
								</VisualState>
								<VisualState x:Name="Disabled">
									<VisualState.Setters>
										<Setter Target="ButtonLayoutGrid.Opacity"
												Value="0" />
									</VisualState.Setters>
								</VisualState>
							</VisualStateGroup>
						</VisualStateManager.VisualStateGroups>

						<Border x:Name="BorderRoot"
								Height="16"
								Width="16"
								CornerRadius="8"
								Background="Transparent">

							<Path x:Name="GlyphElement"
								  Data="{StaticResource ClearGlyphPathData}"
								  Fill="{TemplateBinding Background}"
								  VerticalAlignment="Center"
								  HorizontalAlignment="Center"
								  Stretch="Uniform"
								  Width="16"
								  Height="16"
								  AutomationProperties.AccessibilityView="Raw" />
						</Border>
					</Grid>
				</ControlTemplate>
			</Setter.Value>
		</Setter>
	</Style>

	<Style x:Key="MaterialChipStyle"
		   TargetType="controls:Chip">
		<Setter Property="VerticalAlignment"
				Value="Stretch" />
		<Setter Property="VerticalContentAlignment"
				Value="Center" />
		<Setter Property="Background"
				Value="{StaticResource MaterialOnSurfacePressedBrush}" />
		<Setter Property="Foreground"
				Value="{StaticResource MaterialOnSurfaceMediumBrush}" />
		<Setter Property="Height"
				Value="{StaticResource ChipHeight}" />
		<Setter Property="CornerRadius"
				Value="{StaticResource ChipCornerRadius}" />
		<Setter Property="Padding"
				Value="4,0" />
		<Setter Property="Template">
			<Setter.Value>
				<ControlTemplate TargetType="controls:Chip">
					<Grid>

						<VisualStateManager.VisualStateGroups>
							<VisualStateGroup x:Name="CommonStates">
								<VisualState x:Name="Normal" />
								<VisualState x:Name="PointerOver">
									<VisualState.Setters>
										<Setter Target="ElevatedRoot.Background"
												Value="{StaticResource MaterialOnSurfaceFocusedBrush}" />
									</VisualState.Setters>
								</VisualState>
								<VisualState x:Name="Pressed">
									<VisualState.Setters>
										<Setter Target="ElevatedRoot.Elevation"
												Value="{StaticResource ChipElevation}" />
									</VisualState.Setters>
								</VisualState>
								<VisualState x:Name="Disabled">
									<VisualState.Setters>
										<Setter Target="ElevatedRoot.Opacity"
												Value="0.5" />
									</VisualState.Setters>
								</VisualState>

								<VisualState x:Name="CheckedPointerOver">
									<VisualState.Setters>
										<Setter Target="ElevatedRoot.Background"
												Value="{StaticResource MaterialOnSurfaceFocusedBrush}" />
										<Setter Target="CheckGlyphElement.Visibility"
												Value="Visible" />
									</VisualState.Setters>
								</VisualState>

								<VisualState x:Name="Checked">
									<VisualState.Setters>
										<Setter Target="CheckGlyphElement.Visibility"
												Value="Visible" />
										<Setter Target="ElevatedRoot.Background"
												Value="{StaticResource MaterialOnSurfaceLowBrush}" />
									</VisualState.Setters>
								</VisualState>

								<VisualState x:Name="CheckedPressed">
									<VisualState.Setters>
										<Setter Target="ElevatedRoot.Elevation"
												Value="{StaticResource ChipElevation}" />
									</VisualState.Setters>
								</VisualState>
							</VisualStateGroup>
						</VisualStateManager.VisualStateGroups>

						<toolkit:ElevatedView x:Name="ElevatedRoot"
											  Background="{TemplateBinding Background}"
											  CornerRadius="{TemplateBinding CornerRadius}">

							<Grid CornerRadius="{TemplateBinding CornerRadius}">

								<controls:Ripple Feedback="{StaticResource MaterialOnSurfaceLowBrush}"
												 CornerRadius="{TemplateBinding CornerRadius}"
												 Padding="{TemplateBinding Padding}">
									<Grid>
										<Grid.ColumnDefinitions>
											<ColumnDefinition Width="Auto" />
											<ColumnDefinition Width="*" />
											<ColumnDefinition Width="Auto" />
										</Grid.ColumnDefinitions>

										
										<ContentPresenter x:Name="ThumbnailPresenter"
														  Content="{TemplateBinding Thumbnail}"
														  ContentTemplate="{TemplateBinding ThumbnailTemplate}"
														  Visibility="{Binding Thumbnail, RelativeSource={RelativeSource Mode=TemplatedParent}, Converter={StaticResource MaterialNullToCollapsedConverter}, FallbackValue=Collapsed}"
														  Height="{StaticResource ThumbnailSize}"
														  Width="{StaticResource ThumbnailSize}"
														  CornerRadius="{StaticResource ThumbnailCornerRadius}"
														  AutomationProperties.AccessibilityView="Raw" />

										<Path x:Name="CheckGlyphElement"
											  Data="{StaticResource CheckGlyphPathStyle}"
											  Fill="{TemplateBinding Foreground}"
											  Visibility="Collapsed"
											  VerticalAlignment="Center"
											  HorizontalAlignment="Center"
											  Stretch="Uniform"
											  Height="{StaticResource CheckGlyphHeight}"
											  AutomationProperties.AccessibilityView="Raw" />

										
										<ContentPresenter x:Name="ContentPresenter"
														  ContentTemplate="{TemplateBinding ContentTemplate}"
														  ContentTransitions="{TemplateBinding ContentTransitions}"
														  Content="{TemplateBinding Content}"
														  Foreground="{TemplateBinding Foreground}"
														  VerticalAlignment="{TemplateBinding VerticalContentAlignment}"
														  AutomationProperties.AccessibilityView="Raw"
														  Margin="8,0"
														  Grid.Column="1" />

										
										<Button x:Name="PART_RemoveButton"
												Visibility="{Binding CanRemove, RelativeSource={RelativeSource Mode=TemplatedParent}, Converter={StaticResource MaterialTrueToVisible}, FallbackValue=Collapsed}"
												VerticalAlignment="{TemplateBinding VerticalContentAlignment}"
												Background="{TemplateBinding Foreground}"
												Style="{StaticResource DeleteButtonStyle}"
												Margin="0,0,4,0"
												Grid.Column="2" />
									</Grid>
								</controls:Ripple>
							</Grid>
						</toolkit:ElevatedView>
					</Grid>
				</ControlTemplate>
			</Setter.Value>
		</Setter>
	</Style>

	<Style x:Key="MaterialOutlinedChipStyle"
		   TargetType="controls:Chip"
		   BasedOn="{StaticResource MaterialChipStyle}">
		<Setter Property="Background"
				Value="{StaticResource MaterialSurfaceBrush}" />
		<Setter Property="Foreground"
				Value="{StaticResource MaterialOnSurfaceMediumBrush}" />
		<Setter Property="BorderThickness"
				Value="5" />
		<Setter Property="BorderBrush"
				Value="{StaticResource MaterialOnSurfaceLowBrush}" />
		<Setter Property="Template">
			<Setter.Value>
				<ControlTemplate TargetType="controls:Chip">
					<Grid>

						<VisualStateManager.VisualStateGroups>
							<VisualStateGroup x:Name="CommonStates">
								<VisualState x:Name="Normal" />
								<VisualState x:Name="PointerOver">
									<VisualState.Setters>
										<Setter Target="ElevatedRoot.Background"
												Value="{StaticResource MaterialOnSurfaceHoverBrush}" />
									</VisualState.Setters>
								</VisualState>
								<VisualState x:Name="Pressed">
									<VisualState.Setters>
										<Setter Target="ElevatedRoot.Elevation"
												Value="{StaticResource ChipElevation}" />
									</VisualState.Setters>
								</VisualState>
								<VisualState x:Name="Disabled">
									<VisualState.Setters>
										<Setter Target="ElevatedRoot.Opacity"
												Value="0.5" />
									</VisualState.Setters>
								</VisualState>

								<VisualState x:Name="CheckedPointerOver">
									<VisualState.Setters>
										<Setter Target="ElevatedRoot.Background"
												Value="{StaticResource MaterialOnSurfaceFocusedBrush}" />
										<Setter Target="CheckGlyphElement.Visibility"
												Value="Visible" />
									</VisualState.Setters>
								</VisualState>

								<VisualState x:Name="Checked">
									<VisualState.Setters>
										<Setter Target="CheckGlyphElement.Visibility"
												Value="Visible" />
										<Setter Target="ElevatedRoot.Background"
												Value="{StaticResource MaterialOnSurfaceHoverBrush}" />
									</VisualState.Setters>
								</VisualState>
							</VisualStateGroup>
						</VisualStateManager.VisualStateGroups>

						<toolkit:ElevatedView x:Name="ElevatedRoot"
											  Background="{TemplateBinding Background}"
											  CornerRadius="{TemplateBinding CornerRadius}"
											  BorderBrush="Black"
											  BorderThickness="{TemplateBinding BorderThickness}">

							<Grid CornerRadius="{TemplateBinding CornerRadius}">

								<controls:Ripple Feedback="{StaticResource MaterialOnSurfaceFocusedBrush}"
												 CornerRadius="{TemplateBinding CornerRadius}"
												 Padding="{TemplateBinding Padding}">
									<Grid>
										<Grid.ColumnDefinitions>
											<ColumnDefinition Width="Auto" />
											<ColumnDefinition Width="*" />
											<ColumnDefinition Width="Auto" />
										</Grid.ColumnDefinitions>

										
										<ContentPresenter x:Name="ThumbnailPresenter"
														  Content="{TemplateBinding Thumbnail}"
														  ContentTemplate="{TemplateBinding ThumbnailTemplate}"
														  Visibility="{Binding Thumbnail, RelativeSource={RelativeSource Mode=TemplatedParent}, Converter={StaticResource MaterialNullToCollapsedConverter}, FallbackValue=Collapsed}"
														  Height="{StaticResource ThumbnailSize}"
														  Width="{StaticResource ThumbnailSize}"
														  CornerRadius="{StaticResource ThumbnailCornerRadius}"
														  AutomationProperties.AccessibilityView="Raw" />

										<Path x:Name="CheckGlyphElement"
											  Data="{StaticResource CheckGlyphPathStyle}"
											  Fill="{TemplateBinding Foreground}"
											  Visibility="Collapsed"
											  VerticalAlignment="Center"
											  HorizontalAlignment="Center"
											  Stretch="Uniform"
											  Height="{StaticResource CheckGlyphHeight}"
											  AutomationProperties.AccessibilityView="Raw" />

										
										<ContentPresenter x:Name="ContentPresenter"
														  ContentTemplate="{TemplateBinding ContentTemplate}"
														  ContentTransitions="{TemplateBinding ContentTransitions}"
														  Content="{TemplateBinding Content}"
														  Foreground="{TemplateBinding Foreground}"
														  VerticalAlignment="{TemplateBinding VerticalContentAlignment}"
														  AutomationProperties.AccessibilityView="Raw"
														  Margin="8,0"
														  Grid.Column="1" />

										
										<Button x:Name="PART_RemoveButton"
												Visibility="{Binding CanRemove, RelativeSource={RelativeSource Mode=TemplatedParent}, Converter={StaticResource MaterialTrueToVisible}, FallbackValue=Collapsed}"
												VerticalAlignment="{TemplateBinding VerticalContentAlignment}"
												Background="{TemplateBinding Foreground}"
												Style="{StaticResource DeleteButtonStyle}"
												Margin="0,0,4,0"
												Grid.Column="2" />
									</Grid>
								</controls:Ripple>
							</Grid>
						</toolkit:ElevatedView>
					</Grid>
				</ControlTemplate>
			</Setter.Value>
		</Setter>
	</Style>

	<Style x:Key="MaterialPrimaryChipStyle"
		   TargetType="controls:Chip"
		   BasedOn="{StaticResource MaterialChipStyle}">
		<Setter Property="Background"
				Value="{StaticResource MaterialOnSurfacePressedBrush}" />
		<Setter Property="Foreground"
				Value="{StaticResource MaterialOnSurfaceMediumBrush}" />
		<Setter Property="Template">
			<Setter.Value>
				<ControlTemplate TargetType="controls:Chip">
					<Grid>

						<VisualStateManager.VisualStateGroups>
							<VisualStateGroup x:Name="CommonStates">
								<VisualState x:Name="Normal" />
								<VisualState x:Name="PointerOver">
									<VisualState.Setters>
										<Setter Target="ElevatedRoot.Background"
												Value="{StaticResource MaterialOnSurfaceFocusedBrush}" />
									</VisualState.Setters>
								</VisualState>
								<VisualState x:Name="Pressed">
									<VisualState.Setters>
										<Setter Target="ElevatedRoot.Elevation"
												Value="{StaticResource ChipElevation}" />
										<Setter Target="ContentPresenter.Foreground"
												Value="{StaticResource MaterialOnSurfaceMediumBrush}" />
									</VisualState.Setters>
								</VisualState>
								<VisualState x:Name="Disabled">
									<VisualState.Setters>
										<Setter Target="ElevatedRoot.Opacity"
												Value="0.5" />
									</VisualState.Setters>
								</VisualState>

								<VisualState x:Name="CheckedPointerOver">
									<VisualState.Setters>
										<Setter Target="ContentPresenter.Foreground"
												Value="{StaticResource MaterialPrimaryBrush}" />
										<Setter Target="ElevatedRoot.Background"
												Value="{StaticResource MaterialPrimaryVariantLightBrush}" />
									</VisualState.Setters>
								</VisualState>

								<VisualState x:Name="Checked">
									<VisualState.Setters>
										<Setter Target="ContentPresenter.Foreground"
												Value="{StaticResource MaterialPrimaryBrush}" />
										<Setter Target="ElevatedRoot.Background"
												Value="{StaticResource MaterialPrimaryLowBrush}" />
									</VisualState.Setters>
								</VisualState>

								<VisualState x:Name="CheckedPressed">
									<VisualState.Setters>
										<Setter Target="ElevatedRoot.Background"
												Value="{StaticResource MaterialPrimaryLowBrush}" />
										<Setter Target="ContentPresenter.Foreground"
												Value="{StaticResource MaterialOnSurfaceMediumBrush}" />
										<Setter Target="ElevatedRoot.Elevation"
												Value="{StaticResource ChipElevation}" />
									</VisualState.Setters>
								</VisualState>
							</VisualStateGroup>
						</VisualStateManager.VisualStateGroups>

						<toolkit:ElevatedView x:Name="ElevatedRoot"
											  Background="{TemplateBinding Background}"
											  CornerRadius="{TemplateBinding CornerRadius}">

							<Grid CornerRadius="{TemplateBinding CornerRadius}">

								<controls:Ripple x:Name="RippleRoot"
												 Feedback="{StaticResource MaterialPrimaryFocusedBrush}"
												 CornerRadius="{TemplateBinding CornerRadius}"
												 Padding="{TemplateBinding Padding}">
									<Grid>
										<Grid.ColumnDefinitions>
											<ColumnDefinition Width="Auto" />
											<ColumnDefinition Width="*" />
											<ColumnDefinition Width="Auto" />
										</Grid.ColumnDefinitions>

										
										<ContentPresenter x:Name="ThumbnailPresenter"
														  Content="{TemplateBinding Thumbnail}"
														  ContentTemplate="{TemplateBinding ThumbnailTemplate}"
														  Visibility="{Binding Thumbnail, RelativeSource={RelativeSource Mode=TemplatedParent}, Converter={StaticResource MaterialNullToCollapsedConverter}, FallbackValue=Collapsed}"
														  Height="{StaticResource ThumbnailSize}"
														  Width="{StaticResource ThumbnailSize}"
														  CornerRadius="{StaticResource ThumbnailCornerRadius}"
														  AutomationProperties.AccessibilityView="Raw" />

										
										<ContentPresenter x:Name="ContentPresenter"
														  ContentTemplate="{TemplateBinding ContentTemplate}"
														  ContentTransitions="{TemplateBinding ContentTransitions}"
														  Content="{TemplateBinding Content}"
														  Foreground="{TemplateBinding Foreground}"
														  VerticalAlignment="{TemplateBinding VerticalContentAlignment}"
														  AutomationProperties.AccessibilityView="Raw"
														  Margin="8,0"
														  Grid.Column="1" />

										
										<Button x:Name="PART_RemoveButton"
												Visibility="{Binding CanRemove, RelativeSource={RelativeSource Mode=TemplatedParent}, Converter={StaticResource MaterialTrueToVisible}, FallbackValue=Collapsed}"
												VerticalAlignment="{TemplateBinding VerticalContentAlignment}"
												Background="{TemplateBinding Foreground}"
												Style="{StaticResource DeleteButtonStyle}"
												Margin="0,0,4,0"
												Grid.Column="2" />
									</Grid>
								</controls:Ripple>
							</Grid>
						</toolkit:ElevatedView>
					</Grid>
				</ControlTemplate>
			</Setter.Value>
		</Setter>
	</Style>

	<Style x:Key="MaterialPrimaryOutlinedChipStyle"
		   TargetType="controls:Chip"
		   BasedOn="{StaticResource MaterialChipStyle}">
		<Setter Property="Background"
				Value="{StaticResource MaterialSurfaceBrush}" />
		<Setter Property="Foreground"
				Value="{StaticResource MaterialOnSurfaceMediumBrush}" />
		<Setter Property="BorderThickness"
				Value="5" />
		<Setter Property="BorderBrush"
				Value="{StaticResource MaterialOnSurfaceLowBrush}" />
		<Setter Property="Template">
			<Setter.Value>
				<ControlTemplate TargetType="controls:Chip">
					<Grid>

						<VisualStateManager.VisualStateGroups>
							<VisualStateGroup x:Name="CommonStates">
								<VisualState x:Name="Normal" />
								<VisualState x:Name="PointerOver">
									<VisualState.Setters>
										<Setter Target="ElevatedRoot.Background"
												Value="{StaticResource MaterialOnSurfaceHoverBrush}" />
									</VisualState.Setters>
								</VisualState>
								<VisualState x:Name="Pressed">
									<VisualState.Setters>
										<Setter Target="ElevatedRoot.Elevation"
												Value="{StaticResource ChipElevation}" />
									</VisualState.Setters>
								</VisualState>
								<VisualState x:Name="Disabled">
									<VisualState.Setters>
										<Setter Target="ElevatedRoot.Opacity"
												Value="0.5" />
									</VisualState.Setters>
								</VisualState>

								<VisualState x:Name="CheckedPointerOver">
									<VisualState.Setters>
										<Setter Target="ContentPresenter.Foreground"
												Value="{StaticResource MaterialPrimaryBrush}" />
										<Setter Target="ElevatedRoot.Background"
												Value="{StaticResource MaterialPrimaryFocusedBrush}" />
										<Setter Target="ElevatedRoot.BorderBrush"
												Value="{StaticResource MaterialPrimaryVariantLightBrush}" />
									</VisualState.Setters>
								</VisualState>

								<VisualState x:Name="Checked">
									<VisualState.Setters>
										<Setter Target="ContentPresenter.Foreground"
												Value="{StaticResource MaterialPrimaryMediumBrush}" />
										<Setter Target="ElevatedRoot.Background"
												Value="{StaticResource MaterialPrimaryFocusedBrush}" />
										<Setter Target="ElevatedRoot.BorderBrush"
												Value="{StaticResource MaterialPrimaryVariantLightBrush}" />
									</VisualState.Setters>
								</VisualState>

								<VisualState x:Name="CheckedPressed">
									<VisualState.Setters>
										<Setter Target="ElevatedRoot.Background"
												Value="{StaticResource MaterialPrimaryFocusedBrush}" />
										<Setter Target="ContentPresenter.Foreground"
												Value="{StaticResource MaterialOnSurfaceMediumBrush}" />
										<Setter Target="ElevatedRoot.Elevation"
												Value="{StaticResource ChipElevation}" />
									</VisualState.Setters>
								</VisualState>
							</VisualStateGroup>
						</VisualStateManager.VisualStateGroups>

						<toolkit:ElevatedView x:Name="ElevatedRoot"
											  Background="{TemplateBinding Background}"
											  CornerRadius="{TemplateBinding CornerRadius}"
											  BorderBrush="Black"
											  BorderThickness="{TemplateBinding BorderThickness}">

							<Grid CornerRadius="{TemplateBinding CornerRadius}">

								<controls:Ripple x:Name="RippleRoot"
												 Feedback="{StaticResource MaterialOnSurfaceFocusedBrush}"
												 CornerRadius="{TemplateBinding CornerRadius}"
												 Padding="{TemplateBinding Padding}">
									<Grid>
										<Grid.ColumnDefinitions>
											<ColumnDefinition Width="Auto" />
											<ColumnDefinition Width="*" />
											<ColumnDefinition Width="Auto" />
										</Grid.ColumnDefinitions>

										
										<ContentPresenter x:Name="ThumbnailPresenter"
														  Content="{TemplateBinding Thumbnail}"
														  ContentTemplate="{TemplateBinding ThumbnailTemplate}"
														  Visibility="{Binding Thumbnail, RelativeSource={RelativeSource Mode=TemplatedParent}, Converter={StaticResource MaterialNullToCollapsedConverter}, FallbackValue=Collapsed}"
														  Height="{StaticResource ThumbnailSize}"
														  Width="{StaticResource ThumbnailSize}"
														  CornerRadius="{StaticResource ThumbnailCornerRadius}"
														  AutomationProperties.AccessibilityView="Raw" />

										
										<ContentPresenter x:Name="ContentPresenter"
														  ContentTemplate="{TemplateBinding ContentTemplate}"
														  ContentTransitions="{TemplateBinding ContentTransitions}"
														  Content="{TemplateBinding Content}"
														  Foreground="{TemplateBinding Foreground}"
														  VerticalAlignment="{TemplateBinding VerticalContentAlignment}"
														  AutomationProperties.AccessibilityView="Raw"
														  Margin="8,0"
														  Grid.Column="1" />

										
										<Button x:Name="PART_RemoveButton"
												Visibility="{Binding CanRemove, RelativeSource={RelativeSource Mode=TemplatedParent}, Converter={StaticResource MaterialTrueToVisible}, FallbackValue=Collapsed}"
												VerticalAlignment="{TemplateBinding VerticalContentAlignment}"
												Background="{TemplateBinding BorderBrush}"
												Style="{StaticResource DeleteButtonStyle}"
												Margin="0,0,4,0"
												Grid.Column="2" />
									</Grid>
								</controls:Ripple>
							</Grid>
						</toolkit:ElevatedView>
					</Grid>
				</ControlTemplate>
			</Setter.Value>
		</Setter>
	</Style>
</ResourceDictionary>
`

**Comment by agneszitte-nventive** [comment]
@jeromelaban I was able to trim down to a much simpler sample code to repro the related issues I noticed on all platforms compared to UWP (The issues were more noticeable with some much bigger values for BorderThickness and CornerRadius properties):

```
<StackPanel>
		<toolkit:ElevatedView Height="100"
							  Width="200"
							  Background="Yellow"
							  CornerRadius="15"
							  BorderBrush="#66121212"
							  BorderThickness="15"
							  Margin="30">
			<Grid Background="DeepPink"
				  CornerRadius="25">
				<TextBlock Text="Test with ElevatedView"
						   VerticalAlignment="Center"
						   HorizontalAlignment="Center" />
			</Grid>
		</toolkit:ElevatedView>

		<Grid Height="100"
			  Width="200"
			  Background="Orange"
			  CornerRadius="15"
			  BorderBrush="#66121212"
			  BorderThickness="15"
			  Margin="30">
			<Grid Background="Red"
				  CornerRadius="25">
				<TextBlock Text="Test with a Grid"
						   VerticalAlignment="Center"
						   HorizontalAlignment="Center" />
			</Grid>
		</Grid>
	</StackPanel>
```

### **Tested with today Uno.UI latest dev => 3.10.0-dev.283**

_**Android:**_
![image](https://user-images.githubusercontent.com/16295702/129077211-525269ee-9453-460c-90c4-03c2979bbeea.png)

_**UWP:**_
![image](https://user-images.githubusercontent.com/16295702/129076787-5318df4a-5f18-4be5-9884-e36d18bb1c78.png)

_**iOS:**_
![image](https://user-images.githubusercontent.com/16295702/129078212-02e4155d-48bb-47c2-9bfa-979d3c466274.png)

_**WASM:**_
![image](https://user-images.githubusercontent.com/16295702/129077032-c9b883e8-426e-4d12-8b28-f515ec9dcdd9.png)

_**Skia GTK:**_
![image](https://user-images.githubusercontent.com/16295702/129078520-b0724398-e145-48e9-98dc-bf848fc8ee90.png)

**Comment by jeromelaban** [comment]
Is it a regression introduced in a recent uno build ?

**Comment by agneszitte-nventive** [comment]
@jeromelaban I'm not sure but I can quickly test with an older version (before 3.9).
(cf. https://github.com/unoplatform/uno/issues/6637)

**Comment by agneszitte-nventive** [comment]
> Is it a regression introduced in a recent uno build ?

@jeromelaban I'm not sure but I can quickly test with an older version (before 3.9 for example).
(cf. unoplatform/uno#6637)

**Comment by agneszitte-nventive** [comment]
> > Is it a regression introduced in a recent uno build ?
> 
> @jeromelaban I'm not sure but I can quickly test with an older version (before 3.9 for example).
> (cf. [unoplatform/uno#6637](https://github.com/unoplatform/uno/issues/6637))

@jeromelaban I have the same results with **Uno.UI 3.8.13**
