### ISSUE TITLE
[UWP][Material][ChipGroup] SelectedItem does not work with Enum type as itemsSource

### ISSUE THREAD

**Issue by vincentcastagna** [unoplatform/Uno.Themes#624]
## Current behavior

- When settings as `ItemsSource `a `IEnumerable<T>` where `T` is of `enum` type, the selection state does not work on UWP. In order to get the selected state, we need to double click the given chip.
 
## Expected behavior

- Using a list of `enum `should work as any other types and the selected state should be reflected in the UI. 

## How to reproduce it (as minimally and precisely as possible)

- This can be easily reproduced with simple code behind.

In a page define : 
```xml
<controls:ChipGroup x:Name="ChipGroup"
		                    Grid.Row="1"
		                    SelectionMode="Single" />
		                    
 <Button Click="ButtonBase_OnClick" Content="Select" Foreground="Red" />
```

In the code behind, simply do : 

```csharp
public ContentPage()
{
	this.InitializeComponent();
	var test = new List<TestEnum>() { TestEnum.KitKat, TestEnum.Lion, TestEnum.Snickers, TestEnum.Oreo };
	ChipGroup.ItemsSource = test;
	ChipGroup.SelectedItem = test.Last();
}

public enum TestEnum
{
	KitKat,
	Oreo,
	Mars,
	Lion,
	Snickers
}

private void ButtonBase_OnClick(object sender, RoutedEventArgs e)
{
	ChipGroup.SelectedItem = TestEnum.Lion;
}
```

Notice that the SelectedItem is set to TestEnum.Oreo but is not reflected in the UI. 
Same if you change it from code behind with a button, the SelectedItem is not in a selected state (or for a few milisec only) 

## Environment

Nuget Package: Material.Uno.UI 1.0.0-dev.812

Package Version(s): Uno.UI 3.10.0-dev.591

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [x] UWP
- [ ] MacOS

**Comment by jeanplevesque** [comment]
Fix will be available in next version containing #625
