### ISSUE TITLE
[ChipGroup] SelectedItem initial binding is not working

### ISSUE THREAD

**Issue by vincentcastagna** [unoplatform/Uno.Themes#626]
## Current behavior

- When binding the `SelectedItem` property from `ChipGroup` to a property in VM, the initial binding is not taken in consideration and does not propagate. 

Clues : 
- This might be due to a race condition between `SelectedItem` being set and `ItemsSource ` being set to late. 
- Also in [`OnSelectedItemChanged`](https://github.com/unoplatform/Uno.Themes/blob/master/src/library/Uno.Material/Controls/Chips/ChipGroup.cs#L117) method of `ChipGroup`, we noticed that checking if `ItemsPanelRoot == null` might not be enough and we should also check that there are items in it. 

## Expected behavior

- As long as a value is pushed into SelectedItem, the value should update and propagates 

## How to reproduce it (as minimally and precisely as possible)

This can be easily reproduced with simple bindings. 

In a page define a chip group with  an `ItemsSource `and bind to a single property for selection : 
```xml
<controls:ChipGroup x:Name="ChipGroup"
		                    Grid.Row="1"
		                    ItemsSource="{Binding SourceGroup}"
		                    SelectedItem="{Binding SelectedGroup}" 
		                    SelectionMode="Single" />
		                    
```

In your VM define : 

```csharp

// Use a simple enum 
public enum TestEnum
{
	KitKat,
	Oreo,
	Mars,
	Lion,
	Snickers
}

// Use any property to bind to a list of it 

public TestEnum[] SourceGroup
{
    get => _sourceGroup;
    set
      {
	  _sourceGroup= value;
	  RaisePropertyChanged();
	}
}
		
public TestEnum SelectedGroup
{
	get => _selectedGroup;
	set
	{
		_selectedGroup= value;
		RaisePropertyChanged();
	 }
}

```

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [x] UWP
- [ ] MacOS

**Comment by jeanplevesque** [comment]
Fix will be available with the next version that includes #628
