### ISSUE TITLE
[Material] Add ContentDialog

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#637]
## What would you like to be added:

Investigation needs to be done to see how customizable is the ContentDialog. We would need the ability to customize the "chrome" surrounding the Content part. So the action button areas as well as CornerRadius, etc.

Material style for ContentDialog

UWP:
![image](https://user-images.githubusercontent.com/4793020/136965233-4d99c8c5-44bb-44b9-9abd-d4b359b451f3.png)

Material:
<img width="158" alt="image" src="https://user-images.githubusercontent.com/4793020/190259410-4cbd8459-c03d-4893-b291-771280d2eae2.png">

Material Guidance:
https://m3.material.io/components/dialogs/overview

## For which Platform:

- [x] UWP
- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] macOS

**Comment by Xiaoy312** [comment]
todo: m3 style

**Comment by NVLudwig** [comment]
@kazo0 I believe we will be adding in the option for users to users to invoque Default Button Property
