### ISSUE TITLE
[Android] TextBox cursor doesn't display correctly after entering text

### ISSUE THREAD

**Issue by MaximeDion-Work** [unoplatform/Uno.Themes#639]
## Current behavior

![image](https://user-images.githubusercontent.com/64613932/137317541-f0974e30-62ba-47fa-8094-5579b51f7f2f.png)

https://user-images.githubusercontent.com/64613932/137326847-e9d7d98a-da3c-4d10-b1f3-52ceba6a3292.mp4

## Expected behavior

![image](https://user-images.githubusercontent.com/64613932/137317624-32f3c605-6597-4a83-9df4-8fc45d6be8b1.png)

## How to reproduce it (as minimally and precisely as possible)

Select a TextBox enter text (can be a single letter)
Wait 3-4 cursor animation cycle
Notice cursor split and blinks out of sync  

## Environment

Nuget Package: Happen on master branch of Uno.Theme

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android (Samsung SM-G975F Android 10.0 - API 29)
- [ ] WebAssembly
- [ ] UWP
- [ ] MacOS

**Comment by jeromelaban** [comment]
Can you specify which version of the package you used, which version of uno you used, and make a video of it? Thanks!

**Comment by MaximeDion-Work** [comment]
Uno: 3.6.0-dev275
Commit number on master branch: 190e2d1d

**Comment by agneszitte-nventive** [comment]
Tested in TZ with Uno.Material 1.2.0 / Uno.UI 4.0.11, the issue is fixed.
( cc @jeanplevesque / @MaximeDion-Work )
