### ISSUE TITLE
Move the opacity from MaterialOverlayColor onto MaterialOverlayBrush

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/Uno.Themes#663]
```xml
<Color x:Key="MaterialOnBackgroundColor">#FFFFFF</Color>
<Color x:Key="MaterialOnSurfaceColor">#DEFFFFFF</Color>
<Color x:Key="MaterialOnErrorColor">#000000</Color>
<Color x:Key="MaterialOverlayColor">#51FFFFFF</Color>
```
One of them doesnt look like the other

note: when working on this, keep an eye on all direct reference of `MaterialOverlayColor` and adjust accordingly
https://github.com/unoplatform/Uno.Themes/blob/cc0f80c7dc5f0fcf6cd719806c42b9e9a3c506d6/src/library/Uno.Material/Styles/Controls/ExpandingBottomSheet.xaml#L186

**Comment by agneszitte-nventive** [comment]
@kazo0 / @Xiaoy312 Is this issue still relevant?

**Comment by Xiaoy312** [comment]
this issue is only relevant in v1 palette; v2 palette doesnt have this problem
we can just ignore this issue as v1 is unofficially deprecated
