### ISSUE TITLE
[All] Setting <extensions:ControlExtensions.Icon> on a button to {x:Null} still reserve space for icon

### ISSUE THREAD

**Issue by MaximeDion-Work** [unoplatform/Uno.Themes#686]
## Current behavior

![image](https://user-images.githubusercontent.com/64613932/143597568-cffae3dd-93bb-493a-99ec-a8b347db24ab.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/64613932/143597671-2c541bb0-6d04-4fa6-bec1-b24f1ddfbf0c.png)

## How to reproduce it (as minimally and precisely as possible)
`
<Button Content="Test"
		Style="{StaticResource MaterialContainedButtonStyle}"
		HorizontalAlignment="Stretch" >
	<extensions:ControlExtensions.Icon>
		<PathIcon Data="{x:Null}" />
	</extensions:ControlExtensions.Icon>
</Button>
`

## Environment

Nuget Package: Uno.Material

Package Version(s): v1.0.2

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] ~~WebAssembly~~
- [x] UWP
- [ ] ~~MacOS~~

**Comment by Xiaoy312** [comment]
While it is possible to specifically to check for empty icon from the library, 
the responsibility should be on the developer (user of this library) to not pass an instance of `IconElement` that displays nothing.

**Comment by jeanplevesque** [comment]
Yeah @Xiaoy312 is right @MaximeDion-Work. `null` needs to be set one level higher.
It doesn't make sense to pass a `PathIcon` instance that has `Data=null`. Just pass `null` to the attached property directly.

**Comment by jeromelaban** [comment]
Let's close this issue for now then. Thanks!

**Comment by jeanplevesque** [comment]
@MaximeDion-Work Can you still test that the bug doesn't happen if you use `null` correctly?

**Comment by MaximeDion-Work** [comment]
I'm not sure what you mean by using "null correctly". I can't make extensions:ControlExtensions.Icon conditional.

<Button Content="Test" Style="{StaticResource MaterialContainedButtonStyle}" 
              HorizontalAlignment="Stretch" > 
    <extensions:ControlExtensions.Icon> 
        <PathIcon Data="{x:Null}" /> 
    </extensions:ControlExtensions.Icon> 
</Button>

**Comment by jeanplevesque** [comment]
> I'm not sure what you mean by using "null correctly". I can't make extensions:ControlExtensions.Icon conditional.

@MaximeDion-Work  Yes you can and that's the proposed solution.
You should be able to do it using a converter and setting the PathIcon as a static resource in that converter.

**Comment by MaximeDion-Work** [comment]
Ok I get it
