### ISSUE TITLE
Color System

### ISSUE THREAD

**Issue by MatFillion** [unoplatform/Uno.Themes#7]
Dark Theme included

https://app.zeplin.io/project/5e344ca7405a53a6ef303bc1/screen/5e50379848b7b962c05da01b

**Comment by StewartPolsky** [comment]
When using Dark theme, ToggleSwitch when off is very difficult to see

![Uno Material Dark Mode Toggle Switch](https://user-images.githubusercontent.com/49959074/82594158-a5977e00-9b71-11ea-8fa1-fdc708b4c1d5.gif)

**Comment by NicolasChampagne** [comment]
> When using Dark theme, ToggleSwitch when off is very difficult to see
> 
> ![Uno Material Dark Mode Toggle Switch](https://user-images.githubusercontent.com/49959074/82594158-a5977e00-9b71-11ea-8fa1-fdc708b4c1d5.gif)

After investigation this should be fixed when we merge #41 
@StewartPolsky @MatFillion
