### ISSUE TITLE
I cannot acces HyphenGlyphPathStyle, CheckGlyphPathStyle anymore

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/Uno.Themes#758]
## Current behavior

When I try to access HyphenGlyphPathStyle and CheckGlyphPathStyle as a static resource in the latest nugets, the app crashes: 
![image](https://user-images.githubusercontent.com/2359550/167521613-4dddc225-38ff-471d-85db-453abab01e11.png) 

## Expected behavior
It should be accessible just like in Uno.material 1.1.0

## How to reproduce it (as minimally and precisely as possible)
Make a project including that 

[MissingGlyph.zip](https://github.com/unoplatform/Uno.Themes/files/8634618/MissingGlyph.zip)

## Environment

Nuget Package:  

Package Version(s): 
- 1.1.0: worked
- 1.3.3 (latest stable): dont have it.
- 2.0.0-dev.183 (latest prerelease): dont have it.

Affected platform(s):
I Only tried on UWP and android, on android, there doesnt seem to be an issue.

- [ ] ~~iOS~~
- [ ] Android
- [ ] ~~WebAssembly~~
- [X] UWP
- [ ] ~~MacOS~~

## Anything else we need to know?
I didnt try on the other platform, but I imagine it doesnt work either.

**Comment by kazo0** [comment]
This is a result of the Xaml Merge. Both Checkbox and Flyout styles were creating a StaticResource with the key `CheckGlyphPathStyle`. So there is now a `CheckBoxCheckGlyphPathStyle` and `FlyoutCheckGlyphPathStyle`

`HyphenGlyphPathStyle` has also changed to `CheckBoxHyphenGlyphPathStyle`
