### ISSUE TITLE
Cannot use it on net6.0-windows10.0.19041 and winappsdk 1.03

### ISSUE THREAD

**Issue by cesarchefinho** [unoplatform/Uno.Themes#767]
Please provide a package with target framework to dot net 6 and windows appsdk 1.03 on nuget

Thanks

**Comment by jeromelaban** [comment]
The current packages are already compatible for those targets, see https://www.nuget.org/packages/Uno.Material.WinUI.

If you're having other issues, please provide additional details.

**Comment by cesarchefinho** [comment]
Not true.

1.3.3 has target framework net5.0-windows10.0.18362

Also it depends on Microsoft.WindowsAppSDK 1.00

There are problems with linking with targetframeword net6. 0-windows.10.0.19041 and windowsappsdk 103

![Screenshot_20220516-200938_Chrome](https://user-images.githubusercontent.com/55895254/168696788-a16410da-58b1-44ab-a762-980536212bd5.jpg)

**Comment by jeromelaban** [comment]
Thanks, we do know what we're publishing.

Please review the answer in the other discussion you opened, we're not going to be updating the themes library to add support for specific versions of .NET and win app sdk, since net5 and 1.0.0 that you pointed at in the screenshot are backward compatible with newer versions.

**Comment by jeromelaban** [comment]
Please review the answer in the other discussion you opened, we're not going to be updating the themes library to add support for specific versions of .NET and win app sdk, since net5 and 1.0.0 that you pointed at in the screenshot are backward compatible with newer versions.

**Comment by cesarchefinho** [comment]
It is not correct.

I use more than 20 packages in my project, from community toolkit, thirdparty library's and even Uno packages like Uno.Lottie.Winui and others from uno, and no one have link or reference problems with net6/appsdk103/Windows19041.

The only packages that I have problems is Uno.material.winui and uno.Toolkit.Winui

You cannot say that this is be compatible. Is isn't and requires hacks on project configuration file like you say (I will test it) 

We are even having trouble with app.Xaml and resources not instânciated by Uno.Material on winui windows project (it works fine on web assembly, on Android, on iOS, Mac and Linux) 

Well.... I will test the reference that you say and I will post here if it works, but a best solution is provide net6 packages support. 

Tanhk you

And sorry for the problems that I say. 

Thank you again

**Comment by jeromelaban** [comment]
Please follow the instructions on the other repro, and if it still does not work please provide attach a repro solution that we can troubleshoot.
