### ISSUE TITLE
[Android] Extra setup for Uno.Material ToggleSwitch dark mode colors is not working 

### ISSUE THREAD

**Issue by arianeleonard** [unoplatform/Uno.Themes#784]
## Current behavior

When completing step 2 of the Uno.Material extra setup for the ToggleSwitch style, the thumb tint color of the control stays the same for dark and light mode. Here's the documentation :  https://github.com/unoplatform/uno/blob/master/doc/articles/features/uno-material-controls-extra-setup.md

## Expected behavior

The MaterialPrimaryColor and MaterialSurfaceVariantColor defined in Resources/values-night/colors should appear as the thumb tint color of the ToggleSwitch when the app is in dark mode.

## How to reproduce it (as minimally and precisely as possible)

1. Launch the repro on Android : 
[ToggleSwitch.zip](https://github.com/unoplatform/Uno.Themes/files/8764327/ToggleSwitch.zip)

2. Skip the onboarding pages.
3. Login with any email and password.
4. On the bottom bar, select the profile/settings section.
5. On the profile page, turn on the switch and notice the thumb tint color.
6. Click on the button "Toggle between themes" to switch to dark mode and notice that the thumb color tint is the same as in light mode. It should be the colors defined in Resources/values-night/colors.xml.

## Environment

Nuget Package:

Package Version(s):
Uno.Material : 1.3.3
Uno.UI : 4.2.6

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] UWP
- [ ] MacOS

**Comment by kazo0** [comment]
This extra setup should no longer be needed. The `MaterialToggleSwitchStyle` from Uno.Material v2.x should be working as desired. 

If you're still experiencing issue with the latest styles, feel free to open an issue on the [Themes repo](https://github.com/unoplatform/Uno.Themes), thanks!
