### ISSUE TITLE
Missing resource key=MaterialProgressRingStyle - ArgumentException

### ISSUE THREAD

**Issue by HakanL** [unoplatform/Uno.Themes#821]
I have a Uno solution with Skia.Wpf, UWP and Wasm heads. I have added Material support in my App.xaml, and it works fine with UWP and Wasm, but when I try to run the Skia.Wpf (.Host) I get an ArgumentException during start up when the resources are merged in the generated file, specifically when Uno.Material.MaterialResources is added to the MergedDictionaries.
I'm not using a ProgressRing, but I can't start the head with material support.

## Current behavior

ArgumentException

## Expected behavior

No exception

## How to reproduce it (as minimally and precisely as possible)

[](https://github.com/HakanL/UnoMultiPlatform1)

## Environment

Nuget Package: Uno.Material.WinUI

Package Version(s): 2.1.0

Affected platform(s):

- [X] WPF
- [ ] Android
- [ ] WebAssembly
- [ ] UWP
- [ ] MacOS

**Comment by HakanL** [comment]
I'm not getting this exception in version 2.0.0 of the Nuget package.

**Comment by kazo0** [comment]
I believe this should be fixed by https://github.com/unoplatform/Uno.Themes/pull/820

But I will have to double check this with a Skia.Wpf solution.

This is using the Uno.WinUI packages and not Uno.UI, right?

**Comment by HakanL** [comment]
Yes, I'm using Uno.WinUI in the non-UWP heads, and then Uno.UI in the UWP (with `#if` in the usings).

**Comment by kazo0** [comment]
@HakanL, the fix should be included in the new 2.2.0 stable release of [Uno.Material.WinUI](https://www.nuget.org/packages/Uno.Material.WinUI/2.2.0) and [Uno.Material](https://www.nuget.org/packages/Uno.Material/2.2.0).
 
I will close this issue as fixed in a little bit but let me know if you are still experiencing the issue

Thanks for the report!

**Comment by kazo0** [comment]
fixed by https://github.com/unoplatform/Uno.Themes/pull/820
