### ISSUE TITLE
Simplify initialization

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#822]
We currently need to explicitly initialize `MaterialFonts`, `MaterialColors`, and `MaterialResources` within the `App.xaml`. Same goes for Uno.Cupertino.

We should be able to have a single point of initialization that would accept the optional Font and ColorPalette override sources.

So the `App.xaml` can go from this:

```xml
 <Application ...>
 	<Application.Resources>
 		<ResourceDictionary>
 			<ResourceDictionary.MergedDictionaries>

 			        <!-- Load WinUI resources -->
 			        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />

 			        <!-- Load Uno.Material resources -->
				<MaterialColors xmlns="using:Uno.Material"
				                OverrideSource="ms-appx:///Style/Application/MaterialColorsOverride.xaml" />
				<MaterialFonts xmlns="using:Uno.Material"
				               OverrideSource="ms-appx:///Style/Application/MaterialFontsOverride.xaml" />
				<MaterialResources xmlns="using:Uno.Material" />

 				<!-- Load custom application resources -->
 				<!-- ... -->

 			</ResourceDictionary.MergedDictionaries>
 		</ResourceDictionary>
 	</Application.Resources>
 </Application>

```

to something like this:
```xml
 <Application ...>
 	<Application.Resources>
 		<ResourceDictionary>
 			<ResourceDictionary.MergedDictionaries>

 				<!-- Load WinUI resources -->
 				<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />

 				<!-- Load Uno.Material resources -->
				<MaterialTheme xmlns="using:Uno.Material"
				               ColorPaletteOverrideSource="ms-appx:///Style/Application/MaterialColorsOverride.xaml"
				               FontOverrideSource="ms-appx:///Style/Application/MaterialFontsOverride.xaml" />

 				<!-- Load custom application resources -->
 				<!-- ... -->

 			</ResourceDictionary.MergedDictionaries>
 		</ResourceDictionary>
 	</Application.Resources>
 </Application>
```

**Comment by kazo0** [comment]
In the end we should be able to consolidate any overrides into a single file. So we can have something like:

```xml
 <Application ...>
 	<Application.Resources>
 		<ResourceDictionary>
 			<ResourceDictionary.MergedDictionaries>

 				<!-- Load WinUI resources -->
 				<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />

 				<!-- Load Uno.Material resources -->
				<MaterialTheme xmlns="using:Uno.Material"
				               ColorPaletteOverrideSource="ms-appx:///Style/Application/MaterialColorsOverride.xaml"
				               FontOverrideSource="ms-appx:///Style/Application/MaterialFontsOverride.xaml" />

 				<!-- Load custom application resources -->
 				<!-- ... -->

 			</ResourceDictionary.MergedDictionaries>
 		</ResourceDictionary>
 	</Application.Resources>
 </Application>
```

And for C# Markup:
```cs
public static T UseMaterial<T>(this T app,
	ResourceDictionary overrides = null where T : Application
{
	return app.Resources(r => r.Merged(overrides { } ? new MaterialTheme().OverrideDictionary(overrides) : new MaterialTheme()));
}
```

**Comment by kazo0** [comment]
We should be deprecating the old initialization method of using `MaterialColors`, `MaterialFonts`, and `MaterialResources`. I was thinking we could just add something like `[Deprecated("Resource initialization for the Uno.Material theme should now be done using the MaterialTheme class instead.", DeprecationType.Deprecate, 3)]`

But it seems like this does not generate a warning when a application is using those classes in their `App.xaml`. Not sure if there is another way to warn devs that the classes are now deprecated? @jeromelaban?

**Comment by Xiaoy312** [comment]
try to use [`[Obsolete]`](https://learn.microsoft.com/en-us/dotnet/api/system.obsoleteattribute?view=net-7.0) attribute?

**Comment by kazo0** [comment]
Looks like Obsolete works a little better. Both `DeprecatedAttribute` and `ObsoleteAttribute` result in compiler warnings on build (only on Windows though, none for Uno platforms) but `ObsoleteAttribute` also result in editor hints as well:
![image](https://user-images.githubusercontent.com/4793020/213293234-316e511c-4ad1-4848-91ec-5eda5ca9011b.png)

**Comment by jeromelaban** [comment]
The problem with obsolete is that it breaks the build instantly if warnings as errors are enabled. This can make it difficult to disable the warning specifically for that use. I would go for `DeprecatedAttribute` instead, even if we need to create an analyzer for it to surface it.
