### ISSUE TITLE
MaterialCheckBoxStyle foreground color cannot be changed

### ISSUE THREAD

**Issue by arianeleonard** [unoplatform/Uno.Themes#823]
## Current behavior

The content color of a checkbox using MaterialCheckBoxStyle cannot be changed. The foreground is set to a color instead of using TemplateBinding. (https://github.com/unoplatform/Uno.Themes/blob/master/src/library/Uno.Material/Styles/Controls/v1/CheckBox.xaml)

## Expected behavior

When using MaterialCheckBoxStyle to style a checkbox, it should be possible to set the foreground of the checkbox (which means the text and the checkbox border) to any color. 

## How to reproduce it (as minimally and precisely as possible)

1. Launch repro sample 
[UnoApplicationTemplate.zip](https://github.com/unoplatform/Uno.Themes/files/9014077/UnoApplicationTemplate.zip)
2. On the login page, press on the "create account" button
3. On the create account page, scroll to the bottom and select "create account"
4. Notice that, just above the button, there is a blue checkbox with an error message around. It's foreground is set to white, but it still appears in blue.
## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [x] UWP
- [ ] MacOS

**Comment by agneszitte-nventive** [comment]
@kazo0 I will check on the status of this issue with you
