### ISSUE TITLE
TextBlock not centered with Checkbox 

### ISSUE THREAD

**Issue by Soap-141** [unoplatform/Uno.Themes#832]
## Current behavior

TextBlock not centered with CheckBox. We need to set LineHeight to 0 for it to be centered.

![Capture_89](https://user-images.githubusercontent.com/57812285/181367429-d81851cb-a862-4d46-af3d-71fcb17b00eb.PNG)

## Expected behavior

We should not have to set LineHeight to 0 for TextBlock to be centered with checkbox.

## How to reproduce it (as minimally and precisely as possible)

1. Download [SampleLineHeight.zip](https://github.com/unoplatform/Uno.Themes/files/9203384/SampleLineHeight.zip)
2. Open solution
3. Start project on windows, android, ios
4. Notice how the default textblock is not centered with checkbox but the other one is.

## Environment

Nuget Package: Uno.Material.WinUI

Package Version(s): 2.3.0-dev.4

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] ~~WebAssembly~~
- [x] UWP
- [ ] ~~MacOS~~

**Comment by Xiaoy312** [comment]
Material added some hardcoded LineHeight to all text styles. 

Of the many combination tried (LineStackingStrategy=BaselineToBaseline TextLineBounds=Full) was the 2nd closest for v-centering compared to (LineHeight=0). But mostly for UWP, the same works less suitably for ios/droid. 

And that is specific to the default font used in the material library. If a different font were to be used instead, the result could change. It would be best to use the default value (0), so it can adapt magically based on the font being used: 
> The height of each line in pixels. A value of 0 indicates that the line height is determined automatically from the current font characteristics. The default is 0.
> -- [TextBlock.LineHeight Property](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textblock.lineheight?view=winrt-22621)
