### ISSUE TITLE
[All][TextBox] Placeholder Text not Vertically Centered

### ISSUE THREAD

**Issue by Soap-141** [unoplatform/Uno.Themes#842]
## Current behavior

When using a `TextBox` with `MaterialOutlineTextBoxStyle` the placeholder text is not vertically centered.

![Capture_97](https://user-images.githubusercontent.com/57812285/188887893-e6a693da-8d28-4093-8c3b-553c220f2432.PNG)

## Expected behavior

When using a `TextBox` with `MaterialOutlineTextBoxStyle` the placeholder text should be vertically centered.

## How to reproduce it (as minimally and precisely as possible)

1. Download [MyApp.zip](https://github.com/unoplatform/Uno.Themes/files/9506488/MyApp.zip)
2. Open solution
3. Start project
4. Notice Placeholder Text in the TextBox is not vertically centered

## Environment

Nuget Package:

- Uno.WinUI
- Uno.Material.WinUI

Package Version(s):

- 4.5.0-dev.802
- 2.3.0-dev.12

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] ~~WebAssembly~~
- [ ] ~~UWP~~
- [x] WinUI
- [ ] ~~MacOS~~

**Comment by Soap-141** [comment]
Not fixed in 2.3.0-dev.20
![image](https://user-images.githubusercontent.com/57812285/189658603-34dd974d-254f-4f88-8d17-8b120687c61c.png)

**Comment by agneszitte-nventive** [comment]
Syncing with @Soap-141 at the moment to make sure of the nuget package version and the sample app he used for his tests

**Comment by agneszitte-nventive** [comment]
So after syncing with @Soap-141 regarding the vertical alignment issue for the TextBox, Thomas did a sample app but there were no font files added to the sample so it was using the default font.

Uno.Themes for Material is using Roboto font and the project is using EncodeSansCondensed font.

So I'm trying to make sure placeholder and editable text are properly vertically aligned regarding what font is used at the end

**Comment by agneszitte-nventive** [comment]
@jeromelaban, @kazo0 with all of the changes with the font lately I'm not sure if this issue is still relevant

**Comment by Xiaoy312** [comment]
should be covered within #974

**Comment by agneszitte** [comment]
@jhanvi03 I will let you verify the Material TextBox (that you can test with Gallery Canary) to see if we still have some vertical alignment issues please. If so please leave more details for the impacted platforms. If not we can close this issue.

**Comment by jhanvi03** [comment]
Text seems to be align on iOS, Android and WinUI. 
![image](https://github.com/user-attachments/assets/4c9f1a57-e42a-49dc-9af2-7b4a00146dc7)

I have opened another issue for Icon not align with the text https://github.com/unoplatform/Uno.Themes/issues/1443

**Comment by agneszitte** [comment]
> Text seems to be align on iOS, Android and WinUI. 
> 
> I have opened another issue for Icon not align with the text #1443

Thanks @jhanvi03!
I am closing this issue then, and we will use https://github.com/unoplatform/Uno.Themes/issues/1443 to track the alignment issue when there is an icon.
