### ISSUE TITLE
Add support for CornerRadius in material ToggleButton 

### ISSUE THREAD

**Issue by iury-kc** [unoplatform/Uno.Themes#850]
## Current behavior

If the user override the cornerradius property in IconToggleButton in Figma Plugin it will not reflect in the render result. Only XAML. since the Theme is preventing to process the CornerRadius attribute.

## Expected behavior

To allow Component Override working propperly, it should be possible to override that.

## How to reproduce it (as minimally and precisely as possible)

Override the cornerradius property at the top frame of an IconToggleButton instance in FigmaFile and run the plugin.

**Comment by sakshi173** [comment]
@iury-kc, could you please confirm it is fixed or not, I am not getting what the issue is?
