### ISSUE TITLE
[Epic] Lightweight Styling

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#854]
Instead of having to override the ControlTemplate of any given Material/Cupertino style we should allow for [Lightweight Styling](https://learn.microsoft.com/en-us/windows/apps/design/style/xaml-styles#lightweight-styling)

All styles should be refactored to reference resource keys that follow an accepted standard naming scheme.

**All _Default_ styles (those without a `style-variant` should follow the resource key naming coming from the matching Fluent themeresources**

Proposed naming convention:
{?:style-variant}{control-name}{member}{?:visual-state}

| Name Part | Description |
| --- | --- |
| `style-variant` | **(Optional)** Certain styles have multiple variants. Ex: For Button we have style variants such as: Outlined, Text, Filled | 
| `control-name` | Name of the control type (Button, TextBox, CheckBox, etc.) |
| `member` | The property that this style should be assigned to (Foreground, Background, BorderBrush, etc.) |
| `visual-state` | **(Optional)**  Specifies which `VisualState` that this resource will be applied to (PointerOver, Checked, Disabled, etc.)  |

## Required Styles

- https://github.com/unoplatform/Uno.Themes/issues/1063
- https://github.com/unoplatform/Uno.Themes/issues/986
- https://github.com/unoplatform/Uno.Themes/issues/987
- https://github.com/unoplatform/Uno.Themes/issues/988
- https://github.com/unoplatform/Uno.Themes/issues/989
- https://github.com/unoplatform/Uno.Themes/issues/990
- https://github.com/unoplatform/Uno.Themes/issues/991
- https://github.com/unoplatform/Uno.Themes/issues/992
- https://github.com/unoplatform/Uno.Themes/issues/993
- https://github.com/unoplatform/Uno.Themes/issues/994
- https://github.com/unoplatform/Uno.Themes/issues/1005
- https://github.com/unoplatform/Uno.Themes/issues/1006
- https://github.com/unoplatform/Uno.Themes/issues/1007
- https://github.com/unoplatform/Uno.Themes/issues/1008
- https://github.com/unoplatform/Uno.Themes/issues/1009
- https://github.com/unoplatform/Uno.Themes/issues/1018
- https://github.com/unoplatform/Uno.Themes/issues/1019
- https://github.com/unoplatform/Uno.Themes/issues/1110
- https://github.com/unoplatform/Uno.Gallery/issues/824

## EDIT: 2023-05-30

1. We will be removing the {design} prefix for the lightweight styling keys since this will hinder us from creating design-agnostic aliases of these keys. Because of a [limitation in the way resources are resolved](https://learn.microsoft.com/en-us/windows/apps/design/style/xaml-styles#aliasing-control-resources-to-new-names): if you create an alias (B) for a resource key (A) and then override the value of A, the alias (B) will still retain the original value of A and will not be updated. Therefore, we cannot rely on aliasing the material-specific lightweight styling keys as design-agnostic ones and expect it to work if people were to override the material specific ones, or vice-versa.
2. When creating lightweight style resource keys for a **default** style such as MaterialCheckBoxStyle, MaterialDatePickerStyle, etc (i.e. when there is no `style-variant`), we should be using the same key names as the ones coming from the Fluent resources as a base. We can go ahead and create additional lightweight resource keys, but we should at least be supporting the ones coming from Fluent. Example: the CheckBox style in Material should define the same resource keys that are defined [here](https://github.com/unoplatform/uno/blob/82a6bc7e7aedada2085de687d50f684fbcf11f6e/src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/CheckBox_themeresources.xaml#L15-L109), as well as any additional keys that may be useful to have. Certain extra lightweight resource keys can be created that are specific to the Material template, and in those cases we would prefix those with "Material". Example:

**Comment by Xiaoy312** [comment]
the proposed naming convention is expanded from the current style naming convention:
{design}{?:style-variant}{control-name}Style
{design}{?:style-variant}{control-name}**{member}{?:visual-state}**

eg:
MaterialFilledButtonStyle
MaterialFilledButtonBackground
MaterialFilledButtonBackgroundPressed

note: most styles are also aliased with a new key without the {design} prefix, so "MaterialFilledButtonStyle" can also referenced with "FilledButtonStyle" key.

**Comment by kazo0** [comment]
Something to consider here, overriding these resources is going to be tricky. If my Button Style is referencing MaterialFilledButtonBackground, and I override MaterialFilledButtonBackground within my App.xaml, the aliased FilledButtonBackground resource will continue to resolve to the original value of MaterialFilledButtonBackground and not the overridden value. The same issue applies in the other direction. If I were to override FilledButtonBrush in my App.xaml, the MaterialFilledButtonBrush will not resolve to the new overridden value, only usages of the shared key, FilledButtonBrush, are affected by the override.

Right now, the Material styles contain a mishmash of resource references using both the Material specific keys but also the aliased "shared" keys. 

[Example:](https://github.com/unoplatform/Uno.Themes/blob/f090ed9ce49f96039b6f2d3ed62a596689cb2bc9/src/library/Uno.Material/Styles/Controls/v2/Button.xaml#L466-L475)

```xml
<Setter Property="Foreground"
		Value="{StaticResource PrimaryBrush}" />
<Setter Property="BorderThickness"
		Value="{StaticResource MaterialOutlinedButtonBorderThickness}" />
<Setter Property="BorderBrush"
		Value="{StaticResource MaterialOutlinedButtonBorderBrush}" />
```

We need to figure out how we should be dealing with overrides. Should all Material styles **only** reference Material-specific resource keys? So, we'd use MaterialPrimaryBrush, MaterialOutlinedButtonBorderThickness, etc. In that case, we would provide aliases for these resources, but you would need to specifically override the resources using the Material prefix in order for the included styles to adapt properly. Overriding MaterialPrimaryBrush from Purple to Red will be reflected in the styles but any place that is directly referencing the aliased shared key of PrimaryBrush will still show Purple.

Otherwise, we get rid of the Material/Cupertino prefixes for resources, remove all the aliases, and they just get redefined in the Uno.Cupertino and Uno.Material libraries. There will have to be some special cases for resources that may be specific to one design system. In this case, we can reference PrimaryBrush, OutlinedButtonBorderThickness , etc. and those keys would also be the ones to override. 

I feel like maintaining the design system prefixes are kind of pointless. Unless there are some resources that exist in only one design-system, then those can be specially documented usages with the Material/Cupertino prefix. 

Problem with getting rid of the prefix is that it'll be a big breaking change for anyone that is currently using the Material prefixed keys. For the most part, people would most probably be using the shared aliases, but I'm assuming this'd need to be introduced as a new major version. 

@francoistanguay @Xiaoy312 @jeromelaban thoughts?

**Comment by jeromelaban** [comment]
Assuming current users don't override styles using Material-prefixed resources (which currently does not work with Uno), we could invert their definitions for the generic ones to be the original styles and the material prefixed ones to be the aliases.

We may also need to consider the scenario about the resolution in the gallery app, which contains both definitions simultaneously (if included at the app.xaml level), but may still resolve properly when using material-prefixed styles.

**Comment by kazo0** [comment]
Yeah I've already inverted the font resources in my branch:

[Typography.xaml](https://github.com/unoplatform/Uno.Themes/blob/dev/sb/typo-overrides/src/library/Uno.Material/Styles/Application/v2/Typography.xaml)

[TypographyOverrides.xaml](https://github.com/unoplatform/Uno.Themes/blob/dev/sb/typo-overrides/src/library/Uno.Material/Styles/Application/v2/TypographyOverrides.xaml) (should be called aliases, not overrides)

For the actual Styles themselves I don't think this is going to be an issue, it's more for the resources that the styles reference. Like for the Typography changes in the above links, I changed all usages of those resources within the styles to the non-prefixed/non-aliased ones.

So either, 
- Generic resource keys are the original definition and the styles reference the generic keys directly. So then overriding FilledButtonBackground will be reflected in the FilledButtonStyle. Or,
- The styles reference only the aliased/prefixed resources and you would then need to specify the design system prefix when overriding. So in order for FilledButtonStyle to reflect the Background override, it needs to reference **Material**FilledButtonBackground

My feeling is people should not use prefixed resource keys within the app, same way they should be using the non-prefixed style keys. Only thing that messes things up are apps like Gallery where you need a way to directly reference the proper design system resources. So aliasing to prefixed keys will work but then you'd need to know that your overrides should be using the prefixed keys.

**Comment by kazo0** [comment]
FYI for the issue of resource aliases not reflecting the overridden values, it seems that this is a known issue and pain point: https://github.com/microsoft/microsoft-ui-xaml/issues/2913

**Comment by kazo0** [comment]
Looking back on this, we should be going with the original design and allowing lightweight styling at a **per-control** level. Where we would be able to override something like a brush in the Material style for NavigationViewItem called `MaterialNavigationViewItemBackgroundSelected`, rather than needing to locally override the `PrimarySelectedBrush` that this alias would be referencing.

Proposal updated and copied to the original post:

Proposed naming convention:
{design}{?:style-variant}{control-name}{member}{?:visual-state}

| Name Part | Description |
| --- | --- |
| `design` | A prefix for the design system (Material, Cupertino, etc.) |
| `style-variant` | **(Optional)** Certain styles have multiple variants. Ex: For Button we have style variants such as: Outlined, Text, Filled | 
| `control-name` | Name of the control type (Button, TextBox, CheckBox, etc.) |
| `member` | The property that this style should be assigned to (Foreground, Background, BorderBrush, etc.) |
| `visual-state` | **(Optional)**  Specifies which ` VisualState` that this resource will be applied to (PointerOver, Checked, Disabled, etc.)  |

**Comment by agneszitte** [comment]
Closing this epic issue as the only left is https://github.com/unoplatform/Uno.Themes/issues/1063 which is already in progress
