### ISSUE TITLE
Split into separate WinUI/UWP projects for Cupertino/Material

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#875]
Follow the pattern done elsewhere and have a Uno.Material.csproj + Uno.Material.WinUI.csproj rather than dealing with both UWP and WinUI in a single csproj

**Comment by Xiaoy312** [comment]
We should probably also start including uwp-only.slnf or winui-only.slnf to help improve debug/build time/experience.
The project is starting to get bloated. Somewhat fine here, but much worse in toolkit.
