### ISSUE TITLE
[Cupertino] Cannot find a Resource with the Name/Key CupertinoEmptyToTrue 

### ISSUE THREAD

**Issue by matizk144** [unoplatform/Uno.Themes#891]
## Current behavior

Once you would like to use Style for TextBox of PasswordBox app throw exception:
Cannot find a Resource with the Name/Key CupertinoEmptyToTrue

## Expected behavior

Application should render controls without exceptions :)

## How to reproduce it (as minimally and precisely as possible)

Use Uno.Cupertino library in version 2.3.0 in your application and try bind Style for Textbox: CupertinoTextBoxStyle Or PasswordBox: CupertinoPasswordBoxStyle

or

pull from Github  and launch Uno.Gallery project on UWP.

## Environment

Nuget Package:

Package Version(s): 2.3.0

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [x] UWP
- [ ] MacOS
- [x] WinUi

**Comment by kazo0** [comment]
Thanks for the report @matizk144!

I believe the issue should be fixed in the latest -dev package builds. 

If you use version 2.4.0-dev.68 or 2.4.0-dev.66 does it work?

**Comment by matizk144** [comment]
Thanks for quick answer. I verified on 2.4.0-dev.68 and both control works as expected.
