### ISSUE TITLE
[SPEC] Material/Cupertino init for Markup

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#892]
To allow for a more fluent style of initializing the Themes resources using something like C# Markup, we need to make some changes to the Material/Cupertino ResourceDictionaries that are required in an app's App.xaml. We currently have the ability to override the Colors and Fonts used by Uno.Material and Uno.Cupertino through the use of an [`OverrideSource`](https://github.com/unoplatform/Uno.Themes/blob/f090ed9ce49f96039b6f2d3ed62a596689cb2bc9/src/library/Uno.Material/MaterialFonts.cs#L15-L26) DependencyProperty. This property is just a string that accepts a URI to the dictionary containing the overridden values.

We'll need to have a way of specifying an actual instance of ResourceDictionary that you'd like to provide the Color/Fonts overrides.

The proposal is to add a separate `Override` DependencyProperty that will be of type `ResourceDictionary`. With this new property, setting `OverrideSource` would simply set the `Override` property to an instance of `ResourceDictionary` with the `Source` URI set as the value of `OverrideSource`. This would also mean changing the [MergedDictionaries logic](https://github.com/unoplatform/Uno.Themes/blob/f090ed9ce49f96039b6f2d3ed62a596689cb2bc9/src/library/Uno.Material/MaterialFonts.cs#L33-L44) to only check if `Override` is `null` rather than relying on the value of `OverrideSource` since we can't be sure that the `OverrideSource` will always have a value.

So in the App.xaml, we can still doing the following:

```xml
<MaterialColors xmlns="using:Uno.Material"
				OverrideSource="ms-appx:///ColorPaletteOverride.xaml" />
<MaterialFonts xmlns="using:Uno.Material"
				OverrideSource="ms-appx:///MaterialFontsOverride.xaml" />
<MaterialResources xmlns="using:Uno.Material" />
```

But now we can initialize the MaterialColors and MaterialFonts from C# and override the resources by setting the `Override` property.

So we'd be able to do something like this:

```cs
App.Resources(r => r.Merged(
	new MaterialColors().Override(myColorOverrideDictionary),
	new MaterialFonts().Override(myFontOverrideDictionary),
	new MaterialResources()));
```

We can then create an extension method like:

```cs
public static IApplicationBuilder UseMaterialTheme(this IApplicationBuilder builder, ResourceDictionary? colorOverride = null, ResourceDictionary? fontOverride = null)
{
	builder.App.Resources(r => r.Merged(
		new MaterialColors().Override(colorOverride),
		new MaterialFonts().Override(fontOverride),
		new MaterialResources()));
}
```

Or is the `UseMaterialTheme` not necessary and we can just rely on the generated fluent `Override` property?

cc: @francoistanguay @ajpinedam @dansiegel @Xiaoy312

**Comment by kazo0** [comment]
Changed code example from:

```cs
App.Resources(r => r.Merged(new MaterialColors().Override(myColorOverrideDictionary))
                     .Merged(new MaterialFonts().Override(myFontOverrideDictionary))
                     .Merged(new MaterialResources());
```

to

```cs
App.Resources(r => r.Merged(
	new MaterialColors().Override(myColorOverrideDictionary),
	new MaterialFonts().Override(myFontOverrideDictionary),
	new MaterialResources()));
```

**Comment by kazo0** [comment]
@dansiegel, updated the code example. So was your argument that we shouldn't really need the `UseMaterialTheme` and we the syntax using the ResourceDictionaryBuilder would be sufficient?

**Comment by francoistanguay** [comment]
I think I'd like to keep a .UseMaterial(this Application app, overrides....) as I think the order of the dictionaries is important and kinda complex)....

I would extend Application instead of ApplicationBuilder so not to have a dependency on Uno.Extensions.Core and only have a dependency on C# Markup

And we could have a .UseMaterialToolkit(...) extensions as well mayve if useful?

**Comment by kazo0** [comment]
Yeah i added a spec for Toolkit here: https://github.com/unoplatform/uno.toolkit.ui/issues/416

I'm guessing we could also include a call to UseMaterial() within UseMaterialToolkit(). In that case, UserMaterialToolkit would also need to accept an optional color/font override dictionary

**Comment by francoistanguay** [comment]
Then I'd probably keep both separate for now instead of Toolkit having to facade Material by replicating all arguments..

**Comment by francoistanguay** [comment]
Oh and I think UseMaterial/Toolkit should be Fluent on Application so you can do
builder.Application.UseMaterial(overrides....).UseMaterialToolkit() at least....

**Comment by kazo0** [comment]
So we would have the following extension method:

```cs
public static partial class MaterialMarkup
{
	public static T UseMaterialTheme<T>(this T app) where T : Application
	{
		app.Resources(r => r.Merged(
			new MaterialColors(),
			new MaterialFonts(),
			new MaterialResources())
		);

		return app;
	}
}
```

If we want to be able to add the `IApplicationBuilder` extensions then Uno.Material.WinUI.Markup would need to have a dependency on Uno.Extensions.Hosting, which I assume we don't want to do, @francoistanguay?

**Comment by kazo0** [comment]
Oh I just saw 

> I think I'd like to keep a .UseMaterial(this Application app, overrides....) as I think the order of the dictionaries is important and kinda complex)....
> 
> I would extend Application instead of ApplicationBuilder so not to have a dependency on Uno.Extensions.Core and only have a dependency on C# Markup
> 
> And we could have a .UseMaterialToolkit(...) extensions as well mayve if useful?

Oh I just noticed the mention of using Application instead of ApplicationBuilder, so that answers my question about the Extensions dependency

**Comment by kazo0** [comment]
Implemented by https://github.com/unoplatform/Uno.Themes/pull/896
