### ISSUE TITLE
Init crashes for override ResourceDictionaries

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#907]
Getting a crash on Windows when initializing MaterialColors/MaterialFonts in the App.xaml

![MicrosoftTeams-image](https://user-images.githubusercontent.com/4793020/211836124-993f38d9-fb52-4ee3-a45b-60ef3e469c7a.png)

**Comment by Xiaoy312** [comment]
I think, for the new "markup-syntax", you dont need to inject a `ResourceDictionary`, but should be injecting a `Func<>` of instead.
That way you can bypass the problem of same dictionary being merged into multiple dictionaries.
