### ISSUE TITLE
[Windows] CommandBar throws an System.Runtime.InteropServices.COMException using Material resources

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/Uno.Themes#914]
## Current behavior
Navigating to a page with CommandBar crashes the windows app with unhandled exception using one of these resources
```
<MaterialResources xmlns="using:Uno.Material" />
<ToolkitResources xmlns="using:Uno.Toolkit.UI" />
<MaterialToolkitResources xmlns="using:Uno.Toolkit.UI.Material" />
```

## Expected behavior
No crash

## How to reproduce it (as minimally and precisely as possible)
1. Create uno project
2. Add toolkit with material resources
3. Add resources to the Dictionary
4. Create page with CommandBar
5. Start windows and navigate to the page containing CommandBar

## Environment

Nuget Package:
Uno.WinUI 4.5.0-dev.521
Uno.Toolkit.WinUI 2.3.0-dev.6
Uno.Toolkit.WinUI.Material 2.3.0-dev.6

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [X] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [X] 2022 (version: )
- [ ] for Mac (version: )

**Comment by kazo0** [comment]
Also, as an FYI, there is now a newer control that you can use for the native navigation bars. The NavigationBar control that lives inside of the Uno.Toolkit.UI packages is now the recommended control to use for this scenario. Docs for Toolkit can be found here: https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/getting-started.html
