### ISSUE TITLE
Material Button not showing when used with new solution structure

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/Uno.Themes#918]
## Current behavior

Run the following to generate a new app based on the Uno.Extensions template
```
dotnet new install Uno.Extensions.Templates::2.3.0-dev.650
dotnet new unoapp-extensions -o ReproApp
```
The created ReproApp should contain a button on the mainpage but when you run the app on Windows, the button doesn't show

## Expected behavior

The button should show

## How to reproduce it (as minimally and precisely as possible)
See steps above

Alternatively,
Create a new app using the unoapp template (dotnet new install Uno.ProjectTemplates.Dotnet::4.7.37) 
Add reference to Material
Add Material to appresources
Add Button to mainpage
Run Windows target - Button won't be visible

## Environment

Nuget Package:
[2.5.0-dev.15](https://www.nuget.org/packages/Uno.Material/2.5.0-dev.15)

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [X] WinUI
- [ ] MacOS

## Anything else we need to know?

I've tried this version of material with the old solution structure (see version 4.6.39 of the project templates) and it works fine
I've also upgraded the old solution to the latest 4.7 release of uno and that works fine as well.

**Comment by Youssef1313** [comment]
I'll look and see if I can find something.

**Comment by Youssef1313** [comment]
I took a look. I wasn't able to find the root cause, but I found out that adding an explicit reference to Uno.WinUI with latest dev version works. `<PackageReference Include="Uno.WinUI" Version="4.8.0-dev.332" />`

Any reason Uno.Material packages are still referencing 4.5.x?

**Comment by eriklimakc** [comment]
@nickrandolph @kazo0 @Youssef1313 Uno.WinUI 4.7.44 fixed this issue on SimpleCalc .net7.

**Comment by Youssef1313** [comment]
Good!

Very likely related to the ElevatedView issue that was backported to 4.7.

Let's close then.
