### ISSUE TITLE
Fix opacity values of 4 brushes in Themes to match original guidance and Figma File

### ISSUE THREAD

**Issue by NVLudwig** [unoplatform/Uno.Themes#928]
Note: This is a low priority fix, these brushes are legacy from M2 components and only one of them brushes is currently actively used in the Figma file

## Current behavior

PrimarySelectedBrush -----------> Expected 08% ---------> Actual 16%
OnPrimaryMediumBrush ---------> Expected 74% ---------> Actual 54%
OnPrimaryLowBrush -------------> Expected 38% ---------> Actual 32%
OnPrimarySelectedBrush --------> Expected 08% ---------> Actual 16%

## How to reproduce it (as minimally and precisely as possible)

Observe values in Themes and compare to Figma file

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [X] iOS
- [X] Android
- [X] WebAssembly
- [ ] UWP
- [X ] MacOS

**Comment by NVLudwig** [comment]
@nickrandolph tagging you on this as you found it.

**Comment by Xiaoy312** [comment]
It is worth mentioning that the reason we kept the original values is because certain control styles carried over from v1 and probably expect those values.

**Comment by NVLudwig** [comment]
@Xiaoy312 The expected values above are those for Material 2so they are legacy but they are also incorrect at the moment

**Comment by NVLudwig** [comment]
This is now deprecated
