### ISSUE TITLE
Text is not visible in Filled TextBox when focused in Material Dark Theme

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/Uno.Themes#932]
## Current behavior
The text in the Filled TextBox is not visible when it is focused in Material when in Dark Theme with the default color.
<img width="692" alt="image" src="https://user-images.githubusercontent.com/78549750/220854796-9965d2ac-0590-4a31-9359-d384d4c0530d.png">

## How to reproduce it (as minimally and precisely as possible)

Open the Uno Gallery and set the theme to dark. 

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] UWP
- [x] MacOS

**Comment by morning4coffe-dev** [comment]
@NVLudwig

**Comment by NVLudwig** [comment]
This is the same issue as [934](https://github.com/unoplatform/Uno.Themes/issues/934)
