### ISSUE TITLE
Add Tint Override Property

### ISSUE THREAD

**Issue by NVLudwig** [unoplatform/Uno.Themes#935]
## What would you like to be added:
Allow a user to keep elevation while opting out of using Tints on specific components

## Why is this needed:
Follow M3 guidance more closely
Give end users flexibility
Allow futur versions of the Figma file to be styled Cupertino and Fluent

## For which Platform:

- [X] UWP
- [X] iOS
- [X] Android
- [X] WebAssembly
- [X] macOS

## Anything else we need to know?

Linked to this [EPIC](https://github.com/unoplatform/Uno.Themes/issues/936)

**Comment by kazo0** [comment]
Implemented by https://github.com/unoplatform/Uno.Themes/pull/930
