### ISSUE TITLE
[Material][TextBox][PasswordBox] Add support for Label and Placeholder at the same time

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#974]
## What would you like to be added:

Support for a Label as well as a PlaceholderText in TextBox controls. Right now we are using the PlaceholderText as the "Label" portion of the Material style. So, right now our Material style supports the Orange highlighted cases but we do not support the Red highlighted cases where we can have a PlaceholderText while still having a Label appear above

> columns [common states]: normal, focused, hovered, error, disabled(not in screenshot)
> rows ["text" states]: 
> - {label=Label, text=Input}, 
> - {label=Label}, 
> - {label=Label, placeholderText=Placeholder}

![image](https://user-images.githubusercontent.com/4793020/233129444-84519b6a-a4b7-4135-8f44-902780f58176.png)

**Comment by agneszitte** [comment]
If we replace the Label term with the TextBox Header property to have a better idea in the Material M3 Figma File.
Following this the Placeholder is not moving in any case, only the Header (aka Label for Material).
![image](https://github.com/unoplatform/Uno.Themes/assets/16295702/ce7c4c4a-db46-4286-b821-f0e6caa70971)
![image](https://github.com/unoplatform/Uno.Themes/assets/16295702/c3c29c0d-e39d-4ae8-9eba-1e5854517873)

**Comment by kazo0** [comment]
@NVLudwig fyi ^ this may mean some changes to the figma file

**Comment by kazo0** [comment]
I believe @NVLudwig is thinking it would be difficult to have the component behave in a Figma document to only have a Placeholder appear after the text has been focused

As it stands now, I believe our Material styles don't react to the Focus state do they @Xiaoy312 / @agneszitte ? For the most part, I believe I've only ever seen the Placeholder "appearing" after the Label has animated upwards in that reference app that this video is from. In the real, world you usually just get a blank field after the Label has moved:

<img width="379" alt="image" src="https://github.com/unoplatform/Uno.Themes/assets/4793020/dbaf6520-940e-4d8f-a4a6-ef60599fbdb9">

<img width="377" alt="MicrosoftTeams-image (1)" src="https://github.com/unoplatform/Uno.Themes/assets/4793020/2dec3d2a-34d9-4ded-b8cd-a1d7a31d7801">


plus I don't think I see that combination in the official [M3 Google Figma](https://www.figma.com/file/ox5ZruJkjIN0c13IwPwVNr/Material-3-Design-Kit-(Community)?type=design&t=UBLszZFbIUON8cMw-0), right?

![MicrosoftTeams-image (2)](https://github.com/unoplatform/Uno.Themes/assets/4793020/c9307093-4aba-4ab9-9024-d48e3fba4ce8)

but I do agree having the Placeholder appear after the Label has moved is more difficult. The scenario I see it being useful is say we have a TextBox with the Label as "Phone Number", then when the field is focused, the "Phone Number" slides up and you are left with a placeholder of something like "(###) ###-####" to show the expected format. Or something like "Birthday" and "MM/DD/YYYY"

**Comment by agneszitte** [comment]
@kazo0, @NVLudwig, @Xiaoy312 
It is the same behavior when testing the **Compose Material Catalog** from **Google**

https://github.com/unoplatform/Uno.Themes/assets/16295702/78e53e7f-ab84-4e00-a2b3-ad2b3ef3fbce

**Comment by eriklimakc** [comment]
In [Material M2](https://m2.material.io/components/text-fields#filled-text-field) page there's an example that shows Placeholder appearing after focus.

![image](https://github.com/unoplatform/Uno.Themes/assets/114886335/75d0104e-8638-4cf5-9cc2-d688db19a577)

@kazo0 There's a VisualState for focus in TextBox.xaml we could use if we're following this behavior.

**Comment by NVLudwig** [comment]
<img width="157" alt="image" src="https://github.com/unoplatform/Uno.Themes/assets/29584087/be45d011-0fbf-4d4d-a8fa-cf1eb927e256">
 ⇅
<img width="158" alt="image" src="https://github.com/unoplatform/Uno.Themes/assets/29584087/a06f930f-088c-4382-bbec-30c28a2c8a07">


I **slightly** prefer the originally agreed version where Placeholders are visible before the user interacts with the TextBox unless there was a previous input. Because It sets the expectation for the user before the field is focused and it's more likely that they will have read the instructions before typing (many people still look down at the keyboard while typing).

This could also work for me (with a cursor in the second case)
<img width="315" alt="image" src="https://github.com/unoplatform/Uno.Themes/assets/29584087/8111edfe-a658-434e-b9e6-10a2b10c1fc8">

**My only real blocker is** having the label travel to the top of the box and mask the Outline because I don't think we can support it in Figma (@SMarengere any ideas?)

**Comment by kazo0** [comment]
No I meant we currently don't support the animation of the Label/Header when the field is focused. For right now, we only seem to be animating the label when text is entered

**Comment by agneszitte** [comment]
> @agneszitte No I meant we currently don't support the animation of the Label/Header when the field is focused. For right now, we only seem to be animating the label when text is entered

I may be missing something here, but I don't think of a technical blocker for us to achieve the wanted behavior.
cf. a small test from @eriklimakc  https://github.com/unoplatform/Uno.Themes/issues/974#issuecomment-1554818966

@NVLudwig / @SMarengere 
![image](https://github.com/unoplatform/Uno.Themes/assets/16295702/c3602ad5-4513-41fd-b003-c3ba2639c12e)
We have a separate issue for the fact that the Label is not at the correct level for the TextBox Outline style, as right now, it is not done in the code also. And should be a separate concern in my opinion.
[[Material][TextBox] Invalid Label translation after start typing [Outline]](https://github.com/unoplatform/Uno.Themes/issues/895#top)#895

**Comment by agneszitte** [comment]
@NVLudwig (cc @kazo0 / @eriklimakc) so for this part you mentioned
![image](https://github.com/unoplatform/Uno.Themes/assets/16295702/af2c3fdf-4900-44ff-a7b9-c3364fc7049a)
If we go the route you prefer, note that:

1.  We will go a different route than the Official Material Google samples
2.  We will need to adjust the logic to have these specs instead:
     - Without Label/Placeholder, we will have a simple TextBox (matching Windows behavior)
     - With a Placeholder and no Label,  we will have a simple TextBox (matching Windows behavior).
       We shouldn't move or animate the Placeholder in any case in my opinion, if we are still following a bit the guidelines and Material M3 Figma file.
     - If there is a Label:
       - Without a Placeholder, the Header moves up and it will be empty underneath until some text is entered
       - With a Placeholder, the Header does not move, it is already at the top and shows also the Placeholder underneath until some text is entered

**Comment by eriklimakc** [comment]
So the final spec for this one would be:

1. When there are no placeholder or header: It will be a simple TextBox

2. When there is a placeholder but no header: It will display the placeholder in the "Normal" VisualState and it will disappear when a text is inputed

3. When there is header but no placeholder: It will display the Header aligned vertically in the center and it will animate upwards when the input is focused

4. When there are header and placeholder: It will display the Header aligned vertically in the center and when the TextBox is focused, the header will animate upwards and the Placeholder will become visible aligned vertically in the center until some text is inputed.

Agreed? @agneszitte @Xiaoy312 @kazo0 @NVLudwig

**Comment by agneszitte** [comment]
@NVLudwig / @kazo0 / @Xiaoy312 
At the moment I noticed @eriklimakc implemented the Material TextBox behavior - https://github.com/unoplatform/Uno.Themes/issues/974#issuecomment-1567366753
(instead of the version Ludwig preferred related to the placeholder - https://github.com/unoplatform/Uno.Themes/issues/974#issuecomment-1554984229)

You can test the outcome of his current [draft PR](https://github.com/unoplatform/Uno.Themes/pull/1014) here: https://salmon-rock-0cfebe70f-1014.eastus2.azurestaticapps.net/

@kazo0 / @NVLudwig As I said previously, I will let you decide what will be the final decision for the wanted behavior.

**Comment by NVLudwig** [comment]
> @NVLudwig so for this part you mentioned ![image](https://user-images.githubusercontent.com/16295702/239590623-af2c3fdf-4900-44ff-a7b9-c3364fc7049a.png) If we go the route you prefer, just note that:
> 
> 1. We will go a different route than the Official Material M2/M3 Google samples or the Material M2 doc
>    cf.
>    
>    * [Above video using Google Compose Material Catalog App](https://github.com/unoplatform/Uno.Themes/issues/974#issuecomment-1554525033)
>    * [@eriklimakc's comment](https://github.com/unoplatform/Uno.Themes/issues/974#issuecomment-1554809976)
> 2. We will need to adjust the logic to have these specs instead:
>    
>    * Without Label/Placeholder, we will have a simple TextBox (matching Windows behavior)
>    * With a Placeholder and no Label,  we will have a simple TextBox (matching Windows behavior).
>      **We shouldn't move or animate the Placeholder in any case in my opinion, if we are still following a bit the guidelines and Material M3 Figma file.**
>    * If there is a Label:
>      
>      * Without a Placeholder, the Label moves up and it will be empty underneath until some text is entered
>        ![image](https://user-images.githubusercontent.com/16295702/239596682-86a68467-6d22-45b3-ac12-37874bbce400.png) → ![image](https://user-images.githubusercontent.com/16295702/239596785-337367c1-3499-43eb-bc81-43ad1abac663.png) → ![image](https://user-images.githubusercontent.com/16295702/239596554-814b3ec9-97f6-40de-a7f9-49291e88ccf9.png)
>      * With a Placeholder, the Label does not move, it is already at the top and shows also the Placeholder underneath until some text is entered
>        ![image](https://user-images.githubusercontent.com/16295702/239595806-eaa9157a-372a-48a3-9235-d14e0832dd8f.png) → ![image](https://user-images.githubusercontent.com/16295702/239596412-cea9f921-5f5e-4580-90f6-bf27f83702be.png)→ ![image](https://user-images.githubusercontent.com/16295702/239596554-814b3ec9-97f6-40de-a7f9-49291e88ccf9.png)
> 
> So I will let you decide with @kazo0 what will be the final decision (cc @eriklimakc)

This is the way. ↑

Only change I would recommend is: we don't absolutely need to add the case where a TextBox has a Placeholder but no label. If it's extra work to make it leave that one out please, else it's not a huge sin.


-----------------
Reviewing the Figma File I noticed Placeholder is not longer in there, please correct this @SMarengere

**Comment by agneszitte** [comment]
@NVLudwig for the case where a TextBox has a Placeholder but no label it will behave like a usual TextBox (matching Windows behavior). Meaning the Placeholder will be visible inside until some text is entered. It is not extra work, it is already what it is in place in general.

Remember that on the implementation:
- Placeholder will use the Placeholder property of the TextBox control
- Label will use the Header property of the TextBox control

**Comment by agneszitte** [comment]
@eriklimakc I think it would be good to add some comments at the style level in the code to explicitly precise that we will go a different route than the Official Material M2/M3 Google samples & the Material doc regarding the fact that the Placeholder will always be visible.

cf. With a Placeholder, the Label does not move, it is already at the top and shows also the Placeholder underneath until some text is entered

**Comment by eriklimakc** [comment]
What when there's Header but no Placeholder? Should the Header animate upwards when focused or when starting to type?

@kazo0 @agneszitte @NVLudwig

**Comment by NVLudwig** [comment]
@eriklimakc 
Yes on focus the the label should immediately move up and the cursor should bink on and empty text field when there is no placeholder.
