### ISSUE TITLE
[Material] Lightweight Styling - ToggleSwitch Styles

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#990]
Following the guidelines from https://github.com/unoplatform/Uno.Themes/issues/854, refactor the resources for all styles related to this control into ThemeDictionaries ("Default"/"Light") and make sure to reference these resources using the `ThemeResource` binding in ALL places within the style

**Comment by agneszitte** [comment]
Will need to wait for the new ToggleSwitch to be merged first
https://github.com/unoplatform/Uno.Themes/pull/1031

**Comment by agneszitte** [comment]
https://github.com/unoplatform/Uno.Themes/pull/1031 is now merged
Ready for Lightweight Styling

**Comment by agneszitte** [comment]
Closed with https://github.com/unoplatform/Uno.Themes/pull/1130
